### ISSUE TITLE
We're sorry this game cannot be continued due to Set: uninitialized constant Engine::SharePool::Set Broken action: { "type": "par", "entity": 441, "entity_type": "player", "id": 11, "created_at": 1710643472, "corporation": "IC", "share_price": "124,0,12" }

### ISSUE THREAD

**Issue by digitalreign** [tobymao/18xx#10516] opened 2024-03-17 13:28 UTC
**What's your Game ID?**

https://18xx.games/game/156599?action=10

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by ollybh** [comment] 2024-03-17 13:38
Duplicate of #10484.

**Closed by ollybh** 2024-03-17 13:38 UTC
Labels: needs triage
