### ISSUE TITLE
[18CO] Illegal Action cannot buy share of ATSF

### ISSUE THREAD

**Issue by BellmakerSA** [tobymao/18xx#3066] opened 2021-01-04 22:39 UTC
Barat cannot buy a share of ATSF even though they can clearly do so:

https://18xx.games/game/20011

![ADAA28CD-A5EA-41BE-B6E2-08EF0D4E8D31](https://user-images.githubusercontent.com/73144084/103586801-d97ea400-4eb3-11eb-8313-a2fce4d42627.png)

**Comment by ryandriskel** [comment] 2021-01-05 14:40
Please use the history to navigate to the action where barat could not purchase ATSF shares and paste that link here. I see the game in the President's choice round when those messages were sent, but the screen shows Stock Round, so I am not sure when this problem occurred.

**Comment by ryandriskel** [comment] 2021-01-05 14:53
Your group was not the only one to report a similar issue. I am not able to reproduce any problems with hotseat mode, however. It would help me out a whole lot if you could UNDO that game to the point where an error is being thrown, as it must be specific to multiplayer, and that is VERY difficult for me to debug without a game in the broken state.

<img width="377" alt="Screen Shot 2021-01-05 at 7 50 37 AM" src="https://user-images.githubusercontent.com/15675400/103660360-ba6f2900-4f2a-11eb-815e-4f85980e8375.png">

**Comment by BellmakerSA** [comment] 2021-01-05 21:06
I rewound the game back barat’s turn in the President’s Round

**Comment by ryandriskel** [comment] 2021-01-06 04:32
Ok, I've been able to reproduce the problem locally. It looks like the server thinks it is a different player's turn than the browser. I don't have a solution yet but when I do I'll update here and once deployed you'll be able to resume your game.

**Comment by ryandriskel** [comment] 2021-01-06 05:04
Welp, I said that, and then an unrelated update made this game go poof! I'm sorry! Two more bugs have been fixed though.

I'm going to close this ticket because there is another report of this same issue with a game that did not disappear.

**Closed by ryandriskel** 2021-01-06 05:04 UTC
Labels: 18CO, bug
