### ISSUE TITLE
[1862] User cannot pass during merge (illegal action)

### ISSUE THREAD

**Issue by Krzysztof-PL** [tobymao/18xx#5799] opened 2021-06-22 20:48 UTC
Game ID: 47215 (stay open)

During pass in Merge step appears message:
The server did not accept this action due to: illegal action: Blocking step Acquier cannot proces action 274... refreshing

**Comment by roseundy** [comment] 2021-06-22 21:40
I can't reproduce this. Can you hard refresh your browser (on a PC: <ctrl><shift>R) and try again?

**Comment by Krzysztof-PL** [comment] 2021-06-22 21:51
We are trying all in Master Mode. I attach screenshot
![1862 error](https://user-images.githubusercontent.com/86325701/123004276-b0e05d00-d3b4-11eb-90d3-294007610450.jpg)

**Comment by roseundy** [comment] 2021-06-23 16:03
This was a challenging bug to find. The root cause was a rounding error when EUR merged earlier in the game.

**Comment by roseundy** [comment] 2021-06-23 16:06
Once the bug fix is released, you will find that the game will be on the redeem shares step for EUR.

**Closed** 2021-06-24 15:36 UTC
Labels: 1862, bug
