### ISSUE TITLE
[1870] buy share after selling gives error Illegal action: wrong number of arguments

### ISSUE THREAD

**Issue by RockCartel** [tobymao/18xx#9321] opened 2023-07-30 19:50 UTC
https://18xx.games/game/129078
Getting error when buying SLSF share, after selling 1 of each ATSF & MP share.
The server did not accept this action due to: Illegal action: wrong number of arguments (given 2, expected 0)... refreshing.
The action works fine in a hotseat copy of this game

**Comment by RockCartel** [comment] 2023-08-02 07:25
Getting the same error when only trying to sell the ATSF share (same game)

**Comment by RockCartel** [comment] 2023-08-02 19:35
It lets me sell 2 shares, but not 1

**Comment by xorbot135** [comment] 2023-08-22 22:03
Having this same issue here: https://18xx.games/game/124884#tools

SR7 player "zachchillman" can't buy and sell an slsf share which has reissued

**Comment by philcampeau** [comment] 2023-08-28 19:09
In both cases, without a link to the actual action where the problem was happening, it's hard to reproduce and fix.

**Comment by RockCartel** [comment] 2023-08-28 20:17
Tried to repro in a hotseat game and can't get the error. I guess it's semi-rare given the number of 1870 games not seeing it. I'm always playing 1870 so will record if/when it happens next.

**Comment by summerjumbo** [comment] 2023-09-25 03:47
same here
https://18xx.games/game/135402
player "seasons" could sell one share of SLFS and raised enough money to buy one share of ATSF.
but when the player tried to buy actually, the message "The server did not accept this action due to: illegal action: wrong number of arguments (given 2, expected 0)... refleshing." showed up and was forced to be back in the buying step.

**Comment by summerjumbo** [comment] 2023-09-25 04:53
how about this
https://gist.github.com/summerjumbo/0524aea9ffeb41f06b0fdfa81342600d

**Comment by summerjumbo** [comment] 2023-10-04 07:32
another case
https://gist.github.com/summerjumbo/a420ed2d613ceabb2ac0b6f3418202a3

**Comment by philcampeau** [comment] 2023-10-04 14:48
With all these examples, when I import the game in hotseat mode, or clone the game, I'm able to complete the action and continue. 

@summerjumbo on your end, if you go into Tools and click Clone game, are you able to make the moves in the cloned game?

**Comment by summerjumbo** [comment] 2023-10-04 17:30
yes, i could continue when i played the cloned games either.

**Comment by philcampeau** [comment] 2023-10-04 18:02
Yeah, that was actually a useless question. I wasn't thinking that when the site is running hotseat or cloned, it runs directly on the compiled Javascript. I needed to import the game into my local environment to run it in Ruby, and yeah now I'm getting the same error. Alright, time to do some digging!

**Comment by philcampeau** [comment] 2023-10-04 18:49
Alright, I think we found the issue. I pushed a fix. Once it gets implemented, you'll need to undo to the beginning of that player's turn, and everything should work fine.

**Closed** 2023-10-04 18:55 UTC
Labels: 1870, stock market

**Comment by summerjumbo** [comment] 2023-10-05 04:38
thanks!
