### ISSUE TITLE
18EU - Clicking on button to buy a minor company (#5 for $50) causes a never return timeout.  Game Id 133714

### ISSUE THREAD

**Issue by Rupre** [tobymao/18xx#9615] opened 2023-09-15 03:40 UTC
**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by philcampeau** [comment] 2023-10-03 14:43
I can't even load this locally as a hotseat game. Possibly this is something that was also fixed by #9663

**Comment by andrewzwicky** [comment] 2024-01-09 23:13
As far as I can tell, the way to trigger this is to do the following:

1. P1 **with < $100** sets up auto actions for "buy price" for some minor.
2. P2 selects a **different** minor for auction (initial bid or not is irrelevant, it triggers in both cases).
3. Resolve that auction.

The game gets stuck in an infinite loop resolving a continuous stream of Pass actions for P1.  `@ auctioning` and related things are all clear because the first step is that the auction is resolved, so active_bidders, etc. are all emptied out before the auto actions get to start resolving.

If P1 has enough money to participate, the auto action is properly disabled (different minor selected).  So I think the root cause is basically that auto actions aren't disabled in the case where P1 is eliminated from the auction immediately.

**Closed** 2024-01-25 03:45 UTC
Labels: bug, 18EU
