### ISSUE TITLE
[18Mag] Magyar Államvastutak generating an error: Nil can't be coerced into integer

### ISSUE THREAD

**Issue by edfactor29** [tobymao/18xx#9313] opened 2023-07-22 13:57 UTC
Id: 129270

https://18xx.games/game/129270

**How to Reproduce the Bug?**

During the first Operating round whenever i try to use the +1 ability on company 15

**Which Browser / Platform?**

I am using Chrome

**Comment by philcampeau** [comment] 2023-07-24 18:21
In your gamestate right now it looks like the +1 from Magyar Államvastutak has already been added to the 2 train. 

When I clone the game and play, I'm able to run a 2+1, pay out, skip trains, and move on to the next corp's turn. Is this not your experience?

![image](https://github.com/tobymao/18xx/assets/26125362/060aba1e-cec9-45ad-bc49-a7ec7a5f4560)

**Comment by philcampeau** [comment] 2023-07-25 13:13
Can you post a screenshot of the error message?

**Comment by edfactor29** [comment] 2023-07-25 16:29
![Screenshot (1)](https://github.com/tobymao/18xx/assets/64444723/13d8e55c-849b-4d50-9e27-6f1fac15e968)

**Comment by edfactor29** [comment] 2023-07-25 16:29
yes i should have thought of that i guess.

**Comment by philcampeau** [comment] 2023-07-26 14:02
Ah, in that case, this is a duplicate of issue #9198. I'll close this issue and add a note to that one.

**Closed by philcampeau** 2023-07-26 14:02 UTC
Labels: bug, 18Mag

**Comment by philcampeau** [comment] 2024-05-29 03:14
Long awaited update, but I've just run some tests and it looks like this issue has been resolved. I'm completely unable to reproduce it.
