### ISSUE TITLE
[18EU] Bug reporting, game cannot be continued

### ISSUE THREAD

**Issue by Ticketautomat1** [tobymao/18xx#9826] opened 2023-10-24 19:14 UTC
game link: https://18xx.games/game/133286?action=519

game cannot be continued due to all_abilities and broken action. Please have a look.

I can't end the game manually by myself.

**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by volker18xxdev** [comment] 2023-10-26 07:59
kodemaniak want to discard a minor. Button "discard minor" produce an error.
![grafik](https://github.com/tobymao/18xx/assets/80693707/77ec80a0-a3a4-49fd-8659-669fbc0a2179)

**Comment by ollybh** [comment] 2023-10-28 09:35
Closing, duplicate of #9805.

**Closed by ollybh** 2023-10-28 09:35 UTC
Labels: needs triage
