### ISSUE TITLE
[1830] Game cannot be continued

### ISSUE THREAD

**Issue by bootydharma** [tobymao/18xx#10492] opened 2024-03-17 07:39 UTC
**What's your Game ID?** 15230

Link - https://18xx.games/game/153280

- (optional) Provide a link to the specific action that triggered the bug using the `Game` tab and `History` navigation arrows - https://18xx.games/game/153280?action=18

**Which Browser / Platform?** 1.63.174 Chromium: 122.0.6261.128 (Official Build) (64-bit)

**Comment by ollybh** [comment] 2024-03-17 10:51
Duplicate of #10484.

**Closed by ollybh** 2024-03-17 10:51 UTC
Labels: needs triage
