### ISSUE TITLE
1847 AE https://18xx.games/game/164391  Error when trying to purchase the d-share of Nordbahn

### ISSUE THREAD

**Issue by Trainsinvestite** [tobymao/18xx#10802] opened 2024-05-26 15:31 UTC
**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by benjaminxscott** [comment] 2024-05-28 03:42
Dupe of https://github.com/tobymao/18xx/issues/10814

**Closed by benjaminxscott** 2024-05-28 03:42 UTC
Labels: needs triage
