### ISSUE TITLE
1862. Train buying message after game end

### ISSUE THREAD

**Issue by heliopolix** [tobymao/18xx#5788] opened 2021-06-21 22:32 UTC
Game ended, last company continued to skip buying trains during post-game chat after each chat entry.

https://18xx.games/game/47101

**Comment by roseundy** [comment] 2021-06-23 16:01
Well, that too way too long. Root cause was a rounding error when EUR merged earlier in the game.

**Comment by roseundy** [comment] 2021-06-23 18:29
Typo on handling receivership train buying. Was '@pass = true', should be '@passed = true'.

**Closed** 2021-06-24 15:36 UTC
Labels: 1862, bug
