### ISSUE TITLE
1849 - 1st SR PAR Values

### ISSUE THREAD

**Issue by richardtempura** [tobymao/18xx#4319] opened 2021-03-05 02:20 UTC
We just started a game of 1849 2 Sicilies and we had the choice od setting par value at 144. Which should'nt be available at the beginning of the game.
We didn't want to fiddle around and try to buy it at that value, but shouldn't it be unavailable?

**Comment by dfannius** [comment] 2021-03-05 02:24
Duplicate of #4266.

**Closed by dfannius** 2021-03-05 02:24 UTC
