### ISSUE TITLE
[1822MRS] Game broken: still need to sell shares before a loan can be granted

### ISSUE THREAD

**Issue by kodemaniak** [tobymao/18xx#10079] opened 2024-01-01 12:55 UTC
In

https://18xx.games/game/145577?action=505

the game is broken with the error:

```
We're sorry this game cannot be continued due to GameError: SteBar still need to sell shares before a loan can be granted
Broken action: { "type": "buy_train", "entity": "16", "entity_type": "corporation", "id": 506, "created_at": 1703864517, "train": "4-2", "price": 300, "variant": "4" }
Please [raise a bug report](https://github.com/tobymao/18xx/issues?q=is%3Aissue+is%3Aopen+label%3A1822,%22needs%20triage%22) and include this link (https://18xx.games/game/145577?action=505)
```

**Comment by vandamm** [comment] 2024-01-02 12:08
Caused by #10059

**Comment by kodemaniak** [comment] 2024-01-21 08:30
I am not sure what the status of this problem is, but could you delete the broken game (https://18xx.games/game/145577) for me? I can not delete it myself due to the bug.

**Comment by michaeljb** [comment] 2024-01-24 03:42
Closing as dup of #10059, will delete game if it cannot be pinned.

**Closed by michaeljb** 2024-01-24 03:42 UTC
Labels: needs triage, 1822
