### ISSUE TITLE
[1846] Erie cannot token Erie

### ISSUE THREAD

**Issue by wcraigtrader** [tobymao/18xx#1003] opened 2020-07-05 20:27 UTC
Erie just opened, issued 3 shares, and with the track already in place, should be able to token the reserved spot in Erie, but cannot.

[1846-erie-cannot-token-erie.txt](https://github.com/tobymao/18xx/files/4875530/1846-erie-cannot-token-erie.txt)

**Comment by StormCrow42** [comment] 2020-07-06 02:42
I imported the game and was able to place the Erie token.

**Comment by tobymao** [comment] 2020-07-06 05:06
i haven't verified but it looks like this cannot be reproduced, closing for now

**Closed by tobymao** 2020-07-06 05:06 UTC
