### ISSUE TITLE
1870: company didn't move one row downward and one column to the right, if sold out and at the top of the market

### ISSUE THREAD

**Issue by hegeton** [tobymao/18xx#5231] opened 2021-05-03 21:54 UTC
https://18xx.games/game/36766?action=723

https://18xx.games/game/36766 at the end of SR 7

in this case the SP didn't so

**Comment by daniel-sousa-me** [comment] 2021-05-04 11:45
Duplicate of #5067

**Comment by crericha** [comment] 2021-05-04 14:46
Duplicate

**Closed** 2021-05-04 14:46 UTC
