### ISSUE TITLE
[1846] wrong player highlighted for Priority Deal on spreadsheet

### ISSUE THREAD

**Issue by waaayback** [tobymao/18xx#2956] opened 2021-01-01 16:36 UTC
https://18xx.games/game/20341?action=402

Start of SR4.  Cannister is (correctly) 'up' (see end of SR3).  However, on the spreadsheet tab, jjrbedford is incorrectly highlighted as the priority deal holder.

**Comment by michaeljb** [comment] 2021-01-01 20:15
The entities tab also highlights jjrbedford as having priority deal. This is showing who would have priority _next_ SR if the current SR ended without anyone taking any more actions. I think this is the intended behavior.

**Comment by dfannius** [comment] 2021-01-01 20:21
When I looked at that game at action 402 just now, Cannister had priority deal in both the Entities tab and the Spreadsheet, which I assert is correct (Cannister was first to pass in SR2). So my observations don't seem to agree with either of yours...

**Comment by waaayback** [comment] 2021-01-02 13:30
Thanks for your replies. At the moment, this seems to be acting correctly (we are still in the SR and the highlighting is behaving correctly). I only saw that once, at the very beginning of the SR. 

I’ll leave this bug open until our next SR and see if it happens again.

**Comment by michaeljb** [comment] 2021-01-02 16:44
I could have been more clear, I was actually commenting on how it looks at https://18xx.games/game/20341?action=403 since that is actually the beginning of the SR

**Comment by dfannius** [comment] 2021-01-02 17:21
Aha. But if everyone passes, doesn't Cannister retain priority deal? So I would expect the priority deal marker to remain on Cannister until he actually takes an action.

**Comment by michaeljb** [comment] 2021-01-02 21:48
Yep, good point. I misremembered the rule for that case 🙂 
Interestingly, if everyone *does* pass 18xx.games does correctly leave priority deal on Cannister, so on the bright side this is just a cosmetic problem.

**Comment by dfannius** [comment] 2021-01-03 01:55
OK, there was a bug introduced a while ago when displaying the priority deal marker at the start of a stock round (in all tabs), fixed with #3002.

**Closed** 2021-01-03 02:50 UTC
Labels: bug, minor
