### ISSUE TITLE
Issue with 1849 (`pending_tokens' for #<Engine::Round::Auction:0x2a112> )

### ISSUE THREAD

**Issue by fabianpk** [tobymao/18xx#3207] opened 2021-01-10 21:35 UTC
Multiplayer game
I won the bid for RSA, but I can't set the par value. The error I get is `pending_tokens' for #<Engine::Round::Auction:0x2a112> 
The game is https://18xx.games/game/22029

**Comment by tysen** [comment] 2021-01-10 22:08
duplicate of #3175

**Closed** 2021-01-10 22:31 UTC
