### ISSUE TITLE
Out of order destination runs don't work in 1870

### ISSUE THREAD

**Issue by ventusignis** [tobymao/18xx#4747] opened 2021-03-24 01:06 UTC
https://gist.github.com/ventusignis/887f3a12782c661e4e113d1571e1cae1

FW was supposed to do its destination run as there was a 4T-sized connectino from Fort Worth to Denver after the Katy ran but it didn't get to do it.

**Comment by ventusignis** [comment] 2021-03-24 01:10
https://18xx.games/game/34179
The FW didn't get to do a destination run when it got back to its turn either

**Comment by daniel-sousa-me** [comment] 2021-03-27 23:06
I'm sorry, I had missed this report. Meanwhile this has been fixed by #4752

**Comment by crericha** [comment] 2021-04-15 21:19
Daniel's comment implies that the issue is resolved. @ventusignis, would you mind verifying with the gist and closing if resolved?

**Closed** 2021-05-05 12:53 UTC
Labels: 1870, bug, rules-broken
