### ISSUE TITLE
[18Neb] Some issues w/ P4 conversion

### ISSUE THREAD

**Issue by Boomcoach** [tobymao/18xx#10621] opened 2024-04-11 00:01 UTC
**What's your Game ID?**
159487
https://18xx.games/game/159487

In 1st SR I wanted to convert P4 to a share of the C&S, but game said I had no valid actions and skipped by me.

In SR2, when I converted P4, I was also given the chance to buy a share in the same action.

**Comment by benjaminxscott** [comment] 2024-04-11 05:25
So there's 3 issues here, the first of which is a wontfix

1 The issue of getting your last SR1 turn autoskipped even if you have an exchange power is a dupe of the oldest bug https://github.com/tobymao/18xx/issues/58

![image](https://github.com/tobymao/18xx/assets/1711810/d9fe0170-487f-4c78-a3e1-3a67d8f4fd77)

2 Shouldn't be able to exchange and buy in the same turn  (private language is "in lieu of a stock purchase")
https://gist.github.com/benjaminxscott/03b0ac394e2552ef0f4bdfe74e043631

3 The exchange throws an error if attempted before C&S has been parred (`undefined method price for nil`)

https://gist.github.com/benjaminxscott/23283f492033c55306f5184dd7cdab00
![Screenshot 2024-04-10 9 37 17 PM](https://github.com/tobymao/18xx/assets/1711810/0ff49920-e7d0-43ea-adb0-a0fbdcbd21f2)

**Closed** 2024-04-12 06:50 UTC
Labels: bug, 18Neb
