### ISSUE TITLE
Wrong turn notification

### ISSUE THREAD

**Issue by mikewill18xx** [tobymao/18xx#309] opened 2020-05-07 00:37 UTC
game 668 says it is mikewill's turn, but when the game is opened it is PedroS' turn

**Comment by jcoveney** [comment] 2020-05-07 04:21
This usually happens when a player undoes a move. I’ve had it happen as well.

**Comment by jenf** [comment] 2020-05-07 07:20
duplicate of #284

**Closed by jenf** 2020-05-07 07:20 UTC
