### ISSUE TITLE
[1817] Auto Actions do not match error

### ISSUE THREAD

**Issue by bridger15** [tobymao/18xx#8130] opened 2022-07-31 15:35 UTC
Getting this error at the top of the screen when I try to enable auto-pass in the game below:
https://i.imgur.com/qNx1SV7.png (The server did not accept this action due to: Auto actions do not match...refreshing.)

Game and specific action where this is occurring: https://18xx.games/game/91500?action=1030 (my turn in stock round)

This error comes up (and the game then refreshes) when I am clicking the "auto-pass" button in the main game tab, and also happens if I try to enable auto-pass from the 'auto' tab on my turn.

I've manually passed and then enabled auto-pass, so we'll see what happens next.

**Comment by bridger15** [comment] 2022-08-01 12:26
Note: Another player in the same game reported that they had seen the bug as well.  I can also confirm that if I enable auto-pass when it is *not* my turn (via the auto tab) that the auto-pass function does appear to work properly.

**Comment by crericha** [comment] 2022-08-05 01:31
Duplicate of #8064. Closing this one.

**Closed by crericha** 2022-08-05 01:31 UTC
