### ISSUE TITLE
[1822PNW] minor conversion treasury shares

### ISSUE THREAD

**Issue by akh911007** [tobymao/18xx#8425] opened 2022-10-06 01:05 UTC
https://18xx.games/game/97489

I converted minor 1 into CPR and the log indicates the remaining 8 shares were placed in the treasury. But later in the stock round CPR isn’t receiving money for shares purchased from the treasury like I expected them to be.

**Comment by akh911007** [comment] 2022-10-06 01:36
I may have misunderstood / misread the rules. I thought the company was operational immediately and would receive money from shares as they were bought. But instead, once 5 shares were purchased, the company received all of the money. Is this expected behavior?

**Comment by outsidePasser** [comment] 2022-10-06 02:14
I have to take a look - I'm not sure off the top of my head.  I'll check on this.

**Comment by ChrisTheCat** [comment] 2022-10-06 03:51
This is a duplicate of https://github.com/tobymao/18xx/issues/8423

akh911007 is correct.

**Closed** 2022-10-10 01:54 UTC
