### ISSUE TITLE
[1822] Paths between Merthyr Tydfil and Pontypool not correctly implemented.

### ISSUE THREAD

**Issue by ScottGiles** [tobymao/18xx#9097] opened 2023-04-10 18:43 UTC
Playing in game 115515.

The 20 minor should be able to run H33 (Gloucester) then G34 (Newport), F35 (Cardiff), E34, E32 and then end the run in F33.

According to 9.1.2, "When tracing routes, Merthyr Tydfil and Pontypool are termini if approached from the other city (Merthyr Tydfil for Pontypool, and Pontypool for Merthyr Tydfil). In other words, it is possible to trace a route directly from one to the other, but it is not possible to then continue the route beyond."  There is an example on the same page of the rulebook that has the SWR doing a route very similar to what I describe, and the text in the example seems to agree that the route I'm proposing is legal.

My understanding of the symbology on the board and also rule 9.1.2 is that you cannot do a run like cardiff -> 21 -> 20 -> Newport -> Gloucester.

The rules state that a valid station marker must be on the path of the route for a valid run.  It does not state that minors must **start** at their sole station marker.

**Comment by michaeljb** [comment] 2023-05-14 21:01
Possibly related to #7799

**Comment by michaeljb** [comment] 2024-06-08 23:53
duplicate of #9097

**Closed by michaeljb** 2024-06-08 23:53 UTC
Labels: routes, 1822
