### ISSUE TITLE
[1871 Old Prince] EMR stock selling incorrect

### ISSUE THREAD

**Issue by Kingsoby1** [tobymao/18xx#10628] opened 2024-04-13 20:45 UTC
The rules say that you must sell stock until you can buy a train. Then they indicate a maximum of three shares that can be sold per company. After you've sold a maximum of three shares per company and you still don't have enough funds, you can declare bankruptcy. 

When you do EMR in the implementation, you can simply sell one share from each company and then declare bankruptcy. You don't have to follow the rules as stated.  

Additionally, EMR allows you to sell down more than three shares. It should be a maximum of three per company per the rules.

**Comment by philcampeau** [comment] 2024-04-15 17:41
This is a duplicate of #8836. It does add helpful additional info, though, so I'll paste this report into the existing one.

**Closed by philcampeau** 2024-04-15 17:41 UTC
Labels: 1871
