### ISSUE TITLE
[1880] Game stuck on one Player's Company OR when another must lay a token

### ISSUE THREAD

**Issue by BluestBlood** [tobymao/18xx#8863] opened 2023-02-18 15:32 UTC
**What's your Game ID?**

https://18xx.games/game/112795

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

Stock Round was entered due to my company (BCR) being the last to not buy a 4+4
Another company (QSR) was floated by a player during the SR
When the SR Concluded, game shows me as active player even when the director of the QSR needs to place their token

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
- Chrome Version 110.0.5481.104 (Official Build) (64-bit)

![Untitled](https://user-images.githubusercontent.com/109913553/219874380-176af739-a4e2-4390-a1c1-cfe8a07606c1.png)
:support)
![Untitled](https://user-images.githubusercontent.com/109913553/219874376-61a74b70-28bb-44c8-a359-06ad917fbee2.png)

**Comment by bentziaxl** [comment] 2023-02-18 19:22
duplicate of #8821

**Closed** 2023-02-18 19:22 UTC
Labels: rules-broken, 1880
