### ISSUE TITLE
[18MS] - game not loading

### ISSUE THREAD

**Issue by Psylvania** [tobymao/18xx#9035] opened 2023-03-19 08:35 UTC
I'm unable to access the game at all.  After I click on it from the homepage it says 'loading game' but doesn't do so. I've tried from two laptops and my phone.

**What's your Game ID?**

https://18xx.games/game/116812

**How to Reproduce the Bug?**

it may be that others trying to load the game from the homepage experience a similar problem.[https://18xx.games/game/116812]() 

**Which Browser / 
I've been using chrome.

**Comment by dolfyner** [comment] 2023-03-21 05:24
Hi!
The game is stuck on loading for me too
Chrome on phone
Dolfyner

**Comment by benjaminxscott** [comment] 2023-03-22 22:44
dupe of #9042

**Closed by benjaminxscott** 2023-03-22 22:44 UTC
Labels: needs triage
