### ISSUE TITLE
[1888] can't continue due to "Set: uninitialized constant"

### ISSUE THREAD

**Issue by Noehrgel** [tobymao/18xx#10505] opened 2024-03-17 10:29 UTC
Hey folks,

came back to this error message today:

We're sorry this game cannot be continued due to Set: uninitialized constant Engine::SharePool::Set
Broken action: { "type": "par", "entity": 17020, "entity_type": "player", "id": 7, "created_at": 1710528299, "corporation": "LYR", "share_price": "90,2,3" }

It is a multiplayer game: https://18xx.games/game/156618?action=6

Thanks and keep up the great work,
Bernd

**Comment by ollybh** [comment] 2024-03-17 10:55
Duplicate of #10484.

**Closed by ollybh** 2024-03-17 10:55 UTC
Labels: needs triage
