### ISSUE TITLE
[1880] Jeme Tien Yow Engineer Office prompts for assign step when company already has D permit

### ISSUE THREAD

**Issue by crericha** [tobymao/18xx#9296] opened 2023-07-09 02:55 UTC
https://gist.github.com/crericha/53f48bddcb082f90b1fc2dcd35bbaed8

**Comment by benjaminxscott** [comment] 2023-11-09 20:46
Dupe of #9791 , the later ticket has more discussion so preferring that one

**Closed by benjaminxscott** 2023-11-09 20:46 UTC
Labels: bug, 1880
