### ISSUE TITLE
1867: Net worth on spreadsheet tab is wrong for Merger rounds

### ISSUE THREAD

**Issue by waaayback** [tobymao/18xx#4070] opened 2021-02-20 22:31 UTC
See title.  The net worth values during merger rounds incorrectly go down.

See this game:
https://18xx.games/game/27906?action=471

For example, look at the net worth values during MR3.  They all drop ~$200 from OR3.2, but then jump right back up again for SR4.

Looks like a formula is wrong somewhere...  :)

**Comment by dfannius** [comment] 2021-02-20 22:46
Duplicate of #4059.

**Closed by dfannius** 2021-02-20 22:46 UTC
