### ISSUE TITLE
We're sorry this game cannot be continued due to Set

### ISSUE THREAD

**Issue by tebones-work** [tobymao/18xx#10496] opened 2024-03-17 07:50 UTC
We're sorry this game cannot be continued due to Set: uninitialized constant Engine::SharePool::Set
Broken action: { "type": "par", "entity": 12904, "entity_type": "player", "id": 16, "created_at": 1709890862, "corporation": "WR", "share_price": "100,0,4" }
Please [raise a bug report](https://github.com/tobymao/18xx/issues?q=is%3Aissue+is%3Aopen+label%3A1856,%22needs%20triage%22) and include this link ()
**What's your Game ID?**
https://18xx.games/game/155633?action=15

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by ollybh** [comment] 2024-03-17 10:52
Duplicate of #10484.

**Closed by ollybh** 2024-03-17 10:52 UTC
Labels: needs triage
