### ISSUE TITLE
21Moon crashed, back to start after we were in SR 4

### ISSUE THREAD

**Issue by BillPeeck** [tobymao/18xx#10493] opened 2024-03-17 07:45 UTC
(https://18xx.games/game/152681?action=18)
Was ok yesterday when I looked, now is back to first stock buy round 1 with the following message.

We're sorry this game cannot be continued due to Set: uninitialized constant Engine::SharePool::Set
Broken action: { "type": "par", "entity": 7090, "entity_type": "player", "id": 19, "created_at": 1707937837, "corporation": "VH", "share_price": "60,5,2" }
Please [raise a bug report](https://github.com/tobymao/18xx/issues?q=is%3Aissue+is%3Aopen+label%3A21Moon,%22needs%20triage%22) and include this link (https://18xx.games/game/152681?action=18)

**Comment by ollybh** [comment] 2024-03-17 10:51
Duplicate of #10484.

**Closed by ollybh** 2024-03-17 10:51 UTC
Labels: needs triage
