### ISSUE TITLE
[1882] Game cannot be continued

### ISSUE THREAD

**Issue by lmenthe** [tobymao/18xx#10495] opened 2024-03-17 07:48 UTC
Game Id: 154986
Description "Night Country"

"We're sorry this game cannot be continued due to Set: uninitialized constant Engine::SharePool::Set
Broken action: { "type": "pass", "entity": 3440, "entity_type": "player", "id": 15, "created_at": 1709521547 }
include this link (https://18xx.games/game/154986?action=14)"

**Comment by ollybh** [comment] 2024-03-17 10:52
Duplicate of #10484.

**Closed by ollybh** 2024-03-17 10:52 UTC
Labels: needs triage
