### ISSUE TITLE
[18USA] Bridge private companies wrong description

### ISSUE THREAD

**Issue by giovandc** [tobymao/18xx#7540] opened 2022-03-26 10:09 UTC
The description of the bridge private companies "Comes with N $10 bridge tokens that may be placed by the owning corp in a city with $10 water cost, max one token per city, regardless of connectivity.. Allows owning corp to skip $10 river fee when placing track".
Actually, though, the connectivity is required to place the bridge token, so the description is wrong.

**Comment by dfannius** [comment] 2022-03-26 10:57
Duplicate of #7512.

**Closed by dfannius** 2022-03-26 10:57 UTC
Labels: duplicate, 18USA
