### ISSUE TITLE
[1817] Cannot continue, unitialized constant

### ISSUE THREAD

**Issue by UmbralCloud** [tobymao/18xx#10503] opened 2024-03-17 10:00 UTC
**What's your Game ID?**

Multiplayer game: https://18xx.games/game/138829?action=149

**How to Reproduce the Bug?**

This message appears whenever I access the game. The game itself seems to have massively rolled back:

We're sorry this game cannot be continued due to Set: uninitialized constant Engine::SharePool::Set
Broken action: { "type": "pass", "entity": 919, "entity_type": "player", "id": 150, "created_at": 1705498193 }
Please [raise a bug report](https://github.com/tobymao/18xx/issues?q=is%3Aissue+is%3Aopen+label%3A1817,%22needs%20triage%22) and include this link (https://18xx.games/game/138829?action=149)

**Which Browser / Platform?**

Microsoft Edge Version 122.0.2365.92 (Official build) (64-bit), Windows 11

**Comment by ollybh** [comment] 2024-03-17 10:54
Duplicate of #10484.

**Closed by ollybh** 2024-03-17 10:54 UTC
Labels: needs triage
