### ISSUE TITLE
[Multiple] The game engine allows two trains to run over converging track on a shared edge

### ISSUE THREAD

**Issue by spines83** [tobymao/18xx#1436] opened 2020-08-13 02:06 UTC
**Please provide**
* Issue title including game title and concise description, e.g. [18Chesapeake] C-P Private usable out of operating order
* Multiplayer? Link to the game with action number: Game tab -> History, press < to go to the previous action, copy the link and paste here, e.g. https://www.18xx.games/game/4011?action=173
* Hotseat? JSON: Tools -> Copy Game Data -> Create public gist on https://gist.github.com/ and paste link here, e.g. https://gist.github.com/username/07f4d5a2178...

It really helps us having a sample game to reproduce the issue.

(Note: We corrected our moves and made the legal ones, but the moves that should be illegal match up to the screenshots below)
https://18xx.games/game/5820?action=930
https://18xx.games/game/5848?action=416

**Describe the bug**
A clear and concise description of what the bug is. Include steps to reproduce the behavior. If applicable, add screenshots to help explain your problem.
e.g. In OR 2.1 B&O ran a 3 train from A to B to C. Revenue was $80 instead of $100.

The game engine allows two trains to run over converging track on a shared edge. In general, this should be illegal. Pictures explain it way better than words.

1846 (In the second one, NYC -> Fort Wayne + C&O -> Fort Wayne is valid)
![image](https://user-images.githubusercontent.com/1351013/90085896-0bb21e00-dce7-11ea-8960-91b3beca140c.png)
![image](https://user-images.githubusercontent.com/1351013/90085911-12409580-dce7-11ea-897e-84e4c7111786.png)

18Ches
![image](https://user-images.githubusercontent.com/1351013/90085825-f0471300-dce6-11ea-990f-117949d308f2.png)

**Comment by tobymao** [comment] 2020-08-13 05:03
duplicate of #1353

**Closed by tobymao** 2020-08-13 05:03 UTC
