### ISSUE TITLE
1822: Can't lay destination token

### ISSUE THREAD

**Issue by waaayback** [tobymao/18xx#4885] opened 2021-03-31 12:31 UTC
Twice in this game, a RR couldn't lay its destination token.   In each case, another player was able to do it via Master Mode and we could continue.

Suspiciously, both companies were owned by the same player (tool). 

Here, the LYR:
https://18xx.games/game/32368?action=978

Here, the SWR:
https://18xx.games/game/32368?action=1126

**Comment by magnusfalt** [comment] 2021-03-31 16:38
I wasnt able to reproduce the bug in hotseat mode. Since another player was able to do it with master mode i dont think there was anything wrong with the game. If it was so, then it shouldnt work with master mode either.

**Comment by magnusfalt** [comment] 2021-04-06 05:39
Im closing this since i havent been able to reporoiduce this bug and no other have reported this bug.

**Closed by magnusfalt** 2021-04-06 05:39 UTC
Labels: 1822
