### ISSUE TITLE
[1882] - Set: uninitialized constant Engine::SharePool::Set

### ISSUE THREAD

**Issue by stateless** [tobymao/18xx#10490] opened 2024-03-17 07:30 UTC
We're sorry this game cannot be continued due to Set: uninitialized constant Engine::SharePool::Set
Broken action: { "type": "pass", "entity": 15185, "entity_type": "player", "id": 14, "created_at": 1709598928 }
Please [raise a bug report](https://github.com/tobymao/18xx/issues?q=is%3Aissue+is%3Aopen+label%3A1882,%22needs%20triage%22) and include this link (https://18xx.games/game/155211?action=13)

**Comment by ollybh** [comment] 2024-03-17 10:50
Duplicate of #10484.

**Closed by ollybh** 2024-03-17 10:50 UTC
Labels: needs triage
