### ISSUE TITLE
[1822CA] destination token slots not handled correctly

### ISSUE THREAD

**Issue by toolgames** [tobymao/18xx#10147] opened 2024-01-16 14:13 UTC
At this move I placed a tile on Montreal with two token slots in the south:
https://18xx.games/game/148162?action=503

At this move GT placed its destination token and the south expanded to three slots:
https://18xx.games/game/148162?action=505

This is not how the destination tokens work in this game; they are placed in an open, non-reserved spot if one is available. Only if one is NOT available are they placed in what is effectively an extra slot (and in that case if the tile is upgraded to provide an extra slot they move into that slot).

See section 5.8.5:

Destination station slots are not reserved; other companies may place station tokens in them. If this happens the destination station location is still available to the owning company. If there is no unoccupied station slot in the station, the token is simply placed on the destination tile adjacent to the station. Until the tile is upgraded, or if further upgrades do not create additional token slots, then the destination e$ectively creates an additional token slot in the destination station. If the tile is upgraded to create an extra unoccupied station the destination token is at once moved into the slot created, irrespective of which company upgraded the tile,

**Comment by michaeljb** [comment] 2024-01-17 04:38
Thanks for the rules reference, got mixed up on this at one point and couldn't find the rule even though I remembered thinking it was there before.

**Comment by michaeljb** [comment] 2024-01-21 06:16
Working on specifically enumerating and reproducing all the cases I can, I'll edit this comment here as I have updates instead of making a new issue since that would really be a dupe of this issue.

* [gist](https://gist.github.com/michaeljb/0daac896d987e01e423c3bf5a633cb66) - Montreal southern station has an extra slot because CPR tokened there and GT destinated there; upgrading to M3 (where the separate stations join into one) correctly returns CPR's extra token, but the exra slot from the destination remains, so the slots are: CPR home, 7 home, GT dest, extra empty

**Closed** 2024-01-27 17:23 UTC
Labels: bug, 1822CA
