### ISSUE TITLE
[1822PNW] Companies don't float up at the end of a SR for being full held

### ISSUE THREAD

**Issue by setrajonas** [tobymao/18xx#8350] opened 2022-09-17 15:18 UTC
https://18xx.games/game/97938?action=274

SPS should have gone up in value at the end of the SR.

**Comment by benjaminxscott** [comment] 2022-09-18 05:19
fixed in https://github.com/tobymao/18xx/pull/8316 , not deployed yet 

dupe of https://github.com/tobymao/18xx/issues/8323

**Closed by benjaminxscott** 2022-09-18 05:19 UTC
Labels: needs triage
