### ISSUE TITLE
[1889] Mitsubishi Ferry does not work

### ISSUE THREAD

**Issue by padman12** [tobymao/18xx#1406] opened 2020-08-10 09:52 UTC
I started a Hotseat Game of 1889 and I'm not able to use the Mitsubishi Ferry Ability. I did it as displayed in the Tutorial: 
When its my turn with a Company I click on "Mitsubishi Ferry" next to "Abilities". The text pops up and the Ports are highlighted on the map. But when I click on any port, I can't choose the #437 Tile to be placed.  

I tried on my android smartphone in the chrome browser and on my PC, win10, Firefox Browser.

Thanks for any help

Regards

Padman

**Comment by jenf** [comment] 2020-08-10 10:07
confirmed, checking regression point.

**Comment by jenf** [comment] 2020-08-10 10:20
caused by the tile selector upgrade. fixed in 88b103c. refresh and you should be able to do it.

**Closed by jenf** 2020-08-10 10:20 UTC
Labels: 1889, bug
