### ISSUE TITLE
1866. Blocked run route.  Game 127606

### ISSUE THREAD

**Issue by Lime-Turtle** [tobymao/18xx#9360] opened 2023-08-08 16:41 UTC
(https://18xx.games/game/127606?action=193)

It won't even let me end the game. :-(

**Comment by Herbert62** [comment] 2023-08-10 05:00
see #9328

**Comment by philcampeau** [comment] 2023-08-17 04:44
Duplicate of #9328

**Comment by philcampeau** [comment] 2023-08-17 04:49
Duplicate of 9328

**Closed by philcampeau** 2023-08-17 04:49 UTC
Labels: needs triage
