### ISSUE TITLE
[1822+] Bids and bid tokens lost in stock round

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#10578] opened 2024-03-29 19:27 UTC
https://18xx.games/game/154562

In this game, I made my bids on all three privates, as can be seen in the game log.
After having finished the bids, nothing of this can be seen in the game status. 
Moreover, all bid tokens of all players disappeared.

**Comment by beorn7** [comment] 2024-03-30 10:54
It seems to be related to the Loan of player Toker.
I rescued the game by the following procedure:
- Undo KKiermeier's bids, pass instead.
- Pay back loan of Toker.
- Everyone pass until it is KKiermeier's turn again.
- Redo KKiermeier's bids.
- Now everything looks fine.

To reproduce the bug, I have cloned the game at the situation where all the bids and bid tokens disappear:
https://18xx.games/hotseat/hs_jjcxjnam_154562

**Comment by philcampeau** [comment] 2024-04-03 19:46
Possibly related to #10543 ?

**Comment by crericha** [comment] 2024-04-09 07:34
I believe the bug is that if the active player has no `bid` action, then the existing bids aren't shown. We need a better way, than the `bid` action being present, to inform the view code that bidding is active.

**Comment by crericha** [comment] 2024-04-09 07:35
Its a display only bug. There aren't any gameplay issues that I'm aware of.

**Comment by michaeljb** [comment] 2024-06-12 04:02
Closing as a dup of #10543

**Closed by michaeljb** 2024-06-12 04:02 UTC
Labels: game UI, 1822
