### ISSUE TITLE
1822MX auto routing not calculating rotes with multiple trains with LP

### ISSUE THREAD

**Issue by akoewler** [tobymao/18xx#9390] opened 2023-08-13 02:48 UTC
**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by philcampeau** [comment] 2023-08-17 04:41
Can you provide a link to the game, preferably on an action where this occurred?

**Comment by michaeljb** [comment] 2023-08-31 23:57
Probably related to #7902

**Comment by michaeljb** [comment] 2024-06-08 23:59
Closing as duplicate of #7902

**Closed by michaeljb** 2024-06-08 23:59 UTC
Labels: routes, autorouting, 1822MX
