### ISSUE TITLE
[18 Hiawatha] undefined method 'ability' for <Engine::Game::G18Hiawatha::Step::BuySellParShares>

### ISSUE THREAD

**Issue by scninmer08** [tobymao/18xx#10663] opened 2024-04-23 01:52 UTC
https://18xx.games/game/161117

When trying to form DL&W, I cannot use Union Station.  I receive the following error:

undefined method 'ability' for <Engine::Game::G18Hiawatha::Step::BuySellParShares>

I explored this in hotseat mode.  Trying to buy Union Station in first does not work either, nor if I win the bid at a different price, nor if I later open a second company and try to buy it in to that company.

**Comment by philcampeau** [comment] 2024-04-23 14:41
Duplicate of #10664, fix already submitted

**Closed by philcampeau** 2024-04-23 14:41 UTC
Labels: needs triage
