### ISSUE TITLE
Broken      https://18xx.games/game/75410?action=281

### ISSUE THREAD

**Issue by MotoGymkhana** [tobymao/18xx#7393] opened 2022-03-05 03:48 UTC
We're sorry this game cannot be continued due to GameError: Blocking step Buy Trains cannot process action 282
Broken action: { "type": "pass", "entity": "C&O", "entity_type": "corporation", "id": 282, "created_at": 1646371546 }
Please [raise a bug report](https://github.com/tobymao/18xx/issues/) and include this link (https://18xx.games/game/75410?action=281)

**Comment by michaeljb** [comment] 2022-03-05 03:55
This is caused by the same issue as #7361, closing this to keep the details focused in one place.

**Closed by michaeljb** 2022-03-05 03:55 UTC
Labels: needs triage
