### ISSUE TITLE
[1817] can't continue due to "Set: uninitialized constant"

### ISSUE THREAD

**Issue by Noehrgel** [tobymao/18xx#10504] opened 2024-03-17 10:26 UTC
Hey folks,

came back to this error message today:

We're sorry this game cannot be continued due to Set: uninitialized constant Engine::SharePool::Set
Broken action: { "type": "pass", "entity": 8832, "entity_type": "player", "id": 117, "created_at": 1709053938 }

It is a multiplayer game: https://18xx.games/game/147695?action=116

Thanks and keep up the great work,
Bernd

**Comment by ollybh** [comment] 2024-03-17 10:54
Duplicate of #10484.

**Closed by ollybh** 2024-03-17 10:54 UTC
Labels: needs triage
