### ISSUE TITLE
[18RoyalGorge] export train

### ISSUE THREAD

**Issue by familiar-hk** [tobymao/18xx#11369] opened 2024-11-20 09:10 UTC
![image](https://github.com/user-attachments/assets/6fbc8193-08f7-4bfb-8d10-38e73ec13976)
From the new rules, all 2+ should be exported after OR1

**Comment by ollybh** [comment] 2024-11-20 12:10
Duplicate of #11359.

**Closed** 2024-11-20 12:10 UTC
Labels: duplicate, 18RoyalGorge
