### ISSUE TITLE
18 India - the game don't let me place the NWR token in the inicial tile of New Delhi.

### ISSUE THREAD

**Issue by Zebsagaz** [tobymao/18xx#11108] opened 2024-08-08 07:21 UTC
**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by Zebsagaz** [comment] 2024-08-08 07:24
Game ID : Id: 173298
Initial Operation Round, playing with NWR, I can placed the Delhi tile, but it don't let me place my initial token.
Using Chrome Versión 127.0.6533.99 (Build oficial) (64 bits)

**Comment by ollybh** [comment] 2024-08-08 17:05
This is a duplicate of issue #11058. The fix for this bug has not yet been deployed but should be fairly soon.

**Closed** 2024-08-08 17:05 UTC
Labels: duplicate, 18India
