### ISSUE TITLE
The server did not accept this action due to: Auto actions did not match... refreshing

### ISSUE THREAD

**Issue by RedBrand88** [tobymao/18xx#8375] opened 2022-09-23 21:53 UTC
**How to Reproduce the Problem?**

What steps cause the unexpected behavior?
go to this game https://18xx.games/game/96852
Run the CMPS withhold its earnings
click Skip (Trains) button

<img width="1792" alt="Screen Shot 2022-09-23 at 3 44 32 PM" src="https://user-images.githubusercontent.com/22983990/192061032-ba3d92e5-b8b9-497a-97a2-0d4cdb7a7de8.png">

I get this error: The server did not accept this action due to: Auto actions did not match... refreshing.

but if I pay out and then skip trains the site lets me do that. I think this is a site issue but it could be an issue with 1822PNW as it is in alpha still.

**Which Browser / Platform?**
- Browser Version
  - On Safari, 16.0
- Mac Book Pro 2019 intel

**Comment by outsidePasser** [comment] 2022-09-24 01:27
Duplicate of #8374

**Closed by outsidePasser** 2022-09-24 01:27 UTC
Labels: needs triage
