### ISSUE TITLE
18ESP capitalization bug

### ISSUE THREAD

**Issue by queroscia** [tobymao/18xx#10624] opened 2024-04-11 06:39 UTC
Hello,

18ESP game has the capitalization linked to the achievement of three goals, BEFORE phase 5. When phase 5 enters, all major companies are launched with the 60% sold (not the 40% on phases 2-4) and they have the full capitalization (PAR x10). It is the rule. However, on game https://18xx.games/game/154646 the CFLG major company, that was launched AFTER phase 5, received the full capitalization, and ALSO the goals. So, it is receiving more money on its treasury that it should. Every time CFLG reaches a goal (and it shouldn't have goals) it receives PAR x1, PAR x2 or PAR x3. It is wrong, because the company was launched after phase 5 and it hasn't goals for this reason.

Thank you so much.

All the best,

Enrique Trigueros (queroscia): designer of 18ESP.

**Comment by benjaminxscott** [comment] 2024-04-16 03:27
dupe of #10633 (that ticket has more context

**Closed by benjaminxscott** 2024-04-16 03:27 UTC
Labels: bug, 18ESP
