### ISSUE TITLE
[18CZ] No valid city tiles were available when trying to use the river discount private ability on D17, however tiles were available with a regular tile lay action

### ISSUE THREAD

**Issue by khamsoul** [tobymao/18xx#3873] opened 2021-02-15 03:33 UTC
https://18xx.games/game/27945?action=95

**How to Reproduce the Bug?**
At this point in the game, BCB bought in a small private and tried to use the river discount on D17 (you can clone the game at this point to reproduce). However no valid city tiles were shown as available:
![river_lay_no_valid_city_tiles](https://user-images.githubusercontent.com/5924761/107902523-8b6daf00-6efb-11eb-9595-7be288a0004e.png)

When BCB tried to lay a city tile as a regular action, other city tiles were shown as available:
![regular_lay_valid_city_tiles](https://user-images.githubusercontent.com/5924761/107902528-8d377280-6efb-11eb-8c7a-533efd9f2410.png)

**Comment by Zwergenpunk** [comment] 2021-02-15 23:29
Duplicate of #3885 and should be fixed

**Comment by benjaminxscott** [comment] 2021-02-17 21:12
fixed by #3896

**Closed by benjaminxscott** 2021-02-17 21:12 UTC
Labels: 18CZ, bug
