### ISSUE TITLE
[1862] Route includes home token, engine thinks it doesn't

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#11091] opened 2024-07-31 17:59 UTC
https://18xx.games/game/168204?action=551

If you route the blue 6 train first, and then the red 5 train second, the engine doesn't think the home token is included.

<img width="875" alt="Screenshot 2024-07-31 at 08 21 20" src="https://github.com/user-attachments/assets/500b13ca-d34a-4b75-818c-cd687861bb01">

If you route the red 5 train first, and then the blue 6 train second, it works as expected.

**Comment by philcampeau** [comment] 2024-12-13 16:22
Not sure if this has been corrected without being linked, but I'm unable to reproduce the error either in hotseat mode or after importing the game to my local environment. Closing for now.

**Closed by philcampeau** 2024-12-13 16:22 UTC
Labels: 1862
