### ISSUE TITLE
Auto pass in stock round cancels incorrectly

### ISSUE THREAD

**Issue by curlett** [tobymao/18xx#6367] opened 2021-09-23 01:51 UTC
If someone sells a stock then you turn on auto pass I would expect it to pass when it gets back to your turn.

Instead it cancels sure to shares sold, even if the share was sold after you turned on auto pass.

![Screenshot_20210922-184535_Chrome](https://user-images.githubusercontent.com/11777262/134443853-4e4a9922-4493-41a5-a43a-5453b263b1e0.jpg)

**Comment by magnusrk-ch** [comment] 2021-12-02 12:45
This looks like a duplicate of #5215

**Closed** 2021-12-02 16:47 UTC
