### ISSUE TITLE
Track reuse not blocked

### ISSUE THREAD

**Issue by Bobsson** [tobymao/18xx#1556] opened 2020-08-31 18:38 UTC
In the 1846 game I'm in, I was just able to set up a pretty absurd route for B&O ([direct link](https://www.18xx.games/game/7549?action=676)).  As best as I understand the rules, this shouldn't be legal, because crossing over involves using the same hex-to-hex border, and thus the same piece of track.

![image](https://user-images.githubusercontent.com/2022339/91752415-58757000-eb94-11ea-9a27-855bdd9df268.png)

**Comment by dfannius** [comment] 2020-08-31 19:14
Yep. Duplicate of #1353

**Closed by dfannius** 2020-08-31 19:14 UTC
