### ISSUE TITLE
Display last run routes on the map

### ISSUE THREAD

**Issue by slyestfox** [tobymao/18xx#2084] opened 2020-10-28 14:17 UTC
As a newer player that also plays mostly correspondence games, I find it difficult to trace out routes of other players by using the coordinate list in the running log. It could be useful to have some means to simply see a given route displayed on the map. This would help greatly with being able to determine where are good places for tokens.

Options might include:
- Making the coordinate list in the running log clickable
- Adding the company icons in a small list on the Map tab with those being clickable
- Probably some other better UX ideas than my own? :)

**Comment by jenf** [comment] 2020-10-28 16:17
Duplicate of #563

**Closed by jenf** 2020-10-28 16:17 UTC
Labels: enhancement
