### ISSUE TITLE
[1822] [1822CA] Tax Haven value not included in 'total values' table on Spreadsheet tab 

### ISSUE THREAD

**Issue by waaayback** [tobymao/18xx#11030] opened 2024-07-14 01:45 UTC
Title says it all.  
- If a player owns the Tax Haven, its value is correctly reflected on the player's Entity card and on the main "Value" line on the Spreadsheet.
- HOWEVER, it is NOT properly reflected in the 'total values' table below the main Spreadsheet (it's prolly wrong for the delta values too, but I didn't check).  

This seems to be wrong in all 1822* flavors that have a Tax Haven. (I checked a completed 1822 game and it was wrong there too)

Here's an example with screenshots from an active 1822CA game:
https://18xx.games/game/167661?action=1024
waaayback (me) owns the Tax Haven.

NOTE that all the player's "Value" amounts (highlighted) match, except for waaayback's amount in the table (circled in red)
![image](https://github.com/user-attachments/assets/b54f7e1d-1027-48f9-a857-9c75c7a22c6e)

**Comment by michaeljb** [comment] 2024-07-14 18:02
The tax haven value is correctly included in the total values table (where $3335 is shown), and is actually being incorrectly double-counted where $3650 is shown, as described in #11007. Closing as dupe of #11007, and will be fixed in #11011. Thanks for reporting!

**Closed** 2024-07-14 20:07 UTC
Labels: needs triage
