### ISSUE TITLE
Freezing in Chrome on Android

### ISSUE THREAD

**Issue by BGarmon80** [tobymao/18xx#3854] opened 2021-02-14 18:14 UTC
Since the change overnight (I notice what looks to be key shortcuts in tabs now) I'm getting constant freezing and crashing. I'm using Chrome on a Samsung Note 10+.

**Comment by tobymao** [comment] 2021-02-14 20:42
Need some more detail on this.

**Comment by BGarmon80** [comment] 2021-02-14 20:47
When I open a game, I have freedom to scroll for about 1 second, then
screen locks and chrome gives me an error message. If I choose "wait," it
will eventually unfreeze for another second, then lock again.

Chrome on a laptop works fine.

What additional information do you need?

**Comment by tobymao** [comment] 2021-02-14 20:51
what game id?

**Comment by BGarmon80** [comment] 2021-02-14 20:56
27690, 27453, 27685, and 27259 were the only ones I tried. As I mentioned,
I can play fine on a laptop.

**Comment by Landshrk83** [comment] 2021-02-14 21:22
I'm experiencing the same issue on game 24224, also on Android/Chrome and also just started happening since the update overnight.

**Comment by mkkohls** [comment] 2021-02-15 15:21
Same issue in all my games in both chrome and edge on Android. Android 10 latest chrome update. Tried clearing cache and that did not help.

Game ids 25694 27327 probably others but I haven't had turns in those since this started happening.

**Comment by iGuitar93** [comment] 2021-02-15 15:50
I am having this issue too. Seems to be happening in all my games on mobile. It started when the hotkeys showed up for the game tabs.

**Comment by tobymao** [comment] 2021-02-15 16:07
So starting fresh, without the game page loaded at all, you go to 18xx.games, click on a game then it freezes?

**Comment by mkkohls** [comment] 2021-02-15 16:09
That is correct. It seems to be worse when the map is up but i've seen it during srs as well.

**Comment by iGuitar93** [comment] 2021-02-15 16:10
Yes. The main page is fine. Once I loaded a game it freezes.

**Comment by Landshrk83** [comment] 2021-02-15 16:11
> So starting fresh, without the game page loaded at all, you go to 18xx.games, click on a game then it freezes?

Yes, that's exactly what I've experienced.  The main page loads fine.  The game page will load, but immediately freeze the browser (it will pop up a Chrome isn't responding dialog).  Closing the app is the only way to rectify it, waiting will just cause it to pop up the notification again within 10-15 seconds.

**Comment by tobymao** [comment] 2021-02-15 16:12
Are any of you on Slack? Can you ping us in the 18xxgamesdev channel so we can test? None of the core devs can reproduce

**Comment by tobymao** [comment] 2021-02-15 16:53
i've disabled hotkeys temporarily while we try to fix this issue

so far we've figured out that you need to be logged in for this to happen

cc @yzemaze @jenf

**Comment by BGarmon80** [comment] 2021-02-15 18:23
I've only attempted one turn in a game since disabling the hot keys, but it
worked.

**Comment by BGarmon80** [comment] 2021-02-15 18:35
Spoke too soon. Game 27259 froze when I attempted to take a turn on my
phone.

**Comment by yzemaze** [comment] 2021-02-15 18:41
> Spoke too soon. Game 27259 froze when I attempted to take a turn on my phone.

reproducible? or just once?

**Comment by BGarmon80** [comment] 2021-02-15 19:10
Reproducible. Every time I restart Chrome it attempts to reload the game
and as I start to scroll down, not quite at the bottom of the second
charter (we're in a stock round) it freezes.

**Comment by tobymao** [comment] 2021-02-15 20:35
ok, this is important info... the game freezes on scroll

**Comment by iGuitar93** [comment] 2021-02-15 20:37
Yeah the scroll is what does it for me too

**Comment by yzemaze** [comment] 2021-02-15 21:15
Ok, a few tests you could run to help us:

1. Open a) https://gist.githubusercontent.com/yzemaze/ddfcd220c9c6d35554acacdef45573b6/raw/6e93644b66c9750713e4a0ce8a7d2c1a1deeff7b/gistfile1.txt and b) https://gist.github.com/yzemaze/ddfcd220c9c6d35554acacdef45573b6 with Chrome and tell us if they load fine or if a) or b) freezes your browser. Then do the same with Firefox and report results, too.

2. Check your games on 18xx.games. Open those who lead to freezes with Firefox and check if they still freeze. Report results llike this: id 27359, Chrome (no) freeze, Firefox (no) freeze

**Comment by iGuitar93** [comment] 2021-02-15 22:17
1. Link b freezes with chrome upon scrolling. Link a does not. In firefox neither link causes freezeing.
2.  Id: 26781 chrome slight freeze, firefox no freeze

**Comment by iGuitar93** [comment] 2021-02-15 22:21
Here is another game id 26929
Freezes in chrome, does not freeze in firefox

**Comment by TBarchet** [comment] 2021-02-16 16:04
On Android, freezes in Chrome, as well as Brave (Chrome-based).  Freeze sometimes lasts for a few seconds before moving on, sometimes going through a couple of "not responding" messages.  Also experiencing in game IDs:
23066
25723
25383

**Comment by TBarchet** [comment] 2021-02-16 22:29
I also question that it is directly related to scrolling (which I thought I experienced at first), as I experience a freeze after a short delay (in a similar feel to items still loading).  This may be perceived as due to scroll (which is often the first action performed when opening a game), but mine freezes whether I scroll or not.

**Comment by tobymao** [comment] 2021-02-16 22:43
it sounds like this is a chrome / android issue and not something we can easily fix

**Comment by dlpierce** [comment] 2021-02-17 15:26
My wife has been getting these freezes too, but I have not. She says it's been during SRs. We are in the same game (27223) and we have the same device (Pixel 3a) using Chrome.

**Comment by BGarmon80** [comment] 2021-02-17 15:30
In game 27690 I started getting intermittent freezing during ORs yesterday
as well.

**Comment by dlpierce** [comment] 2021-02-19 16:29
I seem to have fixed the freezing by disabling a system accessibility service, Twilight in my case. Does anyone else experiencing freezing have any accessibility services enabled in Android Settings > Accessibility?

**Comment by tobymao** [comment] 2021-02-19 18:36
Thanks to @dlpierce for the investigation, this seems related as well

https://bugs.chromium.org/p/chromium/issues/detail?id=1014945#c18

closing this since it's a chrome bug

**Closed by tobymao** 2021-02-19 18:36 UTC
Labels: bug
