### ISSUE TITLE
18CO Game 20132. DSNG. Player 1 had 2 shares and was Prez. Player 2 bought 2 shares, then 1 share. Game showed Player 2 as President with 2 shares, and Player 1 with 3 shares

### ISSUE THREAD

**Issue by Foxrik** [tobymao/18xx#2821] opened 2020-12-27 01:03 UTC

**Comment by ryandriskel** [comment] 2020-12-27 02:42
Duplicate of https://github.com/tobymao/18xx/issues/2780

Thanks for the report!

**Closed by ryandriskel** 2020-12-27 02:42 UTC
