### ISSUE TITLE
1822 autorouter wildly undercounting

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#9671] opened 2023-09-25 01:27 UTC
https://18xx.games/game/133942?action=1162

The E and 2P are manually routed:

<img width="352" alt="Screenshot 2023-09-24 at 17 44 12" src="https://github.com/tobymao/18xx/assets/8732435/1b03191c-bbae-46a9-a3b7-25ccd8fe916a">
<img width="410" alt="Screenshot 2023-09-24 at 17 44 29" src="https://github.com/tobymao/18xx/assets/8732435/4acbd23b-2312-40d8-9ce2-7af574726b9a">

I click Auto and get this:

<img width="334" alt="Screenshot 2023-09-24 at 17 44 43" src="https://github.com/tobymao/18xx/assets/8732435/38f89e2b-4ba5-4f94-b961-1b1115545425">
<img width="374" alt="Screenshot 2023-09-24 at 17 44 53" src="https://github.com/tobymao/18xx/assets/8732435/d2be107f-67fe-4109-a592-4cc8d4ecc1fd">

I think this is the actual best route:

<img width="335" alt="Screenshot 2023-09-24 at 17 46 15" src="https://github.com/tobymao/18xx/assets/8732435/01cee20a-cec9-455f-9e54-8033a1f897ec">
<img width="401" alt="Screenshot 2023-09-24 at 17 46 24" src="https://github.com/tobymao/18xx/assets/8732435/7b64b6c3-1b8d-460d-a1e4-4f66e45ce21a">

**Comment by BellmakerSA** [comment] 2023-09-26 00:04
E-trains are not being calculated as being able to run the same track as other trains yeah

**Comment by michaeljb** [comment] 2024-06-08 21:47
Closing this as duplicate of #7982

**Closed by michaeljb** 2024-06-08 21:47 UTC
Labels: 1822, autorouting
