### ISSUE TITLE
[Harzbahn 1873] Broken game

### ISSUE THREAD

**Issue by physic** [tobymao/18xx#10486] opened 2024-03-17 07:03 UTC
We're sorry this game cannot be continued due to Set: uninitialized constant Engine::SharePool::Set
Broken action: { "type": "par", "entity": 648, "entity_type": "player", "id": 99, "created_at": [1708888320](tel:1708888320), "corporation": "HBE", "share_price": "150,0,8" }
Please [raise a bug report](https://github.com/tobymao/18xx/issues?q=is%3Aissue+is%3Aopen+label%3A1873,%22needs%20triage%22) and include this link (https://18xx.games/game/152097?action=98)

**Comment by ollybh** [comment] 2024-03-17 10:49
Duplicate of #10484.

**Closed by ollybh** 2024-03-17 10:49 UTC
Labels: needs triage
