### ISSUE TITLE
[18EU] Final exchange round offers market share when treasury share available; selecting this causes an error

### ISSUE THREAD

**Issue by slapphappyjazz** [tobymao/18xx#9861] opened 2023-11-06 20:49 UTC
https://18xx.games/game/137099?action=443

The game is in the final exchange round.  If the current player selects the GSR, they are offered a choice of market or treasury shares.  As described in another bug report (https://github.com/tobymao/18xx/issues/8053), the market shares should not be offered.  If they do select the market shares option, this causes an error.

**Comment by andrewzwicky** [comment] 2024-01-07 18:32
Error for selecting market shares was fixed in #9976
Problem with being able to select Market when shouldn't be allowed to is duplicate of #8053, so will be fixed there

**Closed by andrewzwicky** 2024-01-07 18:32 UTC
Labels: rules-permissive, 18EU
