### ISSUE TITLE
[18Ireland] confusing situation with emergency financing

### ISSUE THREAD

**Issue by Azuureth** [tobymao/18xx#6064] opened 2021-07-21 11:47 UTC
![image](https://user-images.githubusercontent.com/64785010/126483446-6e44e99b-027a-4906-adcb-9e338028287e.png)

Player was about to go bankrupt, but there was an 10H in the bankpool that he could afford. He proceeded to sell all shares he could and was left with not enough money for a D, but too many shares sold for the 10H.

The game still allowed him to continue selling shares, even though he could not afford the D

https://18xx.games/game/47874?action=1154

I Master-acted around the issue by selling just enough shares so he could afford the 10H, and was then succesful in declaring bankruptcy on his next company.

**Comment by dfannius** [comment] 2022-02-05 16:54
Duplicate of #6655.

**Closed by dfannius** 2022-02-05 16:54 UTC
