### ISSUE TITLE
[1848] Can't connect Sydney-Adelaide (errors)

### ISSUE THREAD

**Issue by HerbyMcGee** [tobymao/18xx#9879] opened 2023-11-09 00:20 UTC
**What's your Game ID?**
https://18xx.games/game/139312?action=414

**How to Reproduce the Bug?**
I tried placing Tile # 5 on F13 to make connection with Syndey-Adelaide but then couldn't take further actions. 

**Which Browser / Platform?**
Both on iPhone Safari and desktop Windows 11 Edge, so not sure if relevant

**Comment by andrewzwicky** [comment] 2023-11-09 00:34
dupe of https://github.com/tobymao/18xx/issues/9847

Should be fixed with #9876

**Closed** 2023-11-09 20:35 UTC
Labels: needs triage
