### ISSUE TITLE
[1822MX] FCM can access Acapulco (P23) and lay track there without a connection

### ISSUE THREAD

**Issue by kepakiano** [tobymao/18xx#11149] opened 2024-08-16 09:04 UTC
In https://18xx.games/game/171948?action=507 FCM is able to upgrade O22 and P23 and then lay a token even though it has no route to these tiles. Interestingly, the rules for M24 are enforced correctly.

![image](https://github.com/user-attachments/assets/074798c6-0113-40a0-8fc2-2433f600d01b)

**Comment by philcampeau** [comment] 2024-08-21 03:49
duplicate of #11148

**Closed** 2024-08-21 03:49 UTC
Labels: rules-broken, 1822MX
