### ISSUE TITLE
[1846 2p Variant] "no implicit conversion of NilClass into Integer" error when upgrading tile

### ISSUE THREAD

**Issue by EmberNov** [tobymao/18xx#8590] opened 2022-12-15 21:00 UTC
https://18xx.games/game/106921
![1846](https://user-images.githubusercontent.com/120684230/207965543-16bb923a-aa9d-4e2d-9dcf-264218cc975b.jpg)
When IC tries to lay a green X tile on Erie (D20) in OR 4.2 I get this Error message. Maybe it has something to do with the Erie token that goes in that hex in the 2p Variant? I am playing in the Chrome browser.

**Comment by magnusrk-ch** [comment] 2022-12-18 11:12
The failure happens in exchange_token in city.rb. It's trying to insert the ERIE token, but both slots are token (IC and NYC).

Tom answered a question related to this on BGG (https://boardgamegeek.com/thread/1616729/article/35960505#35960505) but it doesn't cover what happens if both the slots are taken before green.

**Comment by michaeljb** [comment] 2022-12-18 19:24
Duplicate of #7612

**Closed by michaeljb** 2022-12-18 19:24 UTC
Labels: bug, rules-broken, 1846
