### ISSUE TITLE
[1847AE] Tile upgrades not functioning correctly, and missing for green cities

### ISSUE THREAD

**Issue by HerbyMcGee** [tobymao/18xx#9852] opened 2023-11-03 14:27 UTC
**What's your Game ID?**
https://18xx.games/game/138153?action=837#tiles

**How to Reproduce the Bug?**
![image](https://github.com/tobymao/18xx/assets/77583169/642ccf7a-89c2-49f3-9c35-34074b10a09b)

1. Tile upgrade options hide behind the manifest in upper row of manifest
2. Tile upgrades are not shown for Green City tiles
 
![image](https://github.com/tobymao/18xx/assets/77583169/ef823945-0399-4a0e-8fce-65f972f07ccd)

**Which Browser / Platform?**
Edge - Version 118.0.2088.76 (Official build) (64-bit)
Windows 11

**Comment by Galatolol** [comment] 2023-11-03 19:59
From what I see this is how it works on the site. The issue is not 1847AE-related.
e.g. 1830:
![image](https://github.com/tobymao/18xx/assets/10097748/ac377582-5bb0-4586-9285-bba8f2a2d030)

#205 through #208 indeed should show their upgrades. I'll ask around to see if someone knows what may be the reason.

**Comment by slapphappyjazz** [comment] 2023-11-08 20:27
This seems related to [https://github.com/tobymao/18xx/issues/9280](url) - "Layers out of order in Tiles tab when viewing upgrades"

**Comment by benjaminxscott** [comment] 2023-11-09 20:42
It seems like issue (1) may he addressed by 
https://github.com/tobymao/18xx/pull/9864

Issue (2) seems specific to this title, we may have to explicitly create upgrade paths for those tiles since they appear to be custom handled in code

**Comment by Galatolol** [comment] 2023-11-16 14:29
It looks now like both issues are resolved.

https://18xx.games/game/138153?action=837#tiles

**Closed** 2024-01-04 10:43 UTC
Labels: needs triage
