### ISSUE TITLE
[1846]: Requirement that Michigan Central tile lays must connect with each other if two tiles are laid is not enforced

### ISSUE THREAD

**Issue by JEBrosius** [tobymao/18xx#1308] opened 2020-08-02 13:01 UTC
https://www.18xx.games/game/4980?action=313

When the Michigan Central's power is used, either one or two plain yellow tiles may be laid, in B10 and B12.  If two tiles are laid, they must connect with each other across the B10/B12 hexside.  The program is not enforcing this requirement (see the game linked above.)

This problem may also affect the O&I's tile lays, which are similar, but I haven't checked.

**Comment by michaeljb** [comment] 2020-08-03 01:23
Duplicate of #1173

**Closed by michaeljb** 2020-08-03 01:23 UTC
Labels: 1846
