### ISSUE TITLE
[18EU] Unable to merge connected minor into newly forming major

### ISSUE THREAD

**Issue by nienart** [tobymao/18xx#7116] opened 2022-02-12 23:14 UTC
**Description**

In a hotseat game, minors 3 and 15 are owned by the same player, and Paris and Lyon are connected.
- They open a major with all their available cash and the 3.
- Next turn they expect to merge in the 15
- Instead game says "Brittany has no valid actions and passes"

This is the relevant map portion:

![Screen Shot 2022-02-12 at 3 02 39 PM](https://user-images.githubusercontent.com/20801394/153731687-81ba1070-76e3-4074-96e2-83c286b72989.png)

**How to reproduce**

Load game state from [this gist](https://gist.github.com/nienart/c399837dd2545f041ca36ea701598007). Player Aubrey should pass to demonstrate the bug.

**Which Browser / Platform?**
- Browser Version Firefox 95.0.2 (64-bit)
- Platform Desktop

**Comment by ryandriskel** [comment] 2022-02-13 00:01
Duplicate of https://github.com/tobymao/18xx/issues/7069

**Closed by ryandriskel** 2022-02-13 00:01 UTC
Labels: needs triage
