### ISSUE TITLE
[18SJ] Unable to purchase IPO shares from corporations (when it is full cap).

### ISSUE THREAD

**Issue by gardir** [tobymao/18xx#8128] opened 2022-07-30 10:01 UTC
**What's your Game ID?**
https://18xx.games/game/91159

**How to Reproduce the Bug?**
- After reaching Full Cap, clicking on any corporations (ÖSJ or BJ in affected game) during SR will not reveal the "buy" button to buy IPO shares.
- In a clone of the game to hotseat, market shares were possible to purchase. Have not investigated treasury shares.
- Seemed to happen sometime after 18:28Z yesterday (29th. July) when my auto managed to purchase a IPO share.

**Which Browser / Platform?**
- Browser Version
  - On Android and Chrome, 103.0.5060.129
  - On PC and Firefox, version 103.0

**Comment by perwestling** [comment] 2022-07-31 08:51
@gardir: I think I know where the bug is (it is an error after moving IPO shares to the bank when changing to full cap) but I do not know if I will be able to fix that today as I am going to play board games all day. So it might take a couple of days to fix.

**Comment by gardir** [comment] 2022-07-31 09:07
@perwestling thanks for checking, and great you think you know the trouble. I understand completely your priorities, I'll be stalling the game until you have time to fix :)
Have fun and good luck today!

**Comment by perwestling** [comment] 2022-08-02 11:13
I think I found the cause and have now pushed a fix. But it might take a week or so before it is deployed.

**Comment by ddaybell** [comment] 2022-08-04 00:21
I think the same or similar bug has hit my game.  We just transitioned to full-cap, and now nobody is able to buy the president's share of any of the new companies.  So it's not quite an error moving IPO shares to the bank, but it is a problem with buying shares when the game switches to full-cap.  Game is https://18xx.games/game/91791.

**Comment by perwestling** [comment] 2022-08-04 15:56
@ddaybell, thanks for sharing. Have now fixed the bug fix so that it works with parring as well.
So we need to wait for it to be deployed.

**Comment by leamgn** [comment] 2022-08-06 05:14
The same bug has hit my game too. Game is http://18xx.games/game/92427. Do we just have to wait till this problem is fixed?

**Comment by perwestling** [comment] 2022-08-06 07:41
@leamgn I tried the fix on your game and it do work now. So when the fix is deployed it should fix your game, ie yes, please wait.

**Closed** 2022-08-07 05:29 UTC
Labels: bug, 18SJ
