### ISSUE TITLE
[1848] bug of train limit

### ISSUE THREAD

**Issue by plfires** [tobymao/18xx#8349] opened 2022-09-16 08:24 UTC
Here is a bug for train number limit.
The rule of 1848 i have checked english version that in this part is same as 1830 and 1889

if you have 3train and 4 train. now no 5-train sold. you can buy one 5-train then discard one, this is correct.
However, if you have 3train and 4 train, now is second 5-train on sell or 6-train on sell. player cannot bought train.
THe bug is in 1848, now  i can buy one  and discard one train.

**Comment by benjaminxscott** [comment] 2022-09-17 01:23
may be related to https://github.com/tobymao/18xx/issues/8303 which is fixed but might not be deployed yet

**Comment by plfires** [comment] 2022-09-17 17:25
> may be related to #8303 which is fixed but might not be deployed yet

yes, it is same case.  so thanks

actually i have not link. i played game with others but that time i think rule is special. yesterday i  discussing with my friend who has same problem in his hotseat game, and we check the rule.  however he said he delete that game.

**Comment by benjaminxscott** [comment] 2022-09-18 05:14
s.b. fixed, not deployed yet

dupe of #8303

**Closed by benjaminxscott** 2022-09-18 05:14 UTC
Labels: 1848
