### ISSUE TITLE
18USA Just crashed on me near the end - https://18xx.games/game/146912?action=92

### ISSUE THREAD

**Issue by David-Tinman** [tobymao/18xx#10073] opened 2023-12-31 22:11 UTC
**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by michaeljb** [comment] 2023-12-31 22:59
This was caused by #10070, fixed by the seed migration.

**Closed by michaeljb** 2023-12-31 22:59 UTC
Labels: needs triage
