### ISSUE TITLE
[18Chesapeak) Broken game

### ISSUE THREAD

**Issue by Git-Yoda** [tobymao/18xx#10489] opened 2024-03-17 07:27 UTC
https://18xx.games/game/155543

We're sorry this game cannot be continued due to Set: uninitialized constant Engine::SharePool::Set
Broken action: { "type": "bid", "entity": 16957, "entity_type": "player", "id": 5, "created_at": 1709738709, "company": "B&OR", "price": 100 }
Please [raise a bug report](https://github.com/tobymao/18xx/issues?q=is%3Aissue+is%3Aopen+label%3A18Chesapeake,%22needs%20triage%22) and include this link (https://18xx.games/game/155543?action=4)

**Comment by kodemaniak** [comment] 2024-03-17 08:03
Same problem in this game: https://18xx.games/game/156641?action=12)

**Comment by ollybh** [comment] 2024-03-17 10:50
Duplicate of #10484.

**Closed** 2024-03-17 10:54 UTC
Labels: needs triage
