### ISSUE TITLE
[18Chesapeake] https://18xx.games/game/156004?action=8

### ISSUE THREAD

**Issue by jbmoles** [tobymao/18xx#10513] opened 2024-03-17 12:24 UTC
We're sorry this game cannot be continued due to Set: uninitialized constant Engine::SharePool::Set
Broken action: { "type": "pass", "entity": 14449, "entity_type": "player", "id": 9, "created_at": 1710111418 }
**What's your Game ID?**

https://18xx.games/game/156004?action=8

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by ollybh** [comment] 2024-03-17 12:59
Duplicate of #10484.

**Closed by ollybh** 2024-03-17 12:59 UTC
Labels: needs triage
