### ISSUE TITLE
[18NY]

### ISSUE THREAD

**Issue by th3tick** [tobymao/18xx#7287] opened 2022-02-23 09:42 UTC
We got the following error:

We're sorry this game cannot be continued due to GameError: 1 has 95 and cannot spend 100
Broken action: { "type": "buy_train", "entity": "1", "entity_type": "corporation", "id": 146, "created_at": 1645503433, "train": "2H-10", "price": 100, "variant": "2H" }
Please [raise a bug report](https://github.com/tobymao/18xx/issues/) and include this link (https://18xx.games/game/69341?action=145)

**Comment by blackwaterJoseph** [comment] 2022-02-23 12:55
We just got the same error as well while playing 18NY.

We're sorry this game cannot be continued due to GameError: D&H has 151 and cannot spend 200
Broken action: { "type": "buy_train", "entity": "D&H", "entity_type": "corporation", "id": 293, "created_at": 1645452849, "train": "4H-3", "price": 200, "variant": "4H" }
Please [raise a bug report](https://github.com/tobymao/18xx/issues/) and include this link (https://18xx.games/game/73743?action=292)

**Comment by scottredracecar** [comment] 2022-02-23 14:08
There was a bug that is now fixed that was giving too much money for 2H runs so allowed illegal train buys. Possibly you can undo to that step?--otherwise, you will need to restart.

**Comment by blackwaterJoseph** [comment] 2022-02-23 14:12
It says the game is broken and can't accept any new actions.

**Comment by th3tick** [comment] 2022-02-23 14:39
those "new actions" include the undo button

Note that this happened during the train buying step, so while allowing illegal train buys might be related, this after a legal train purchase, and ready to make another, but the company doesn't have enough money.

**Comment by scottredracecar** [comment] 2022-02-23 21:51
Does it work to click to an earlier step in the log to get this kind of undo?
<img width="635" alt="image" src="https://user-images.githubusercontent.com/29106780/155414804-4f9c257f-5b18-4519-91cf-471b11d789e5.png">

**Comment by th3tick** [comment] 2022-02-24 00:07
nope; same error
it's dead, Jim

**Closed** 2022-02-24 00:15 UTC
Labels: 18NY

**Comment by th3tick** [comment] 2022-02-24 00:29
Is there nothing more to be done to fix the actual problem?  It doesn't sound like the bug you referenced where it was "giving too much money for 2H runs so allowed illegal train buys".  There's no sign of too much money anywhere, and no one even attempting illegal train buys.

**Comment by scottredracecar** [comment] 2022-02-24 00:33
The problem is already fixed. There was a bug that was causing the 2Hs to
make too much money and that allowed an illegal buy which is what the error
reports.

The way the system works now, this is not repairable AFAIK. Others will see
this discussion and can chime in if I am wrong.

**Comment by th3tick** [comment] 2022-02-24 02:42
OK.  I guess it must have been keeping two sets of books.  I just wanted to make sure before we bothered starting the game again or anything.
