### ISSUE TITLE
1822MX - Unable to load game

### ISSUE THREAD

**Issue by Conor1846** [tobymao/18xx#8462] opened 2022-10-22 00:16 UTC
Game ID: https://18xx.games/game/100614

Issue: Unclear - player completed a turn and since no player has been able to enter the game.

Screenshot: ![image](https://user-images.githubusercontent.com/116409826/197306976-bad6319f-ec7b-4f87-8168-2ea913d07b14.png)

Browsers: Unable to access in Firefox or Safari

**Comment by andypymont** [comment] 2022-10-26 17:33
I tried to investigate this but haven't been able to get to the bottom of it.

The error is occurring during the calculation of the graph for the NDeM. During the previous run of the NDeM in OR4.2 (action 385), the error does not occur. However, in this latest action, when walking the path from the token in D15, the tile in the hex to the southeast has no reference to the hex it is located in, when it should reference hex E16. This then causes an error when calculating `edge.id` during `walk` in `lib/engine/part/path.rb` because the edge ID tries to include the (non-existent) hex ID.

**Comment by outsidePasser** [comment] 2022-11-03 04:29
The problem is that, for some reason, in the database tile id "8-6" was placed a second time without being replaced from the first time.  When it was removed from the first location, the hex was blanked out, and the second location didn't have a hex.  

This should really not occur unless clients fire multiple requests.  I'm working on a fix that will block this problem from happening even if they do - that is in progress.  

In the mean time, this specific game (100614) has been fixed in the database and the players can proceed.

**Comment by Conor1846** [comment] 2022-11-03 14:01
Thanks all for getting us up and running again!

**Closed** 2023-01-24 06:39 UTC
Labels: bug, 1822MX
