### ISSUE TITLE
[1889], game reverted to opening stock round, token error

### ISSUE THREAD

**Issue by E3GH75** [tobymao/18xx#10514] opened 2024-03-17 12:26 UTC
https://18xx.games/game/153225?action=28

player bought and sold share, undid and bought a different share in stock round 7. Game blew up when next player attempted to make a move. Was on iPhone - safari

**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by ollybh** [comment] 2024-03-17 13:00
Duplicate of #10484.

**Closed by ollybh** 2024-03-17 13:00 UTC
Labels: needs triage
