### ISSUE TITLE
[1822pnw] `server did not accept this action due to: Auto actions do not match .. refreshing

### ISSUE THREAD

**Issue by Watermark33** [tobymao/18xx#8374] opened 2022-09-23 16:19 UTC
*What's your Game ID?* 97564

https://18xx.games/game/97564

https://18xx.games/game/97564?action=1530

**How to Reproduce the Bug?**

Issue shows up after trying to submit payout for SWW train. But not clear how this is related to the error. 

**Which Browser / Platform?**
- Browser Version
  - On Chrome, see [chrome://version](chrome://version)
  Version; 104.0.5112.99 on iPad

**Comment by RedBrand88** [comment] 2022-09-23 23:14
I have the same issue and didn't see this ticket here is the other time this bug was found. Steps to reproduce in this ticket https://github.com/tobymao/18xx/issues/8375

**Comment by outsidePasser** [comment] 2022-09-24 04:10
This problem is due to a bug that is in the pending PR.  I will close it when that PR has been promoted.

**Closed** 2022-09-24 16:49 UTC
Labels: needs triage
