### ISSUE TITLE
1866 bug - unable to continue game

### ISSUE THREAD

**Issue by woodfeld** [tobymao/18xx#10518] opened 2024-03-17 14:21 UTC
Here’s the link - https://18xx.games/game/154002?action=18 

**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by ollybh** [comment] 2024-03-17 14:37
Duplicate of #10484.

**Closed by ollybh** 2024-03-17 14:37 UTC
Labels: needs triage
