### ISSUE TITLE
18EU final minor exchange token bug

### ISSUE THREAD

**Issue by pzieske** [tobymao/18xx#8455] opened 2022-10-17 16:40 UTC
In the final exchange round, I exchanged #3 for a share of the DR from the pool.  The cash and train were returned to the bank, but the DR got the choice of taking the token.  Per the rules, when a share is taken from the pool, the token is removed.
https://18xx.games/game/99792 

[09:20] zieskep exchanges 3 for a 10% share of DR
[09:20] The Bank takes £56 from 3 remaining cash
[09:20] The Depot takes 3 train from 3
[09:20] The Depot is forced to discard pullman train
[10:13] DR replaces 3 token on A10
[10:13] 3 closes

**Comment by andrewzwicky** [comment] 2024-01-07 18:13
duplicate of #8053

**Closed by andrewzwicky** 2024-01-07 18:13 UTC
Labels: bug, 18EU
