### ISSUE TITLE
[1822] Mis-calculating player value

### ISSUE THREAD

**Issue by fanman80** [tobymao/18xx#11220] opened 2024-09-15 01:09 UTC
Game #170226

https://18xx.games/game/170226

During OR10.2 after NBR operation, game displays player value for Pawnpusher as £15,125.
Pawnpusher owns 7 shares of LBSCR at £600 each for £4,200
6 shares of LYR at £360 each for £2,160
3 shares of GWR at £600 each for £1,800
2 shares of MR at £550 each for £1,100
and £7,093 in cash
Total: £16,353

**Comment by fanman80** [comment] 2024-09-15 12:46
After submitting this.  I went back to the game, clicked on the Entities tab and the game correctly displayed Pawnpusher's value as £16,353.  Then I clicked on the Spreadsheet tab which showed the incorrect value of £15,125.  When I went back to the Entities tab the value was shown incorrectly as £15,125.

**Comment by fanman80** [comment] 2024-09-16 02:30
The "game over" summary shows the correct value for Pawnpusher.

**Comment by ChrisTheCat** [comment] 2024-10-10 23:17
This is a problem with the Tax Haven, reported in issue 11040

**Comment by michaeljb** [comment] 2024-12-01 17:45
Closing as duplicate of #11040

**Closed by michaeljb** 2024-12-01 17:45 UTC
Labels: entity display, 1822
