### ISSUE TITLE
Layers out of order in Tiles tab when viewing upgrades

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#9279] opened 2023-06-24 19:39 UTC
**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by philcampeau** [comment] 2023-06-26 19:14
Duplicate of #9280

**Closed by philcampeau** 2023-06-26 19:14 UTC
Labels: needs triage

**Comment by ChrisTheCat** [comment] 2023-06-26 19:37
Weird, not sure how this got posted separately from the actual issue.
