### ISSUE TITLE
18USA missing mining pickaxe icons

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#9228] opened 2023-06-02 06:32 UTC
https://18xx.games/game/121704?action=1371#map

Hexes E9, E19, G21, and H6 are missing the mining pickaxe icons. I checked in a different browser and they appear. I cleared my cache, but that didn't help. I'm running Firefox 102.11.0esr (64bit) on MacOS 13.3.1 (a).

<img width="1139" alt="Screenshot 2023-06-01 at 23 29 26" src="https://github.com/tobymao/18xx/assets/8732435/161c5507-eaec-49dc-b1ea-fd794077059c">

**Comment by crericha** [comment] 2024-05-28 06:08
If I recall, the issue is there is a certain font package that needs to be installed. Do we know which font package? I can add to the wiki.

**Comment by ChrisTheCat** [comment] 2024-05-28 17:05
I don't know which font package. However, a solution that requires end users to install a font package probably isn't the best choice.

**Comment by crericha** [comment] 2024-05-29 04:19
In order to fix in code, it would be a high effort task and that isn't worth it to me since only a very small amount of people (maybe just you) have been affected. I'm going to close the issue as not planned since there is no resolution that will be worked on.

**Closed by crericha** 2024-05-29 04:19 UTC
Labels: 18USA, map

**Comment by scottredracecar** [comment] 2024-05-29 14:56
I think the pickaxe as implemented is an emoji. Maybe those do not display
in Firefox?

Chris S, can you see a pickaxe in C4 here? I am pretty sure
we implemented this one as an emoji so may have the same problem (or not).
https://18xx.games/game/158657?title=1877%3A+Venezuela

**Comment by ChrisTheCat** [comment] 2024-05-29 15:31
I think you're right, and I cannot see the pickaxe in C4 of the linked game.
