### ISSUE TITLE
1846 skips track/token lay when a company has little cash but may issue shares

### ISSUE THREAD

**Issue by jacobb11** [tobymao/18xx#1718] opened 2020-09-24 01:13 UTC
In game 10552 you can see this happening to the PRR around OR 2.1.

The game notes that the PRR hasn't enough money to lay a token or track.
It skips right to route selection.
There are still share issuing buttons.
But after issuing a share it's not possible to back up to lay track/token.

**Comment by dfannius** [comment] 2020-09-24 01:22
I think this is a duplicate of #1709.

**Comment by jacobb11** [comment] 2020-09-24 01:45
> I think this is a duplicate of #1709.

You're probably right.

On a slightly related note, share issue/redeem in 1846 would be awesome if it was allowed at any time during the operating turn, patching the divident payments appropriately.  It's so common in face-to-face play to say "I'll figure out the issue/redeem step later after I've planned out the rest of the turn.".  I would go so far as to allow any play that issuing shares would support then at the end let the user pick among the issue/redemption combinations that would allow the rest of her play.  I can outline how that would work in practice if it would help, and a guess as to how that would be implemented.

Also, 18xx.games is an awesome service!  Thanks for providing it.

Regards,
  Jacob

**Comment by dfannius** [comment] 2020-09-24 01:55
In fact I believe that this bug is a result of some new code that does exactly what you request (#1695, addressing #1433). So once this latest issue is ironed out everything should be wonderful.

**Comment by jacobb11** [comment] 2020-09-24 07:24
> In fact I believe that this bug is a result of some new code that does exactly what you request (#1695, addressing #1433). So once this latest issue is ironed out everything should be wonderful.

Possibly?  I'd guess the current UI allows (modulo the bug) deferring the stock decision until after/during the track/token decision.  But I would like to defer the stock decision until after paying out revenue, which would require distinctly more coding because it would change the payout of the shares issued or redeemed.  Possibly that's already done or planned, but for example currently the log message for the payout is printed during the payout, but that message would become wrong if a share were retroactively issued/redeemed after the payout.  Maybe hook into the undo/redo system, which seems like it would be more complicated.

I don't know if you're a developer for this project (or even *the* developer for this project).  I wrote a route optimizer for several 18xx variants including 1846 earlier this year.  It's a bit complex and perhaps inconveniently in Rust (which I was learning), but I think it's fast enough to automate 1846 route selection, and probably other 18xx games.  Maybe it's worth using or translating?

This is probably all going into github.  Hello randome future github browsers!

~j

**Comment by dfannius** [comment] 2020-09-24 11:06
I haven't actually seen the new feature in action, so I'm not sure what it does do - I assume you are right. 

I'm a semi-active contributor, Toby's the main developer. You should definitely join the Slack if you can (link's on the front page of the site) and join #18xxgamesdev if you want to talk about implementing autorouting.

**Comment by dfannius** [comment] 2020-09-24 23:26
I'm going to close this since we think it's a dup. Hope to see you on Slack!

**Closed by dfannius** 2020-09-24 23:26 UTC
