### ISSUE TITLE
[1846] Steamboat causes player to have to force reload while operating MS

### ISSUE THREAD

**Issue by TomdeGre** [tobymao/18xx#5604] opened 2021-06-04 23:16 UTC
In any game where the steamboat exists (and asks its owner to get assigned in OR1.1), the player operating the MS the turn after is forced to reload the game in order to lay track. This does not appear to be the case when the steamboat was randomly removed, so my brain might be creating connections that do not exist.

Causation and wine. woooo

**Comment by benjaminxscott** [comment] 2021-06-07 14:48
Could you provide a game ID where this happened?
(even if it was a transient issue)

**Comment by jenf** [comment] 2021-06-11 09:50
Please provide a game id, otherwise we cannot proceed with this ticket.

**Comment by TomdeGre** [comment] 2021-06-12 01:27
https://18xx.games/game/45911

is an example. The issue appears in the same way in non-2p variants.

It always occurs when the MS operates during OR 1.1, and it appears to be linked to whether the steamboat is in the game (unsure whether it needs to be assigned for the bug to appear).

When the MS turn starts, the player cannot lay tiles directly. Either a browser reload, or a skip/undo action is required for the game to recognize the tile laying options of the MS. The issue is known to our playgroup to appear in several different browsers.

Nothing serious really since the fix is easy enough.

**Comment by benjaminxscott** [comment] 2022-02-03 17:05
I ran into this bug recently, it's still open

**Comment by mgaree** [comment] 2023-05-25 17:37
I've encountered this bug multiple times, most recently in game 119862 , dated 12 Apr 2023.

**Comment by michaeljb** [comment] 2023-05-29 19:28
Unfortunately the specific games referenced here have all been archived. I created a multiplayer game with Steamboat and Michigan Southern and could not reproduce after trying various combinations of actions for Steamboat - skipping assignment altogether, assigning to Big 4 / MS, or to one of the corporations, and haven't been able to reproduce yet.

I'll keep this open and hopefully the next time someone encounters it, the game ID can be shared so we can check it out before the game gets archived.

**Comment by philcampeau** [comment] 2023-08-29 18:35
No similar reports in quite some time. Will close.

We can always reopen if the problem starts popping up again.

**Comment by benjaminxscott** [comment] 2023-08-31 02:05
here's a repro
https://gist.github.com/benjaminxscott/b8c59be2c395c89df014811fc49113b5

https://18xx.games/game/133456?action=11

dstar2 had just used the SC, and it was now dstar's turn to operate the MS. Nothing is interactable in the MS's realm.

![image](https://github.com/tobymao/18xx/assets/1711810/f284d65e-8f8e-4a28-868e-d5ca69cc7ac0)

**Closed** 2023-09-02 04:23 UTC
Labels: 1846, minor bug
