### ISSUE TITLE
1861: unable to start minors with message that Nikolaev must start first despite Nikolaev already started

### ISSUE THREAD

**Issue by doubt72** [tobymao/18xx#7690] opened 2022-05-04 03:17 UTC
Can't start any minors in SR 3, message shows saying Nikolaev must be started first (Nikolaev has already been started and merged into a major).

https://18xx.games/game/82903?action=357

**How to Reproduce the Bug?**

Hard to be certain, but this is presumably happening after Nikolaev has been merged into a major:

<img width="1939" alt="Screen Shot 2022-05-03 at 9 13 45 PM" src="https://user-images.githubusercontent.com/801243/166618695-4d6be5be-546c-432c-a9f8-ec35b8858612.png">

**Which Browser / Platform?**

Chrome v 100.0.4896.88 MacOS desktop

**Comment by tobymao** [comment] 2022-05-04 04:41
@andypymont

**Comment by andypymont** [comment] 2022-05-04 06:52
@tobymao I can't reproduce this on a clone of the repo - has PR #7681 been deployed to the live server? Inspecting the sources being served this looks like an outdated version of `lib/engine/game/g_1861/step/buy_sell_par_shares.rb` is being used?
`return delete $.$$p,h(l.$type(),"minor")&&n(l.$id(),"N")&&c(G.game.$corporation_by_id("N").$ipoed())?"Nikolaev must be the first corporation":h(l.$type(),"major")&&m(G.game.$home_token_locations(l)["$empty?"]())?"No home token locations are available":_(G,b(G,"ipo_type",$,!1,!0),"ipo_type",[l],u)},1)}`

**Comment by dfannius** [comment] 2022-05-04 11:40
As of the time I write this note, the [latest commit](https://18xx.games/about) of the deployed version is [7766a2a1d](https://github.com/tobymao/18xx/commit/7766a2a1d), which is previous to the commit in which the fix to PR #7681 is merged.

**Comment by dfannius** [comment] 2022-05-04 11:41
(so the fix has not been deployed yet and presumably this will be fixed when it is)

**Comment by andypymont** [comment] 2022-05-04 15:19
Now the deployed version is [a87832c27](https://github.com/tobymao/18xx/commit/a87832c27), I also no longer see the message 
via [the game linked above](https://18xx.games/game/82903?action=357), so I believe this issue can be closed.

**Closed** 2022-05-04 16:02 UTC
Labels: 1861
