### ISSUE TITLE
[1822] Tax Haven being subtracted from other players

### ISSUE THREAD

**Issue by cwebblax** [tobymao/18xx#11185] opened 2024-08-30 17:01 UTC
This seems to be the opposite of the issue seen in 22CA. The tax haven value is correctly applied to the player who is the owner of the tax haven, however that value is then subtracted from all other players' total values. Seems to be the fix that was applied to 22CA was wrongly applied to regular 1822.

https://18xx.games/game/173003

**Comment by ollybh** [comment] 2024-08-31 12:00
Duplicate of issue #11040.

**Closed by ollybh** 2024-08-31 12:00 UTC
Labels: duplicate, 1822
