### ISSUE TITLE
[1880] can't run Trans-Siberian with 6E

### ISSUE THREAD

**Issue by metawidget-net** [tobymao/18xx#9049] opened 2023-03-22 23:11 UTC
https://18xx.games/game/116500

Companies with 6E train and a Trans-Siberian route (E.g. QSR in the final OR) couldn't get the route drawn between the off-board locations: could visit Russia or Vladivostok but not both.

Other trains (e.g. 6, 8) work fine and can connect cities/score bonus.

 Tried on an updated iPhone 13 Pro in Safari (iOS 16.3.1) and an updated MacBook Air (M1) in Chrome (111.0.5563.64).

**Comment by bentziaxl** [comment] 2023-03-23 12:11
duplicate of this: https://github.com/tobymao/18xx/issues/9034

**Closed by bentziaxl** 2023-03-23 12:11 UTC
Labels: needs triage
