### ISSUE TITLE
[1840] List of several bugs/suggestions

### ISSUE THREAD

**Issue by TomdeGre** [tobymao/18xx#5615] opened 2021-06-06 12:30 UTC
Bug: Restart and undo function has unintended effects on the stadtbahn tiles. Laying a stadtbahn tile and then undoing that action allows you to lay a stadtbah tile in the hex that was previously connected to the "undone" tile lay. Restarting the turn during the stadtbah tilelay step also allows your first tilelay to be a stadtbahn tile (this should not be the case according to rules 1X.4 - specifying this first tile needs to connect to your token). Undone stadtbahn tilelays also appear to no longer being placeable after a restart, since the game no longer recognizes them to be the next in the chain. This extends to future turns as well, bugging the ordering of the stadtbahn connections for the rest of the game.

Bug: Private companies pay no dividends in CR1/CR2 - Edit: seems they never pay dividends?

Bug/suggestion: The red and purple bonus tilelays can only be laid if the operating line is connected to any of those possible tiles. While the rules are not very specific, both the yellow bonus tile and the upgrade to green bonus action specify that they follow the normal track laying rules of IX.4 or IX.5. It goes to reason these tiles should be placeable even without connectivity, because all the bonus actions for red/purple are very close to the starting stations of the stadtbahns. Rarely will these tiles be connected this early in the game, and having all these tiles unplaced makes the game a lot less interesting since a large portion of the board becomes unpassable very early on.

Suggestion: The info tab should probably specify when phases change. It now does not tell you when the phase transitions and green tiles become available, neither under gamephases or on the timeline. (possible fix being to color-code the timeline as is done on the physical board?)

Bug: After a company buys a private, and it is consecutively sold to the bank, the money should go to the company. Currently, it still goes to the player, allowing the player to get money for it twice.

Bug(?): Tile L30b currently provides no revenue for non-stadtbahn lines. Should the village/dot in the centre not count as a halt and provide 30 revenue?

**Comment by Zwergenpunk** [comment] 2021-06-06 17:32
Bug1: I think I know why. Good catch

Bug2:  Argh... ;)

Bug3: I think my implementation is correct: https://boardgamegeek.com/thread/2643187/do-red-and-purple-hexes-stadtbahn-follow-same-plac

Suggestion 4: Yeah the phase change is not expected

Bug 5: Urgh again...

Bug 6: Duplicate of #5617

Thanks for your feedback.

**Closed** 2021-06-08 04:15 UTC
Labels: 1840, bug, enhancement
