### ISSUE TITLE
[18MS] $100 train discount from M&O private not being applied after selection

### ISSUE THREAD

**Issue by saccenti** [tobymao/18xx#10030] opened 2023-12-18 16:40 UTC
Not able to get the train discount. Similar issue to the one in 18AL described here: https://github.com/tobymao/18xx/issues/10023

An example: https://18xx.games/game/141855?action=65
Clone from here and test trying to buy the 3T with a discount.

**Comment by saccenti** [comment] 2023-12-18 16:45
Very similar issue here: https://github.com/tobymao/18xx/issues/9686. All these are related to a private that provides some kind of train-buying discount.

**Comment by michaeljb** [comment] 2024-01-07 22:52
Duplicate of #9192. The change made in #10098 may be applicable.

**Closed by michaeljb** 2024-01-07 22:52 UTC
Labels: needs triage
