### ISSUE TITLE
Make usage of C&WI Private ability (and possibly others) more clear

### ISSUE THREAD

**Issue by eheiden** [tobymao/18xx#1028] opened 2020-07-07 15:21 UTC
This is a UI enhancement request - but it is not directly obvious that one needs to click on the text below the private name within the company in order to use the ability.  Perhaps a generic button that says "use private ability" next to the company would be more clear?

**Comment by michaeljb** [comment] 2020-07-07 17:49
Duplicate of #940

**Closed by michaeljb** 2020-07-07 17:49 UTC
