### ISSUE TITLE
[1850] I sold five shares of MILW and the stock price did not decline. Game Id 132733 - Still broken!

### ISSUE THREAD

**Issue by Rupre** [tobymao/18xx#9878] opened 2023-11-08 23:19 UTC
**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by andrewzwicky** [comment] 2023-11-08 23:28
`Current version: deployed at Wed Nov 01 2023 22:54:47`

The latest code had not been deployed yet.  You can check the about page to see if it has been updated.

https://18xx.games/about

**Comment by Rupre** [comment] 2023-11-08 23:40
Are you saying the fix has not yet been deployed?  If so, when should I try
to sell the shares again?  In other words, when will the fix be deployed?

**Comment by andrewzwicky** [comment] 2023-11-09 00:26
Correct, I believe it has not been deployed yet.  I don't know when the deployments happen, so you'll have to wait and check back.

**Comment by Rupre** [comment] 2023-11-09 00:33
Ok, thanks for the update.

**Comment by benjaminxscott** [comment] 2023-11-09 20:37
Dupe of #9659

Fwiw deployments aren't scheduled on a cadence, it's whenever a maintainer with deployment permissions has time

**Closed by benjaminxscott** 2023-11-09 20:37 UTC
Labels: needs triage
