### ISSUE TITLE
[1849 Electric Dreams] Unable to continue

### ISSUE THREAD

**Issue by jeroenh** [tobymao/18xx#11294] opened 2024-10-20 21:03 UTC
**What's your Game ID?**
https://18xx.games/game/181994

As we are progressing to OR 6, the game keeps to hit upon move 217.

**How to Reproduce the Bug?**

The game seemed to hit the bug earlier in  as jeroenh was taking over the presidency of RCS. But after several attempts buying stock worked, and the presidency changed. However, jeroenh is unable to buy the last share, or to press pass.

**Comment by jeroenh** [comment] 2024-10-21 11:09
It is very weird, the error keeps appearing about move 217, but every once in a while we can progress with one or two moves. Then the error shows up again, and refreshes the game.

Move 217 was the first pass on issuing a bond it seems.

**Comment by ollybh** [comment] 2024-10-21 11:26
This might be the same as issue #11138.

**Comment by philcampeau** [comment] 2024-10-24 18:57
It is. Closing as duplicate of #11138

**Closed by philcampeau** 2024-10-24 18:57 UTC
Labels: bug, 1849 variants
