### ISSUE TITLE
Math bug with PEIR when all three shares are owned by a single player

### ISSUE THREAD

**Issue by skizelo** [tobymao/18xx#7859] opened 2022-05-31 13:48 UTC
https://18xx.games/game/82315?action=293
"CthulhuDreams now owns 99.99% of the PEIR"

Where'd the 0.01% of PEIR go?

**Comment by Maxwell-Frank** [comment] 2022-05-31 20:30
Not just a log error. It rounds incorrectly too: https://gist.github.com/Maxwell-Frank/5be41c98421a2296e3b49fac6963051e

**Comment by dfannius** [comment] 2022-06-21 19:49
Same as #7847?

**Comment by dfannius** [comment] 2022-06-22 00:32
Duplicate of #7847.

**Closed by dfannius** 2022-06-22 00:32 UTC
Labels: bug, 1871
