### ISSUE TITLE
[1856] Can't Declare Bankruptcy

### ISSUE THREAD

**Issue by Talbatross** [tobymao/18xx#5622] opened 2021-06-06 19:11 UTC
**What's your Game ID?**
https://18xx.games/game/45005?action=662

**How to Reproduce the Bug?**
Play poorly and when you need to E-Buy a train and don't have cash, you'll notice there's no Declare Bankruptcy.

**Which Browser / Platform?**
- Chrome 91.0.4472.77
- Windows 10 Desktop

**Comment by ventusignis** [comment] 2021-06-06 20:34
Thanks for the report!
Duplicate of #5608

**Closed by ventusignis** 2021-06-06 20:34 UTC
Labels: needs triage
