### ISSUE TITLE
Server error track building

### ISSUE THREAD

**Issue by serpentium** [tobymao/18xx#8046] opened 2022-07-05 19:35 UTC
Cannot accept building track 14 on C14 by the GW.
Tried with CLONE tool and it works.
Online doesnt
https://18xx.games/game/89363

**Comment by ventusignis** [comment] 2022-07-05 20:32
What error do you see when you are trying to lay tile 14?

**Comment by tobymao** [comment] 2022-07-05 20:37
@ventusignis 
Stack trace[Hide framework code]
ArgumentError: wrong number of arguments (given 0, expected 2)
                   /18xx/lib/engine/game/g_1856/game.rb: 1040:in `hexes_connected?'
                   /18xx/lib/engine/game/g_1856/game.rb: 1037:in `destination_connected?'
            /18xx/lib/engine/game/g_1856/step/escrow.rb:   18:in `block in auto_actions'
            /18xx/lib/engine/game/g_1856/step/escrow.rb:   18:in `select'
            /18xx/lib/engine/game/g_1856/step/escrow.rb:   18:in `auto_actions'
                         /18xx/lib/engine/round/base.rb:  146:in `auto_actions'
                          /18xx/lib/engine/game/base.rb:  707:in `process_action'
                                   /18xx/routes/game.rb:   88:in `block(6 levels) in <class

**Comment by crericha** [comment] 2022-07-05 21:42
The issue is CGR does not have a destination, but is marked as an escrow corporation, so the game tries to see if its non-existing destination is connected.

**Closed** 2022-07-05 22:36 UTC
Labels: bug, 1856
