### ISSUE TITLE
[1822] Company is able to build track to GWR London hex

### ISSUE THREAD

**Issue by Ticketautomat1** [tobymao/18xx#4470] opened 2021-03-12 20:52 UTC
LBSCR company is able to build track to the GWR London hex, without concession's owners agreement. GWR concession is in play. Due to rule 5.10.7 it should either not be possible or asking GWR's concession holder for his permission.

https://18xx.games/hotseat/hs_acjuhuop_31915

**Comment by magnusfalt** [comment] 2021-03-12 21:30
This is a duplicate of #4311, so im gonna close this.

**Closed** 2021-03-12 21:31 UTC
