### ISSUE TITLE
1861 - start value of major on wrong spot

### ISSUE THREAD

**Issue by Eludyan** [tobymao/18xx#3847] opened 2021-02-14 03:06 UTC
https://18xx.games/game/25843?active=2

When Ogg converted MNN to form the MKR the token stayed on the blue column 110 instead of moving to the starting value 110 in the pink section. 
![8F54CD36-CB84-4A5D-9363-87F893ABB4D8](https://user-images.githubusercontent.com/73318207/107867265-be01a400-6e36-11eb-81b3-8c294e952ff5.png)
![CC9D36D1-2EEC-4712-9426-9409B4A3D395](https://user-images.githubusercontent.com/73318207/107867269-c5c14880-6e36-11eb-98e8-df7c34369095.png)

**Comment by ChrisTheCat** [comment] 2021-02-14 03:13
Suggest deleting all the template text (from the 18Chesapeake example) next time you file a bug report.

Thanks for reporting, it's definitely a bug.

**Comment by Maxwell-Frank** [comment] 2021-02-14 03:32
@Eludyan I noticed this in a game too, but the rules state that when a company converts, it is parred at the "blue or teal" space on the stock market, which includes the space where the minor token is. I think when a minor converts its stock price is supposed to stay where it is.

**Comment by ChrisTheCat** [comment] 2021-02-14 03:40
No, that's not correct. That only applies to the 1D market. There are no blue or teal spaces on the 2D market.

**Comment by ChrisTheCat** [comment] 2021-02-14 03:42
<img width="246" alt="Screen Shot 2021-02-13 at 7 41 07 PM" src="https://user-images.githubusercontent.com/8732435/107867860-6d3c7c00-6e33-11eb-80f1-859a69bb0de1.png">

![image](https://user-images.githubusercontent.com/8732435/107867873-96f5a300-6e33-11eb-8bbf-5c426cbfbf1f.png)

**Comment by Maxwell-Frank** [comment] 2021-02-14 03:45
@ChrisTheCat It seems like we've run into another discrepancy between the old edition and the new edition: https://boardgamegeek.com/image/5033876/18611867


It seems like both of us remembered the market/rules from the old edition, but when I checked the new rules it seems to contradict.

**Comment by Maxwell-Frank** [comment] 2021-02-14 03:46
"9.1. Convert:
A  Minor  Company  is  eligible  to  Convert  to  a  Major Company if its stock token is in the 
blue zone of the stock market (100 to 165).
A. Price:   The   active   player   chooses   an   available unstarted Major Company and takes its 
charter. That player then sets its stock price to be the same as the converting   Minor   Company   
by   removing   the   Minor Company stock token and placing the new Major Company  stock  token  
in  its  place  in  the  Column Market, or on the blue or teal space of the same value if the Grid Market."

**Comment by ChrisTheCat** [comment] 2021-02-14 03:48
I have to think that's an inadvertent change in the creation of the new rulebook, and needs to be fixed.

**Comment by Maxwell-Frank** [comment] 2021-02-14 03:48
I'm happy to agree with you. Just wanted to point out the discrepancy.

**Comment by ChrisTheCat** [comment] 2021-02-14 03:56
I reported the error, hopefully it will be corrected.

https://boardgamegeek.com/filepage/212807/18611867-rulebook

**Comment by ChrisTheCat** [comment] 2021-02-14 03:58
Actually, the new rules have it correct on page 9.

<img width="530" alt="Screen Shot 2021-02-13 at 7 57 57 PM" src="https://user-images.githubusercontent.com/8732435/107868084-dde49800-6e35-11eb-9b64-21c6ba7ae364.png">

**Comment by Maxwell-Frank** [comment] 2021-02-14 04:02
That doesn't actually clarify anything though.  The rules are clear that if you start a major directly, it needs to be on the pink $100 space, but that is not made clear in the conversion section. 

Looking at the merger rules, it looks like there is just a general typo of the merged/converted companies need to par at a "pink or teal" par value, and not a "blue or teal."  It's not a rules error, just a typo.

**Comment by ChrisTheCat** [comment] 2021-02-14 04:11
Confirmed in the Designer FAQ on BGG:

Q. Merging:  “The price of the new Public Company is equal to the sum of the highestpriced and lowest priced Minor Companies involved (rounded down if necessary)”.So, where does its stock market token go?

A. When minors merge, it’s just like starting a new company.  In fact, it is starting anew company.  So put the token on the red or purple space with the right value.Similarly, when a minor transforms, the result is also a new company and the tokengoes on the red or purple space with the right value.

https://www.boardgamegeek.com/filepage/31271/faq-designers

**Comment by Eludyan** [comment] 2021-02-14 05:10
I wondered about that and will next time. Thanks!

**Comment by jenf** [comment] 2021-02-14 07:59
I read the rules the other way, will fix

**Comment by ianwilson156** [comment] 2021-02-14 09:29
I agree with Maxwell-Frank, it's a kind of typo in the new rules - it should say "pink or teal". Didn't spot that when proofreading - rats! (My excuse - not familiar with the new colours.)

**Closed** 2021-02-15 03:44 UTC
Labels: 1861, bug

**Comment by jenf** [comment] 2021-02-15 10:36
@ianwilson156 Is Josh aware of the typo?

**Comment by ianwilson156** [comment] 2021-02-15 11:12
Not yet...

------ Original Message ------
