### ISSUE TITLE
Rules access?

### ISSUE THREAD

**Issue by SmithInMN** [tobymao/18xx#550] opened 2020-05-28 16:21 UTC
I feel like there has been a lot of talk in the chat about rules based issues.

Is it possible to have either a link to a .pdf of the rules somewhere in each game?  Or to have the actual text accessible.  

I know it's not the biggest inconvenience in the world, but it would definitely help!

**Comment by dfannius** [comment] 2020-05-28 16:31
Duplicate of #161.

**Closed by dfannius** 2020-05-28 16:31 UTC
