### ISSUE TITLE
Game 27853 unable to upgrade yellow dot city next to Prague with bcb owned small company 18cz

### ISSUE THREAD

**Issue by corian09** [tobymao/18xx#3968] opened 2021-02-17 14:33 UTC
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

Please fill out the bug report title with the game name and description

e.g. "[18Chesapeake] Incorrect revenue for route from Baltimore to DC"

**What's your Game ID?**

If your game is "Multiplayer", provide the link to the game. Copy the link from your browser which will look something like `https://18xx.games/game/31337`

- (optional) Provide a link to the specific action that triggered the bug using the `Game` tab and `History` navigation arrows. Copy the resulting link from your browser which will look something like `https://18xx.games/game/31337?action=42`

If your game is "Hotseat", provide a link to your raw game data by using the `Tools` tab and `Copy Game Data`.

Paste that data [into a github gist](https://gist.github.com/) and share the resulting link which will look something like `https://gist.github.com/[your_name]/[some_letters]`.

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

e.g.
- During Operating Round 2.1 the B&O ran a 2 train from Baltimore to DC
- B&O has a token in Baltimore, and both cities are yellow tiles
- Revenue was less than the $60 that I expected

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
- Browser Version
  - On Chrome, see [chrome://version](chrome://version)
  - On Firefox, see [about:support](about:support)
  - On Safari, see [these methods](https://www.lifewire.com/check-the-version-number-of-safari-446563)
- Platform (Mobile, Tablet, Desktop)

**Comment by dfannius** [comment] 2021-02-17 15:12
https://18xx.games/game/27853?action=340

**Comment by Zwergenpunk** [comment] 2021-02-17 16:27
i think this is  a duplicate of #3874. will be fixed when @benjaminxscott  PR is merged

**Closed** 2021-02-17 17:16 UTC
Labels: 18CZ, bug
