### ISSUE TITLE
[1882] Set uninitialised constant

### ISSUE THREAD

**Issue by markpwindle** [tobymao/18xx#10507] opened 2024-03-17 10:46 UTC
**What's your Game ID?**

https://18xx.games/game/154470

https://18xx.games/game/154470?action=21

**How to Reproduce the Bug?**

Open the game

**Which Browser / Platform?**

Any

**Comment by ollybh** [comment] 2024-03-17 10:56
Duplicate of #10484.

**Closed** 2024-03-17 10:56 UTC
Labels: needs triage
