### ISSUE TITLE
[18SJ] Broken game with error message and history deleted or changed - game was pinned to adc723abd

### ISSUE THREAD

**Issue by gardir** [tobymao/18xx#8172] opened 2022-08-12 04:45 UTC
**What's your Game ID?**

https://18xx.games/game/89015?action=68

**How to Reproduce the Bug?**

Should suffice to open the link and get the error message is displayed.
```
We're sorry this game cannot be continued due to GameError: 6 is not upgradeable to 57
Broken action: { "type": "lay_tile", "entity": "ÖKJ", "entity_type": "corporation", "id": 69, "created_at": 1656521226, "hex": "C12", "tile": "57-1", "rotation": 2 }
```
The game also was in a much later phase (**5**, **6** or **D**), with pretty much the whole map tiled out. Now it seems to either have "backtracked" far back in history or something.

**Comment by perwestling** [comment] 2022-08-12 14:28
Hard to figure out why it breaks. But the game is from late june and there has been no action for over a month. The game is pretty early as well.

I would suggest starting another game which uses the latest version. There were some fixes done during the summer.

So @gardir, I think I will close this ticket - OK?

**Comment by gardir** [comment] 2022-08-12 14:31
That's the trouble - we have played this game steadily and suddenly it has reverted to this point since yesterday. We were ad I tried to say 5, 6, or D phase

**Comment by gardir** [comment] 2022-08-12 14:31
But still, it was pinned and I can agree to discard the game. Just wanted to report the bug when it happened in case it is present in current version.

**Comment by perwestling** [comment] 2022-08-12 19:49
@gardir Are you playing in the game? It seems like persons not playing in the game can get this effect (of broken undoes) when looking on games. This was caused by a recent change of handling user identification. And it was not related to 18SJ specifically, just all games with chat in.

**Comment by gardir** [comment] 2022-08-12 20:07
Yup, I'm the game creator xD

**Comment by perwestling** [comment] 2022-08-13 20:24
I close this for now. It is probably a general problem caused by recent changes. So no special action for this game.

**Closed by perwestling** 2022-08-13 20:24 UTC
Labels: needs triage
