### ISSUE TITLE
1862: Can't upgrade a city creating a connection to it.

### ISSUE THREAD

**Issue by jdgalt** [tobymao/18xx#6543] opened 2021-11-26 17:57 UTC
**What's your Game ID?**

Game ID = 61856, multiplayer.  https://18xx.games/game/61856

Action https://18xx.games/game/61856?action=158

During WVR's turn just finished, it attempted to upgrade Great Yarmouth to tile 792, thus connecting to it from the SW.  The game UI did not have Great Yarmouth highlighted and would not accept a play there.

I found a better tile lay and do not want WVR's turn changed.  But another player said I should report the bug anyway.

**How to Reproduce the Bug?**

Back up to WVR's tile laying step, which was at 08:19 PST (16:19 GMT) on Friday, Nov 26.  You can see that Great Yarmouth is not highlighted even though the operating company has track pointed there.

What steps cause the unexpected behavior?

Clicking on Great Yarmouth gave an error message which I don't see by using the history method to get there.

**Which Browser / Platform?**

Google Chrome | 69.0.3497.100 (Official Build) (64-bit)
-- | --
Revision | 8920e690dd011895672947112477d10d5c8afb09-refs/branch-heads/3497@{#948}
OS | Linux
JavaScript | V8 6.9.427.23
Flash | 32.0.0.465 /home/jdgalt/.config/google-chrome/PepperFlash/32.0.0.465/libpepflashplayer.so
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
Command Line | /usr/bin/google-chrome-stable --flag-switches-begin --flag-switches-end --origin-trial-disabled-features=CaptureHandle
Executable Path | /opt/google/chrome/google-chrome

- Platform (Mobile, Tablet, Desktop)
Desktop.  Ubuntu, not sure how to show the version.

**Comment by roseundy** [comment] 2021-12-07 05:09
Bug is caused by the same tile instance being laid twice. This should be impossible.

**Comment by roseundy** [comment] 2021-12-07 05:14
This looks like corrupted game state. When I back up to the point the tiles were laid, and re-lay them, it works fine.

**Comment by magnusrk-ch** [comment] 2021-12-13 21:51
Seems like there should be validation in the lay_tile action that verifies the tile isn't already laid. #6599 demonstrates that the game will probably break for good down the line, when undoing is no longer a good option.

**Comment by roseundy** [comment] 2021-12-14 01:24
Yeah, I've been thinking about adding that to the lay_tile action.

**Comment by roseundy** [comment] 2021-12-26 17:25
I've added a sanity check to 1862 tile lays: #6675

**Comment by magnusrk-ch** [comment] 2022-01-20 16:40
Should we close this then?

**Closed** 2022-01-20 16:59 UTC
Labels: bug, 1862
