### ISSUE TITLE
1822PNW allowing minors to lay track across water through little spikes

### ISSUE THREAD

**Issue by Avemo3** [tobymao/18xx#8293] opened 2022-09-06 16:15 UTC
https://18xx.games/game/96683

M6 laid track in C10 and M21 laid track on N17.

It also allowed for CMPS to reach M21 through the water for eating the minor

**Comment by outsidePasser** [comment] 2022-09-07 02:17
Duplicate of #8287

**Closed** 2022-09-07 02:17 UTC
