### ISSUE TITLE
[1846] We're sorry this game cannot be continued due to Set: uninitialized constant

### ISSUE THREAD

**Issue by easydoesit123** [tobymao/18xx#10485] opened 2024-03-17 06:40 UTC
We're sorry this game cannot be continued due to Set: uninitialized constant Engine::SharePool::Set
Broken action: { "type": "par", "entity": 14449, "entity_type": "player", "id": 24, "created_at": [1710623995](tel:1710623995), "corporation": "IC", "share_price": "124,0,12" }
Please [raise a bug report](https://github.com/tobymao/18xx/issues?q=is%3Aissue+is%3Aopen+label%3A1846,%22needs%20triage%22) and include this link (https://18xx.games/game/156709?action=23)

**Comment by ollybh** [comment] 2024-03-17 10:48
Duplicate of #10484.

**Closed by ollybh** 2024-03-17 10:48 UTC
Labels: needs triage
