### ISSUE TITLE
[1861] tile laying gives "no implicit conversion of nil into Array" error (game 37543)

### ISSUE THREAD

**Issue by th3tick** [tobymao/18xx#5405] opened 2021-05-20 02:45 UTC
laying tile E11 then upgrading tile E13, this pops up for about 2 seconds, then it reloads at the start of my turn
<img width="657" alt="Screen Shot 2021-05-19 at 7 06 26 PM" src="https://user-images.githubusercontent.com/48138042/118911191-0bccf300-b8e3-11eb-9478-371a7e5975a2.png">

**Comment by jenf** [comment] 2021-05-20 19:26
Please provide game id and action id

**Comment by dfannius** [comment] 2021-05-20 19:29
Game ID is 37543 per the subject. Looks like action 411, although I couldn't replicate the issue when I tried it in hotseat.

**Comment by jenf** [comment] 2021-05-20 19:40
yeah, server is rejecting it not the client, so probably okay on hotseat.

**Comment by jenf** [comment] 2021-05-20 21:49
Could you try to resubmit. If it's still failing, exactly which tile are you submitting at which steps?

**Comment by th3tick** [comment] 2021-05-20 23:44
I just tried it again from a new tab and get the same results.  The tiles I'm using are a straight dit in E11 and a green K dit, pointed up-left in E13.

**Comment by tobymao** [comment] 2021-05-22 04:19
debugged this with @th3tick, this is due to the extension privacy badger. he confirmed that when it is active, it fails, and when it is off, it works as intended.

closing since this is an issue with a 3rd party extension

**Closed by tobymao** 2021-05-22 04:19 UTC
Labels: 1861, bug, question
