### ISSUE TITLE
[1822] "need to sell shares before a loan can be granted"

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#10072] opened 2023-12-31 20:00 UTC
https://18xx.games/game/141861?action=733

In this game the following comment was shown:

We're sorry this game cannot be continued due to GameError: ChrisBa still need to sell shares before a loan can be granted
Broken action: { "type": "buy_train", "entity": "21", "entity_type": "corporation", "id": 734, "created_at": 1703543138, "train": "3-5", "price": 200, "variant": "3" }
Please [raise a bug report](https://github.com/tobymao/18xx/issues?q=is%3Aissue+is%3Aopen+label%3A1822,%22needs%20triage%22) and include this link (https://18xx.games/game/141861?action=733)

**Comment by benjaminxscott** [comment] 2024-01-03 18:09
known issue dupe of 10059

**Closed by benjaminxscott** 2024-01-03 18:09 UTC
Labels: needs triage, 1822

**Comment by beorn7** [comment] 2024-01-06 12:01
Note that this is about standard 1822, while #10059 says: "Standard 1822 doesn't have this problem"

Is it really the same bug?

**Comment by beorn7** [comment] 2024-01-06 14:58
Also note that the game above didn't stop at the point where the error is reported now. We actually played beyond that point quite a bit. The game broke later and got reset to the point above (presumably after an update).

I guess the old code allowed to take the loans even though there were still shares to be sold.
