### ISSUE TITLE
1849 - Closed companies donot regain their reserved home location 

### ISSUE THREAD

**Issue by Aavar77** [tobymao/18xx#3280] opened 2021-01-13 20:46 UTC
https://18xx.games/game/22478
- when companies close their home location should be once again reserved.
This did not happen in this game, 
I noticed it previoous games but thought it was a function of the bug not able to refloat cclosed companies

as per Rule 11. in the 1949 rule set 3rd paragraph
When a corporation closes, a token spot on the home city of a corporation
is reserved for it, in the same way as if it had not been
started yet.

**Comment by tysen** [comment] 2021-01-13 20:49
Duplicate of #3279

**Closed** 2021-01-13 20:53 UTC
