### ISSUE TITLE
1822PNW

### ISSUE THREAD

**Issue by fsaglio** [tobymao/18xx#8358] opened 2022-09-19 23:51 UTC
game https://18xx.games/game/98111

SWW was started in SR8, which was in phase 5.   When it was started it should have replaced M8’s token on the map. 

Instead, that did not - M8 is in one of the bid boxes and SWW appears to not exist on the map.

**Comment by outsidePasser** [comment] 2022-09-21 04:34
Duplicate of #8352

**Closed** 2022-09-21 04:34 UTC
Labels: needs triage
