### ISSUE TITLE
Harzbahn 1873 missing borders in dark mode

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#8603] opened 2022-12-19 02:02 UTC
The borders showing the current values of mines and switchers are missing in dark mode.

<img width="324" alt="Screen Shot 2022-12-18 at 17 58 20" src="https://user-images.githubusercontent.com/8732435/208333327-8ab0404a-dbaf-4e6d-bf67-93b204e3d8d4.png"> <img width="332" alt="Screen Shot 2022-12-18 at 18 02 06" src="https://user-images.githubusercontent.com/8732435/208333549-70ef53ff-2f7a-4878-b961-ee46f7a6d822.png">

**Comment by ChrisTheCat** [comment] 2023-02-17 14:38
Realized this is a duplicate of 4913

**Comment by andrewzwicky** [comment] 2024-02-17 17:01
closing as dupe of #4913

**Closed by andrewzwicky** 2024-02-17 17:01 UTC
Labels: Harzbahn 1873, game UI
