### ISSUE TITLE
[18NY] Merge failed. "0 is not valid to spend"

### ISSUE THREAD

**Issue by juliank-e** [tobymao/18xx#6669] opened 2021-12-24 02:46 UTC
**What's your Game ID?**

https://18xx.games/game/65204?action=876

(Please note: this is our first game of 18NY, it's possible I missed something in the merger rules, although I have reread them a couple times)

**How to Reproduce the Bug?**

- OR 6.1
- I wanted to use B&A to acquire NY&H (I was president of both companies)
- B&A had a route and sufficient money to merge NY&H (I also tried fully withholding and had ~$900 and still couldn't merge)
- When I clicked "merge (-$480)" it said "0 is not valid to spend" and the merge didn't happen (although it did briefly show **B&A merges with NY&H** in the history, but then it disappeared) 

**Which Browser / Platform?**
Chrome for iOS 94.0.4606.76

**Comment by crericha** [comment] 2021-12-27 02:30
Duplicate of #6661. Fix has been deployed. If it still isn't working for you, please reopen.

**Closed by crericha** 2021-12-27 02:30 UTC
