### ISSUE TITLE
1849: game 31365

### ISSUE THREAD

**Issue by nockwurst** [tobymao/18xx#4578] opened 2021-03-18 13:04 UTC
https://18xx.games/game/31365

Unable to enter game during my action.  Occurred mid game, can enter other games, cannot get back into this specific game to complete my turn.

**Comment by casabian** [comment] 2021-03-18 13:11
Seems like a duplicate of #4574.

**Comment by michaeljb** [comment] 2021-03-18 13:50
dup of #4574, fixed by c604519

**Closed** 2021-03-18 13:52 UTC
Labels: needs triage
