### ISSUE TITLE
[18Rhl] Private 4 tile upgrade seems to freeze game

### ISSUE THREAD

**Issue by xmunroe** [tobymao/18xx#7042] opened 2022-02-08 17:44 UTC
**What's your Game ID?**
https://18xx.games/game/71013

https://18xx.games/game/71013?action=234

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?
- During Operating Round 5.2 upgraded tile D11 and then tried to use company power to upgrade tile D9, but the interface becomes unresponsive. Unable to click the green check or red 'X' or anything else
- upon reloading page, tile D9 is placed and play can continue.

Please include screenshots (you can drag and drop or upload them into this issue)

**Which Browser / Platform?**
- Browser Version
  - On Chrome 97.0.4692.99 (Official Build) (64-bit) (cohort: Stable)

**Comment by perwestling** [comment] 2022-02-08 21:41
Might be hard to fix as it is a pinned game, but it is good that it is possible to continue to play after reload.
I will take a look and see if I can locate the cause.

**Comment by tobymao** [comment] 2022-02-08 21:45
pinned games have no support, closing issue

**Closed by tobymao** 2022-02-08 21:45 UTC
Labels: minor bug, 18Rhl
