### ISSUE TITLE
[18MS] Private Meridian and Memphis Railway not giving discount

### ISSUE THREAD

**Issue by KillerOrca** [tobymao/18xx#1676] opened 2020-09-16 18:05 UTC
https://www.18xx.games/game/9795?action=166

Private text:
The owning Major Company may lay their cheapest available token for half price. This is not an extra token placement. This ability can only be used once, and using it does not close the private company.

WRA had a $100 cost token remaining. Paid full price for laying it.

**Comment by perwestling** [comment] 2020-09-17 07:29
If you just click to place a token it will use full price token. To activate the reduced cost you need to click on the ability on top:
![image](https://user-images.githubusercontent.com/2631151/93433968-cd041a80-f8c7-11ea-8b96-19d054611741.png)

And then you can place the token, and it will cost just $50.
![image](https://user-images.githubusercontent.com/2631151/93434071-f329ba80-f8c7-11ea-8554-f6ee9e755eff.png)

I suppose it would be possible to automatically trigger the ability if the company had only $100 tokens left, but it is also good to have a uniform behavior. 

Have cloned the game at action 165 and tried to lay token via the ability and by not going via ability, and it works as intended.

@KillerOrca, is it OK to close this issue?

**Comment by KillerOrca** [comment] 2020-09-17 14:09
@perwestling I tried clicking on the private then placing the token but where I clicked was on the charter. Which is where I am used to clicking for 1846/18Chesapeake. Are you saying that it has to be done by clicking the show ability button or should clicking the private on the charter work?

Since you were able to get it to work maybe a display update when the ability is activated would be a better request.

**Comment by perwestling** [comment] 2020-09-17 15:34
@KillerOrca Yes, click on the Abilities on the top activates the ability. This is how it is done in e.g. 18AL. 

You click on the name, not on the Show button. When you do the text appear. See picture in my comment above for how it looks. In other words it does update the display a bit when you update the ability. For some other abilities it has more effect, e.g. when clicking on the Lumber Terminal ability in 18AL the hexes where you can place it are high lighted. For 18MS/AL privates that gives discount for train buy the price shown is the discounted price etc.

So I do think that clicking on the upper ability is the way to go. For some titles there might be more automatic selections, but that would case problems if you do not want to use your special ability at the first opportunity.

If I remember correctly the tile laying in 18CHesapeake also used the click-on-top-ability to trigger? But I am not sure.

**Comment by KillerOrca** [comment] 2020-09-17 15:45
@perwestling I played 18Cheasapeake when it was click the private on the company charter so the show ability button is new for me.

Either way like the tile laying powers highlighting reserved sections of the board when active if the token power activation showed the new reduced token cost that would be a good visual indicator the power is active.

**Comment by perwestling** [comment] 2020-09-17 15:55
The way to click on the ability on the top is a bit new, but I think it is used in all titles.

Highlightning wont work for this ability. It is just a tokening in a normal location.

But reducing the cost of the cheapest token on the company charter when clicking on the ability on top, that is a good idea. I will look into if that is possible to implement with reasonable effort.
As it is, at least the log shows the reduced cost if ability is used to lay the token.

**Comment by tobymao** [comment] 2020-09-17 16:07
closing since it's working as intended

**Closed by tobymao** 2020-09-17 16:07 UTC
Labels: 18MS

**Comment by perwestling** [comment] 2020-09-17 20:12
I checked a bit in the code if it would be easy to show the reduced token price on the company charter, and it was not. So pass on this one.
