### ISSUE TITLE
18 Royal Gorge Error

### ISSUE THREAD

**Issue by ArcticOctopus** [tobymao/18xx#10748] opened 2024-05-12 01:30 UTC
**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by ollybh** [comment] 2024-05-12 09:01
@ArcticOctopus We need more information to be able to understand and fix the problem that you have encountered. Can you please let us know the game ID of the game where this issue occurred? And what is the error you saw?

**Comment by ArcticOctopus** [comment] 2024-05-12 13:23
I thought I did but maybe it didn't save.

https://18xx.games/game/161832

After I hit done after laying track in OR 4.2 I received a "undefined
method 'count' for nil"
Error message.

Hope this helps!

Ian

**Comment by benjaminxscott** [comment] 2024-05-12 19:48
dupe of https://github.com/tobymao/18xx/issues/10735

**Closed** 2024-05-13 01:31 UTC
Labels: 18RoyalGorge
