### ISSUE TITLE
Unable to change player count min or max on chrome for android

### ISSUE THREAD

**Issue by chadamir** [tobymao/18xx#11350] opened 2024-11-15 15:42 UTC
Take for example 1830 minimum player count defaults to 2 max defaults to 6. Attempts to change the number when starting a new game just automatically revert to the default.

**Comment by philcampeau** [comment] 2024-11-15 18:42
Confirmed on my end.

**Comment by ollybh** [comment] 2024-11-16 11:35
Duplicate of #11071.

**Closed by ollybh** 2024-11-16 11:35 UTC
Labels: bug, duplicate, front page
