### ISSUE TITLE
1856 Canadian  Government Railroad

### ISSUE THREAD

**Issue by Willempie3** [tobymao/18xx#7684] opened 2022-05-02 17:38 UTC
The  CGR has only a single president share, 5 or 10 percent. This should be 10 or 20 percent.

**Comment by ventusignis** [comment] 2022-05-02 18:00
Hello Willempie3, do you have a link to a game to refer to? If you are referring to this game, I don't see anything wrong in the game:
https://18xx.games/game/79312?action=752

It is worth noting, rules as written, in the case of a 20 share CGR *all shares* are half a cert, so the 2-share presidency is 1 cert, not half a cert

> The CGR has only a single president share, 5 or 10 percent. This should be 10 or 20 percent.

This is correct, in almost all cases. The only exception is when nobody gets more than 1 share of the CGR but there are enough market shares to force it to be a 20 share corporation - in this case a player becomes president with 1 share (5%) until this can be corrected in the next stock round

**Comment by dfannius** [comment] 2022-05-20 18:14
@Willempie3, it seems like this is expected behavior. If you still think it is not, please respond to ventusignis's comment; otherwise we will close this issue.

**Comment by ventusignis** [comment] 2022-07-05 22:42
I'm closing this since there hasn't been a followup in over a month

**Closed by ventusignis** 2022-07-05 22:42 UTC
Labels: question, 1856
