### ISSUE TITLE
1861 Tile #25 does not upgrade to #40

### ISSUE THREAD

**Issue by Mamimus** [tobymao/18xx#6697] opened 2022-01-02 11:41 UTC
This is happening in https://18xx.games/game/66718 

While playing this round, we noticed that we could not upgrade tile 25 to 40 in any location where they occured (H6, M5, I9) with any company (such as MK or NW). Occording to the rules we have this should however be a valid upgrade. Other upgrades are possible so I do not believe this is an issue of wrong phase or not being allowed to upgrade that track. Tiles are also still available.

![Screenshot from game](https://user-images.githubusercontent.com/96953859/147874539-f203cc66-4e36-4903-8547-b483ebdedc12.png)

**Comment by crericha** [comment] 2022-01-02 20:58
Duplicate of #6683. Thanks for reporting.

**Closed by crericha** 2022-01-02 20:58 UTC
