### ISSUE TITLE
[The Old Prince 1871] During an emergency train buy, interface allows sale of more than 30% of a company.

### ISSUE THREAD

**Issue by mrwong** [tobymao/18xx#10167] opened 2024-01-22 03:43 UTC
**What's your Game ID?**
https://gist.github.com/mrwong/87dd8593332b938131f7b01c9f61932d

**How to Reproduce the Bug?**
Preparation: Be forced into emergency train buying.
![image](https://github.com/tobymao/18xx/assets/9300737/8eaeb986-130b-4df9-9f2a-5d03c2b4fdcc)

Expected behavior: Cannot sell 5.

Actual Behavior: 
![image](https://github.com/tobymao/18xx/assets/9300737/ad5a1555-90f4-4377-859e-4f6e1018094d)

**Which Browser / Platform?**

**Comment by philcampeau** [comment] 2024-01-22 14:14
Duplicate of #8260

**Closed by philcampeau** 2024-01-22 14:14 UTC
Labels: duplicate
