### ISSUE TITLE
Main page: sorting of games over pages

### ISSUE THREAD

**Issue by Herbert62** [tobymao/18xx#491] opened 2020-05-24 11:28 UTC
It seems the games are sorted only in the page.
In my case I see finished games with high IDs on page 1 and running games with low ID on page 2. Once I had the situation that an orange one was on page 2 - and I did not see it when I checked page 1.

**Comment by dfannius** [comment] 2020-05-24 11:47
Duplicate of #356.

**Closed by dfannius** 2020-05-24 11:47 UTC
