### ISSUE TITLE
[1836JR 56] Can't lay tile in B10

### ISSUE THREAD

**Issue by Ticketautomat1** [tobymao/18xx#9636] opened 2023-09-18 21:05 UTC
In this game of 36jr 56 company NFL can't lay a tile on hex B10

https://18xx.games/game/131878?action=20

**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by benjaminxscott** [comment] 2023-09-19 04:49
It seems to work on hotseat

Does it not allow the hex to be clicked? (e.g. grayed out and not selectable)

If it's allowing the hex to be selected, is there any error being thrown after the green checkbox is clicked?

**Comment by Ticketautomat1** [comment] 2023-09-19 05:53
It allows the hex and the tile to be clicked, but after then it reports an "illegal action, wrong number of arguments, given 0 expected 2"

Just try it in master mode.

**Comment by philcampeau** [comment] 2023-09-20 03:10
Worked for me in master mode too.

**Comment by ollybh** [comment] 2023-12-26 12:47
I also can't reproduce this bug, so I'll close this issue.

**Closed by ollybh** 2023-12-26 12:47 UTC
Labels: 1836jr56, cant_reproduce
