### ISSUE TITLE
[1889] SR1, game autopasses owner of Dougo Railway if they can't afford a share. 

### ISSUE THREAD

**Issue by philcampeau** [tobymao/18xx#7685] opened 2022-05-02 21:08 UTC
Game autopasses owner of Dougo Railway if they can't afford a share, but they should have the option to exchange the Dougo for a share of IR, assuming it has been parred (however bad an idea that may be!).

See log here: https://gist.github.com/philcampeau/bcc1fe7ad185f1854b9957e08f851371

Problem may also affect the Mohawk & Hudson private in 1830.

**Comment by Maxwell-Frank** [comment] 2022-05-03 15:23
Duplicate of #4403 and probably the longest-standing bug on the site.

**Comment by benjaminxscott** [comment] 2022-05-03 15:44
We do have a note on this in the wiki fwiw https://github.com/tobymao/18xx/wiki/1889#implementation-notes

But yeah it's a known issue

**Closed by benjaminxscott** 2022-05-03 15:44 UTC
Labels: needs triage
