### ISSUE TITLE
[1870] Cannot close company

### ISSUE THREAD

**Issue by ddaybell** [tobymao/18xx#6859] opened 2022-01-28 02:29 UTC
In the following game:

https://18xx.games/game/69080

We are stuck on the SSW's turn.  The SSW owner wishes to skip track lay, but the game won't process the command.  It returns an error message as follows:

"undefined method 'operating history' for nil".

not sure what is going on, since the SSW owner has been able to skip laying tiles for that same company several times already this game.  NB: He wants to just close the company without ever laying a tile.

**Comment by benjaminxscott** [comment] 2022-01-29 02:42
dupe of https://github.com/tobymao/18xx/issues/6686

**Closed by benjaminxscott** 2022-01-29 02:42 UTC
Labels: bug, 1870
