### ISSUE TITLE
1841 potential bug

### ISSUE THREAD

**Issue by summerjumbo** [tobymao/18xx#9654] opened 2023-09-21 12:09 UTC
To be described.

**What's your Game ID?**

While the rule of 1841, 4.5 describes "Any corporation which is operating must have at least one train during its turn of an Operating Round unless there is no route available on which it could possibly run.", one of my corporation is forced to buy a train who has no more available route. I mean that the corporation has lost the only legal route by being bought of the station in that route.

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by roseundy** [comment] 2023-09-21 13:25
Can you please include a link to the game with the bug? I can't debug without this.

**Comment by summerjumbo** [comment] 2023-09-21 14:57
just got a case.
https://18xx.games/hotseat/hs_xblfzffw_134784
in the game, IFAI is just forced to buy a train. no skip allowed.
IFAI had two tokens on the board, H10 and E11 and H10 was bought by RTSF(and further bought by CFCC)
so only E11token is on now.

**Comment by philcampeau** [comment] 2023-09-21 15:22
Hotseat games are stored locally, not on the server. 

If your game is "Hotseat", provide a link to your raw game data by using the `Tools` tab and `Copy Game Data`.

Paste that data [into a github gist](https://gist.github.com/) and share the resulting link which will look something like `https://gist.github.com/[your_name]/[some_letters]`.

**Comment by summerjumbo** [comment] 2023-09-21 22:23
thanks for letting me know them.

hope this works.
[summerjumbo](https://gist.github.com/summerjumbo)/[1841bug#9654](https://gist.github.com/summerjumbo/c4cb5562d945eb65d1d7c809e33b3298)

**Comment by roseundy** [comment] 2023-09-22 02:07
That worked.

So the problem is that 1841 is the first game on 18xx.games where a corporation can lose a legal route after it has one. In this case, it happened because the corporation in question sold one of its tokens to another corporation. But I believe it could also happen when another corporation tokens a pass the corporation in question used to form a legal route (to a city/town/port on the other side of the pass).

**Comment by summerjumbo** [comment] 2023-09-22 03:17
another bug. i think this is also related to a legal route problem.
https://gist.github.com/summerjumbo/5b42bbfcda0928a53497eebc6367374c
IFAI just started and laid its "home" H10 tile and reached Milan. but could not buy CFCC's token at Milan. No token buying message and treated as automatically skipped. Of course it was not the last CFCC token.

**Comment by roseundy** [comment] 2023-09-22 03:22
That really needs to go into a separate bug report, since the fix for the first bug will close this issue automatically.

**Comment by roseundy** [comment] 2023-09-22 03:25
Besides, it's not a bug since IFAI doesn't have any unplaced tokens.

**Comment by summerjumbo** [comment] 2023-09-22 05:04
very sorry i misunderstood.

**Closed** 2023-09-22 21:59 UTC
Labels: rules-broken, 1841
