### ISSUE TITLE
 [1867] Cannot upgrade Montreal to Silver, thinks tile 639 is already on A1

### ISSUE THREAD

**Issue by wcraigtrader** [tobymao/18xx#8610] opened 2022-12-22 21:13 UTC
DO NOT PASTE THE GAME JSON! Please use [gist](https://gist.github.com/) instead.

Please fill out the bug report title with the game name and description

e.g. "[18Chesapeake] Incorrect revenue for route from Baltimore to DC"

**What's your Game ID?**

https://18xx.games/game/106713
I
**How to Reproduce the Bug?**

Try and lay any tile. I wanted to upgrade Montreal to Silver. It will flash an error lile:

Cannot lay tile 639-0 on L12; it is already on A1

**Which Browser / Platform?**

Linux / Google Chrome / Version 108.0.5359.124 (Official Build) (64-bit)

**Comment by michaeljb** [comment] 2022-12-22 21:17
Caused by #8609, fixed by 984ef17

**Closed by michaeljb** 2022-12-22 21:17 UTC
Labels: needs triage
