### ISSUE TITLE
1822PNW Phase 6, 2 bugs

### ISSUE THREAD

**Issue by Avemo3** [tobymao/18xx#8295] opened 2022-09-06 17:54 UTC
https://18xx.games/game/96683

NPR was started by merged in Phase 6.  Purchasing shares from the treasury is not funding the company.

M8 was unable to convert into major company:
 4.7.2 To convert an Associated Minor certificate into a major company in Phase 5 or later, exchange the Associated Minor’s certificate with the president’s certificate of the associated major company. Transfer all assets from the minor company’s charter to the major company’s charter. Flip the Associated Minor’s home token to the major company’s side and exchange the minor company’s stock market token with the major company’s stock market token, placing it on the same value even if outside the par price box. Place the remaining eight 10% shares in the major company’s treasury. The major company is now operational.

**Comment by dfannius** [comment] 2022-09-07 12:38
@Avemo3 Thanks! Please create one issue per bug in the future - that way it's easier to monitor and update their state independently.

**Comment by outsidePasser** [comment] 2022-09-08 19:14
Duplicate of #8291

**Closed by outsidePasser** 2022-09-08 19:14 UTC
Labels: bug, 1822PNW
