### ISSUE TITLE
[1893] shareholder unable to vote during merger (blocks step w no progression option)

### ISSUE THREAD

**Issue by benjaminxscott** [tobymao/18xx#10311] opened 2024-02-10 18:38 UTC
https://18xx.games/game/149773

https://gist.github.com/benjaminxscott/3de5e4298cf7e6bc05b1686e57d35555

Attempting to float AGV via merge, player `wormjitsu` has 10 votes but is unable to vote on the merger (no UI elements)

**Comment by perwestling** [comment] 2024-02-18 03:19
The cause of this was that the last player did not own any minor, to be merged, but only 10% of AGV. These meant that there was a conflict in the code that resulted in this.

How now fixed so that shares-only also gets to vote.

Games that have encountered this, and which has worked around (ie voted NO to decline) will not break, as the critical point has already been passed. It will fix the issue for future games, and possibly later mergers.

If the players is up for it you could possibly revert all the way to this point, and then get the possibility to change course.
But wait until fix is deplyed.

**Closed** 2024-02-18 19:51 UTC
Labels: bug, 1893
