### ISSUE TITLE
[1870] Game Id 133888 The game is not allowing me to buy a share of Frisco.  The error message is "illegal action, wrong number of arguments (given 2, expected 0)". 

### ISSUE THREAD

**Issue by Rupre** [tobymao/18xx#9718] opened 2023-10-04 03:36 UTC
**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by philcampeau** [comment] 2023-10-04 14:43
duplicate of #9321

**Closed by philcampeau** 2023-10-04 14:43 UTC
Labels: duplicate
