### ISSUE TITLE
1822PNW offered merger without connection

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#8287] opened 2022-09-06 01:40 UTC
https://18xx.games/game/96627?action=533

M8 and M12 are not connected by track

**Comment by outsidePasser** [comment] 2022-09-06 01:47
I believe the change I made this afternoon will fix this when it rolls out.  The game is considering "across the mountain" as "connected".  I will monitor when that change gets rolled out.

**Comment by outsidePasser** [comment] 2022-09-08 19:15
Duplicate of #8293

**Closed by outsidePasser** 2022-09-08 19:15 UTC
Labels: rules-permissive, 1822PNW
