### ISSUE TITLE
[1844] Multiplayer game cannot be continued due to Set: uninitialized constant Engine::SharePool::Set Broken action

### ISSUE THREAD

**Issue by hummus-love** [tobymao/18xx#10517] opened 2024-03-17 13:29 UTC
# Game
https://18xx.games/game/155686?action=47

## Description
We — four people — played asynchronously over the last few days. The last working state was that we were in the first(?) stock round. Today I wanted to check the status but was greeted by the error:

_We're sorry this game cannot be continued due to Set: uninitialized constant Engine::SharePool::Set
Broken action: { "type": "pass", "entity": 16431, "entity_type": "player", "id": 48, "created_at": 1710346861 }
Please [raise a bug report](https://github.com/tobymao/18xx/issues?q=is%3Aissue+is%3Aopen+label%3A1844,%22needs%20triage%22) and include this link (https://18xx.games/game/155686?action=47)_

## Browsers (I know of)
- Firefox on macOS, Linux
- Safari on iOS
- Samsung Internet on Android

**Comment by ollybh** [comment] 2024-03-17 13:37
Duplicate of #10484.

**Closed by ollybh** 2024-03-17 13:37 UTC
Labels: needs triage
