### ISSUE TITLE
[Harzbahn 1873] Game doesn't load anymore

### ISSUE THREAD

**Issue by KlausKiermeier** [tobymao/18xx#6862] opened 2022-01-28 21:39 UTC
**What's your Game ID?**

https://18xx.games/game/68415

This game doesn't load anymore.

**Which Browser / Platform?**

Chrome (Mobile)
and
Firefox (Desktop)

**Comment by beorn7** [comment] 2022-01-28 21:43
Duplicate of #6861 :o)

**Closed** 2022-01-28 21:49 UTC
Labels: needs triage
