### ISSUE TITLE
[1849] Game Corrupted

### ISSUE THREAD

**Issue by TheCostcutter** [tobymao/18xx#4575] opened 2021-03-18 09:47 UTC
https://18xx.games/game/31898

Game hung up on token laying step. Can't access to get further information (sorry!)

**Comment by Zwergenpunk** [comment] 2021-03-18 11:59
Seems like a duplicate of #4574

**Comment by TheCostcutter** [comment] 2021-03-18 12:56
Indeed. Thanks for the assist on thread title too!!

**Comment by michaeljb** [comment] 2021-03-18 13:48
fixed by c604519

**Closed by michaeljb** 2021-03-18 13:48 UTC
Labels: 1849, bug
