### ISSUE TITLE
22mx bug 

### ISSUE THREAD

**Issue by fsaglio** [tobymao/18xx#7720] opened 2022-05-10 02:15 UTC
Game 83495.   Game gets hung up if minor 11 upgrades it’s L to a 2.   

If I flip the L, I get the attached error message when hitting the “done(trains) button. 

> `
![4883050E-6331-4F6E-9BBA-3E72EBFD4012](https://user-images.githubusercontent.com/69740145/167528642-470eb958-51a6-49e2-b6b5-4c8d8fb03f9a.png)
`

**Comment by outsidePasser** [comment] 2022-05-10 02:38
I am not able to recreate this problem either in a cloned game or when creating a new one with this file on my system.  Continuing to investigate.

**Comment by outsidePasser** [comment] 2022-05-11 17:35
This problem does not seem to be re-creatable.  It's possible other bug fixes addressed this problem as well.  Keeping it open for now just in case it crops up again.

**Comment by outsidePasser** [comment] 2022-05-17 01:54
Looking more closely, this is a duplicate of a previous problem.

Dup of #7728

**Comment by dfannius** [comment] 2022-05-22 12:17
Closing as duplicate.

**Closed by dfannius** 2022-05-22 12:17 UTC
Labels: duplicate, 1822MX
