### ISSUE TITLE
[TOP 1871, possibly other titles] Incorrectly assumes player owns $5 less than actual amount when buying train, odd bug

### ISSUE THREAD

**Issue by luigicoolGH** [tobymao/18xx#7639] opened 2022-04-17 22:47 UTC
https://18xx.games/game/79160

Very odd bug.  If does not show up when cloning the game.  Timestamp [14:42].  If the player sells one share of MS and then tries to buy the train, the following error occurs:

"The server did not accept this action due to: Illegal action: VoldyLox has 328 and cannot spend 330... refreshing."

The screen reboots and rolls back to the before the action

The player actually has 333 at that point, but the game thinks the player has 5 dollars less than in reality.  This bug only occurs with that particular scenario, did not occur when selling other shares (perhaps because other sales result in player having more than $5 above purchase price)

**Comment by dfannius** [comment] 2022-06-22 00:32
Duplicate of #7847.

**Closed by dfannius** 2022-06-22 00:32 UTC
Labels: bug, 1871
