### ISSUE TITLE
1882 Reflect Neutral Tokens in Spreadsheet

### ISSUE THREAD

**Issue by Jonbone67** [tobymao/18xx#2502] opened 2020-11-30 18:06 UTC
Please describe your idea and why we should consider it.
The spreadsheet only shows company tokens (available/total) but not neutral ones that companies haven't used yet.  Since CN relies on neutral tokens it would helpful to see this information in the spreadsheet view without having to go to the entities view. Thanks.

**Comment by dfannius** [comment] 2020-11-30 18:11
Duplicate of #1332.

**Closed by dfannius** 2020-11-30 18:11 UTC
Labels: enhancement
