### ISSUE TITLE
[18NewEngland] it doesn’t permit a merge

### ISSUE THREAD

**Issue by queroscia** [tobymao/18xx#6813] opened 2022-01-18 20:40 UTC
Game: https://18xx.games/game/67962

I want to merge the HNH and NLN companies. They are unconnected, but in the same hex. According with the rules, the merge can be done. However, the program doesn’t permit to me do it.

**Comment by benjaminxscott** [comment] 2022-01-18 23:12
dupe of #6811

**Closed by benjaminxscott** 2022-01-18 23:12 UTC
Labels: needs triage
