### ISSUE TITLE
[1847AE] Double share/presidency disappeared after changing presidency

### ISSUE THREAD

**Issue by m4rt1n2d** [tobymao/18xx#9752] opened 2023-10-11 01:17 UTC
SAAR was dumped in the beginning of SR10 onto the double share holder.  When this happened, the presidency or the double share disappeared.  

https://18xx.games/game/137498

**Comment by Galatolol** [comment] 2023-10-25 20:13
I'm not able to reproduce this issue. Maybe it has been solved by one of my other fixes. Let me know if this happens again.

**Comment by ollybh** [comment] 2023-12-26 17:40
Two months since @Galatolol said they couldn't reproduce this and no reports of the bug happening again, so closing this issue.

**Closed by ollybh** 2023-12-26 17:40 UTC
Labels: cant_reproduce, 1847AE
