### ISSUE TITLE
We're sorry this game cannot be continued

### ISSUE THREAD

**Issue by miltad** [tobymao/18xx#10497] opened 2024-03-17 07:59 UTC
We're sorry this game cannot be continued due to Set: uninitialized constant Engine::SharePool::Set
Broken action: { "type": "par", "entity": 14134, "entity_type": "player", "id": 68, "created_at": 1708952438, "corporation": "HBE", "share_price": "120,0,5" }
Please [raise a bug report](https://github.com/tobymao/18xx/issues?q=is%3Aissue+is%3Aopen+label%3A1873,%22needs%20triage%22) and include this link (https://18xx.games/game/153710?action=67)

**Comment by ollybh** [comment] 2024-03-17 10:52
Duplicate of #10484.

**Closed by ollybh** 2024-03-17 10:52 UTC
Labels: needs triage
