### ISSUE TITLE
[1822 Africa] Cannot pass

### ISSUE THREAD

**Issue by Kirasjer87** [tobymao/18xx#9606] opened 2023-09-14 08:39 UTC
**What's your Game ID?**

Game id 134262

**How to Reproduce the Bug?**

During current SR (2.2) I cannot pass turn.

**Which Browser / Platform?**

Desktop, Chrome

**Comment by michaeljb** [comment] 2023-09-14 13:39
Sounds like a duplicate of #9603

**Closed by michaeljb** 2023-09-14 13:39 UTC
Labels: needs triage
