### ISSUE TITLE
corporation bought train from itself - 1856 #65286

### ISSUE THREAD

**Issue by mb1898** [tobymao/18xx#6707] opened 2022-01-04 07:15 UTC
https://18xx.games/game/65286

https://18xx.games/game/65286?action=734
to 
https://18xx.games/game/65286?action=737

Please have a look at the lines TGB buys a 5 train for 1$ from TGB:

[22:20]Trigo operates TGB
[22:20]TGB places a token on K8
[22:50]TGB lays tile #6 with rotation 1 on K8 (Orangeville)
[22:50]TGB skips place a token
[22:50]TGB skips run routes
[22:50]TGB does not run
[22:50]TGB's share price changes from $100 to $90
[22:52]TGB buys a 5 train for $1 from WGB
[22:52]TGB owes no interest
[22:52]TGB buys a 5 train for $1 from TGB
[22:52]TGB buys a 5 train for $1 from TGB
[22:52]TGB buys a 5 train for $1 from TGB
[22:52]TGB buys a 5 train for $1 from TGB
[22:53]TGB exchanges a 5 for a D train for $750 from The Depot
[22:53]TGB buys a tunnel token from the bank for $50
[22:53]TGB passes buy trains
[22:53]TGB skips buy companies
[22:53]-- Operating Round 7.2 (of 3) --

**Comment by tobymao** [comment] 2022-01-04 07:33
please link the action id

**Comment by mb1898** [comment] 2022-01-04 07:43
See original comment

**Comment by scottredracecar** [comment] 2022-02-03 18:31
I see the log entries, but how can this be reproduced? Closing for now, but please reopen if necessary.

**Closed by scottredracecar** 2022-02-03 18:31 UTC
Labels: 1856, needs triage

**Comment by ventusignis** [comment] 2022-06-12 01:09
For future reference:
Here are the actions from that period - note that it's a buy-train for the same train over and over. The game was likely being slow at the time and the current player probably clicked buy train several times and the server ended up processing all of them before the page could update, which led to the TGB buying the train from the WGB for $1, then buying it from itself for $1, then that same train from itself for $1, and so on. For the following train buys, since the money ended up where it came from there was no harm, but a check to make sure that a company cannot buy a train from itself would prevent this from happening again
```
    {
      "type": "buy_train",
      "entity": "TGB",
      "entity_type": "corporation",
      "id": 733,
      "created_at": 1641160350,
      "train": "5-1",
      "price": 1
    },
    {
      "type": "buy_train",
      "entity": "TGB",
      "entity_type": "corporation",
      "id": 734,
      "created_at": 1641160350,
      "train": "5-1",
      "price": 1
    },
    {
      "type": "buy_train",
      "entity": "TGB",
      "entity_type": "corporation",
      "id": 735,
      "created_at": 1641160351,
      "train": "5-1",
      "price": 1
    },
    {
      "type": "buy_train",
      "entity": "TGB",
      "entity_type": "corporation",
      "id": 736,
      "created_at": 1641160351,
      "train": "5-1",
      "price": 1
    },
    {
      "type": "buy_train",
      "entity": "TGB",
      "entity_type": "corporation",
      "id": 737,
      "created_at": 1641160351,
      "train": "5-1",
      "price": 1
    },
```
