### ISSUE TITLE
[18MS] Train discount from Mobile & Ohio Railway not being applied

### ISSUE THREAD

**Issue by Ticketautomat1** [tobymao/18xx#9649] opened 2023-09-20 19:12 UTC
https://18xx.games/game/135152?action=117

The private "Mobile & Ohio Railway" does not work. Am I doing something wrong? From my understanding I the discount of 100 bucks should apply now?

**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by benjaminxscott** [comment] 2023-09-22 22:53
I looked into this a bit, we override `process_buy_train` in a custom 18MS step, which may be related

For some reason, at the `render()` step, `@selected_company` is Nil when it's selected

Compare with [this 1848 game](https://gist.github.com/benjaminxscott/ef8925b4e810efd04c12e7cce61b2377) where the Ghan discount is correctly applied when the private is selected, and `@selected_company` is the expected company object

https://github.com/tobymao/18xx/blob/f2da040af80e979726e7d3203d3cc92ac3c4d258/assets/app/view/game/buy_trains.rb#L184

**Comment by OedipussyRex** [comment] 2023-12-04 08:37
Commenting to +1 and receive notifications.

**Comment by michaeljb** [comment] 2024-01-07 22:52
Duplicate of #9192. The change made in #10098 may be applicable.

**Closed by michaeljb** 2024-01-07 22:52 UTC
Labels: bug, 18MS
