### ISSUE TITLE
Don't suggest invalid routes when valid ones exist

### ISSUE THREAD

**Issue by dfannius** [tobymao/18xx#1125] opened 2020-07-20 14:09 UTC
Game 1306, OR7.1 (it's an old game but I don't think it is pinned)

As SRR, I started my route by clicking on Ohio, then Green Spring, then Washington DC, then Strasburg. There are two paths from DC to Strasburg, but one of them would reuse existing track and one wouldn't. The site gave me the former illegal path by default. Of course I could click again to get the legal one, but it would be nice for illegal ones to be filtered out if some other ones are legal.

**Comment by roseundy** [comment] 2020-10-02 22:21
I _almost_ had this implemented at one point, as part of supporting parallel paths. Unfortunately, it didn't work as intended. I'll see how hard it would be to do it correctly.

**Comment by roseundy** [comment] 2020-10-03 00:12
I have this fixed in my fork, but because it is a UI feature, I need to be extra careful in testing this.

**Closed** 2020-10-12 16:08 UTC
Labels: enhancement
