### ISSUE TITLE
[1822CA] Game Won't Let Major Lay Second Yellow Track

### ISSUE THREAD

**Issue by fanman80** [tobymao/18xx#10956] opened 2024-06-23 21:55 UTC
Game ID  164866

https://18xx.games/game/164866

ICR was floated in SR 10.  In its operation in OR 10.1 "ICR lays tile #8 with rotation 0 on AP2" just fine, but for each of the several attempts (more than 5) to lay a second yellow tile, the server takes a long time to "accept" the move to advance to the token placement phase.  The wait time between clicking the green check mark to commit the second tile lay to advancing to token placement was so long that two page unresponsive messages offering to close the application or wait for it to respond appeared.  After each of the several times after each of the times the game did move beyond this point to letting the ICR place a token, buy a train, redeem a share, and appear to start the turn of the next RR, red messages were given that updates were not accepted due to refreshing and something like " can't process move 1590".

Here's a screen shot of the attempted tile lay:

![image](https://github.com/tobymao/18xx/assets/70117294/3c31b887-8884-443b-b46d-d34c0f2633bf)

I didn't seem to experience any trouble in other games taking turns immediately before or after this trouble.  I had taken turns in at least two games immediately before this problem.  I made several attempts in this game as described above.  I started this bug report and copied it into a document.  I closed and reopened my browser.  I made more attempts as described above.  I took turns in other games with no apparent problems.  I rebooted my computer, and I continued to have this problem.

**Comment by fanman80** [comment] 2024-06-23 22:07
I even tried clicking the "Done Track" button.  Got the same behavior.  Is the game "hung"?

**Comment by michaeljb** [comment] 2024-06-24 00:26
Part of the problem is that the search is starting from the destination token, rather than from the home token. This is how the original 1822 developer decided to do it, and I'd guess that was because the destination location in general is less likely to have track built up around it compared to a home location; that is definitely not the situation for ICR here, with its late start and isolated home city. I'm not going to change that piece right now as the effects it would have on computation for the destinating of other companies is unpredictable.

The search starts from the destination token which should only be a few hundred `walk` calls to traverse the map (or 20 if it happened to pick the right direction first), but #10331 is making that much much worse, and it's actually making almost 2 million calls instead of the few hundred it takes to compute ICR's graph.

There is also something in the UI code making it repeat the call 3 times, I should have cached that in the first place but that piece will be easy to fix now. I'll fix that part and then close the issue, as the rest of this is a duplicate of #10331.

```
D, [2024-06-23T18:11:24.787000] DEBUG -- :     Graph#compute(ICR, routes_only: false, one_token: )
D, [2024-06-23T18:11:24.799000] DEBUG -- :     Graph computed with 348 completed walk calls (skipped 117)
D, [2024-06-23T18:11:24.801000] DEBUG -- :     nodes_connected?(<Engine::Part::City: hex: AH8 index: 0>, <Engine::Part::City: hex: AP4 index: 0>, ICR)
D, [2024-06-23T18:11:53.548000] DEBUG -- :         nodes_connected? returned true after 1997677 walk() calls
D, [2024-06-23T18:11:53.549000] DEBUG -- :     nodes_connected?(<Engine::Part::City: hex: AH8 index: 0>, <Engine::Part::City: hex: AP4 index: 0>, ICR)
D, [2024-06-23T18:12:22.298000] DEBUG -- :         nodes_connected? returned true after 1997677 walk() calls
D, [2024-06-23T18:12:22.299000] DEBUG -- :     nodes_connected?(<Engine::Part::City: hex: AH8 index: 0>, <Engine::Part::City: hex: AP4 index: 0>, ICR)
D, [2024-06-23T18:12:51.502000] DEBUG -- :         nodes_connected? returned true after 1997677 walk() calls
```
> After each of the several times after each of the times the game did move beyond this point to letting the ICR place a token, buy a train, redeem a share, and appear to start the turn of the next RR, red messages were given that updates were not accepted due to refreshing and something like " can't process move 1590".

It sounds like the server is timing out and rejecting the action even after your browser accepts it. My fix should help with that, as it should take the server 1/3 the time to process this after I get the caching, but I can't promise it will work before #10331 is fixed.

Thanks for reporting this! I knew there were some real bad performance issues in the endgame, but with this report I was able to find specifically where the problem was--it also certainly helps that I happened to be working on #10331 lately.

**Comment by fanman80** [comment] 2024-06-24 00:40
Thank you.  Glad my report was of help.

**Comment by michaeljb** [comment] 2024-06-24 14:02
Reverted #10957 due to #10960.

**Closed** 2024-06-30 05:42 UTC
Labels: 1822CA, graph
