### ISSUE TITLE
82: NWR private: new issue 

### ISSUE THREAD

**Issue by JacCCMF** [tobymao/18xx#1529] opened 2020-08-26 12:05 UTC
hi in game 7580, 82, the NWR token doesn’t work. i’m able to buy the private in. Then move token. place token. then upgrade. Then the problem occurs: token disappears. i’m able to put it back, but I should be able to not do my normal tile/token. however it won’t let me put the second token in medicine hat.

it’s counting my NWR move as my token laying for my turn. 

This is a bug right?

* Multiplayer yes 

     "type": "undo",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 229
    },
    {
      "type": "undo",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 230
    },
    {
      "type": "undo",
      "entity": "NWR",
      "entity_type": "company",
      "id": 231
    },
    {
      "type": "place_token",
      "entity": "NWR",
      "entity_type": "company",
      "id": 232,
      "city": "E5-0-0",
      "slot": 0
    },
    {
      "type": "lay_tile",
      "entity": "NWR",
      "entity_type": "company",
      "id": 233,
      "hex": "E5",
      "tile": "59-0",
      "rotation": 0
    },
    {
      "type": "place_token",
      "entity": "GT",
      "entity_type": "corporation",
      "id": 234,
      "city": "59-0-0",
      "slot": 0

**Comment by jenf** [comment] 2020-08-26 12:15
Can't reproduce,

Need a game in the state where it's skipped token step.

**Comment by jenf** [comment] 2020-08-27 19:46
Gonna close this, but if you can reproduce reopen.

**Closed by jenf** 2020-08-27 19:46 UTC
Labels: 1882, question
