### ISSUE TITLE
1822Africa Gold Mine bug

### ISSUE THREAD

**Issue by MatthewDeKoning** [tobymao/18xx#10099] opened 2024-01-05 17:34 UTC
Gold mine private company, used by CAR OR 6.1, removes NAR destination token, replaces it with a free CAR token. 
**What's your Game ID?**

https://18xx.games/game/146845?action=677

<
**Which Browser / Platform?**
Safari on iOS, though not sure what CAR player was using.

**Comment by benjaminxscott** [comment] 2024-01-05 20:42
dupe of #10094

**Closed by benjaminxscott** 2024-01-05 20:42 UTC
Labels: needs triage
