### ISSUE TITLE
[1822] Shares must be sold before a loan is taken

### ISSUE THREAD

**Issue by JaySixA** [tobymao/18xx#10114] opened 2024-01-09 16:31 UTC
This game has been stuck for a while.  Here is the message we received:

We're sorry this game cannot be continued due to GameError: Guido65 still need to sell shares before a loan can be granted
Broken action: { "type": "buy_train", "entity": "7", "entity_type": "corporation", "id": 491, "created_at": 1703224232, "train": "3-5", "price": 200, "variant": "3" }
Please [raise a bug report](https://github.com/tobymao/18xx/issues?q=is%3Aissue+is%3Aopen+label%3A1822,%22needs%20triage%22) and include this link (https://18xx.games/game/142948?action=490)

**Comment by benjaminxscott** [comment] 2024-01-09 19:39
direct dupe #10097 , caused by #10059

The broader fix for this bug seems to be in progress, not to speak for anyone but it's self-assigned to someone

**Closed by benjaminxscott** 2024-01-09 19:39 UTC
Labels: needs triage
