### ISSUE TITLE
https://18xx.games/game/151675?action=11

### ISSUE THREAD

**Issue by romagnarail** [tobymao/18xx#10510] opened 2024-03-17 11:47 UTC
I'm having trouble logging in to the games I'm signed up for in 18xx.games.

My user name is Romagnarail

I see this writing: We're sorry this game cannot be continued due to Set: uninitialized constant Engine::SharePool::Set
Broken action: { "type": "par", "entity": 11522, "entity_type": "player", "id": 12, "created_at": 1707262724, "corporation": "LPS", "share_price": "65,5,4" }
Please [raise a bug report](https://github.com/tobymao/18xx/issues?q=is%3Aissue+is%3Aopen+label%3A1856,%22needs%20triage%22) and include this link (https://18xx.games/game/151675?action=11)

Can you help me ?

**Comment by ollybh** [comment] 2024-03-17 12:19
Duplicate of #10484.

**Closed** 2024-03-17 12:20 UTC
Labels: needs triage
