### ISSUE TITLE
[1828] - Auto Routing allows route to coal mines without coal token.

### ISSUE THREAD

**Issue by H1llsman** [tobymao/18xx#7416] opened 2022-03-08 22:16 UTC
**What's your Game ID?**

https://18xx.games/game/71506?action=1103

**How to Reproduce the Bug?**

What steps cause the unexpected behavior?

When I hit auto route B&O's Diesel is routed as following:
K11-I11-H12-F20-G21-G23-H22-I23-I19-H20-H22-G21 for $430

![image](https://user-images.githubusercontent.com/85963784/157334124-b46eea16-73a9-4afe-9cd4-ba4c75e12532.png)

B&O does not have a coal token and should not be allowed to route there, per rule 16.1, last point:
A share company that does not own a coal marker cannot:
- Have one of its train routes end at or pass through the Virginia Coalfields (K11) (see section 15.2)

**Which Browser / Platform?**
- Browser Version
Firefox v97 - on desktop

**Comment by dfannius** [comment] 2022-03-08 22:22
Thank you for the report, but this is a duplicate of #6365.

**Closed by dfannius** 2022-03-08 22:22 UTC
Labels: duplicate
