### ISSUE TITLE
Clicking a hex in route-building scrolls page up

### ISSUE THREAD

**Issue by gchambers419** [tobymao/18xx#167] opened 2020-04-26 14:30 UTC
From Slack:
toby

people on BGG are saying that the phone scrolls up every time you click on a hex for a route
does that happen for anyone here and what kind of phone do you have

James  10:38 PM
Samsung Galaxy Note 10, never saw that problem

Glenn Chambers
Scrolling issue for route creation happens in chrome browser on Chromebooks as well.  It didn't happen in the top row(s) of hexes.

**Comment by gchambers419** [comment] 2020-04-26 16:54
{
  "status": "active",
  "actions": [
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 1,
      "company": "Mitsubishi Ferry",
      "price": 35
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 2,
      "company": "Ehime Railway",
      "price": 45
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 3,
      "company": "Sumitomo Mines Railway",
      "price": 55
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 4,
      "company": "South Iyo Railway",
      "price": 85
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 5,
      "company": "Dougo Railway",
      "price": 65
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 6,
      "company": "Mitsubishi Ferry",
      "price": 40
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 7,
      "company": "Mitsubishi Ferry",
      "price": 45
    },
    {
      "type": "bid",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 8,
      "company": "Takamatsu E-Railroad",
      "price": 20
    },
    {
      "type": "bid",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 9,
      "company": "Mitsubishi Ferry",
      "price": 50
    },
    {
      "type": "bid",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 10,
      "company": "Mitsubishi Ferry",
      "price": 55
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 11
    },
    {
      "type": "par",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 12,
      "corporation": "TR",
      "share_price": "80,2,3"
    },
    {
      "type": "par",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 13,
      "corporation": "UR",
      "share_price": "70,4,3"
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 14,
      "corporation": "KO",
      "share_price": "75,3,3"
    },
    {
      "type": "par",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 15,
      "corporation": "SR",
      "share_price": "100,0,3"
    },
    {
      "type": "par",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 16,
      "corporation": "IR",
      "share_price": "70,4,3"
    },
    {
      "type": "par",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 17,
      "corporation": "AR",
      "share_price": "70,4,3"
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 18
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 19
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 20
    },
    {
      "type": "buy_share",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 21,
      "share": "UR_1"
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 22
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 23,
      "share": "AR_1"
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 24
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 25
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 26
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 27
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 28
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 29
    },
    {
      "type": "buy_share",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 30,
      "share": "TR_1"
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 31
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 32
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 33,
      "share": "KO_1"
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 34
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 35
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 36
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 37
    },
    {
      "type": "sell_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 38,
      "shares": [
        "TR_1"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 39
    },
    {
      "type": "buy_share",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 40,
      "share": "UR_2"
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 41
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 42
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 43
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 44
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 45
    },
    {
      "type": "buy_share",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 46,
      "share": "TR_2"
    },
    {
      "type": "sell_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 47,
      "shares": [
        "TR_2"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 48
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 49
    },
    {
      "type": "buy_share",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 50,
      "share": "SR_1"
    },
    {
      "type": "sell_shares",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 51,
      "shares": [
        "SR_1"
      ],
      "percent": 10
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 52
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 53
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 54
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 55
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 56,
      "share": "KO_2"
    },
    {
      "type": "sell_shares",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 57,
      "shares": [
        "KO_1",
        "KO_2"
      ],
      "percent": 20
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 58
    },
    {
      "type": "buy_share",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 59,
      "share": "TR_3"
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 60
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 61
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 62
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 63
    },
    {
      "type": "lay_tile",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 64,
      "hex": "G10",
      "tile": "58-0",
      "rotation": 0
    },
    {
      "type": "buy_train",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 65,
      "train": "2-0",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 66
    },
    {
      "type": "buy_share",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 67,
      "share": "UR_3"
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 68
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 69,
      "share": "AR_2"
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 70
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 71
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 72
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 73,
      "share": "AR_3"
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 74
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 75
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 76
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 77
    },
    {
      "type": "lay_tile",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 78,
      "hex": "B5",
      "tile": "9-0",
      "rotation": 3
    },
    {
      "type": "pass",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 79
    },
    {
      "type": "buy_train",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 80,
      "train": "2-1",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 81
    },
    {
      "type": "lay_tile",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 82,
      "hex": "K8",
      "tile": "6-0",
      "rotation": 2
    },
    {
      "type": "buy_train",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 83,
      "train": "2-2",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 84
    },
    {
      "type": "lay_tile",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 85,
      "hex": "G12",
      "tile": "57-0",
      "rotation": 3
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 86
    },
    {
      "type": "run_routes",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 87,
      "routes": [
        {
          "train": "2-0",
          "hexes": [
            "F9",
            "G10"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 88,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 89,
      "train": "2-3",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 90
    },
    {
      "type": "buy_share",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 91,
      "share": "TR_4"
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 92
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 93
    },
    {
      "type": "buy_share",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 94,
      "share": "KO_3"
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 95
    },
    {
      "type": "pass",
      "entity": "Player 3",
      "entity_type": "player",
      "id": 96
    },
    {
      "type": "pass",
      "entity": "Player 1",
      "entity_type": "player",
      "id": 97
    },
    {
      "type": "pass",
      "entity": "Player 2",
      "entity_type": "player",
      "id": 98
    },
    {
      "type": "lay_tile",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 99,
      "hex": "H13",
      "tile": "9-1",
      "rotation": 1
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 100
    },
    {
      "type": "run_routes",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 101,
      "routes": [
        {
          "train": "2-0",
          "hexes": [
            "F9",
            "G10"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 102,
      "kind": "payout"
    },
    {
      "type": "pass",
      "entity": "TR",
      "entity_type": "corporation",
      "id": 103
    },
    {
      "type": "lay_tile",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 104,
      "hex": "J3",
      "tile": "8-0",
      "rotation": 5
    },
    {
      "type": "buy_train",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 105,
      "train": "2-4",
      "price": 80
    },
    {
      "type": "buy_train",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 106,
      "train": "2-5",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "KO",
      "entity_type": "corporation",
      "id": 107
    },
    {
      "type": "lay_tile",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 108,
      "hex": "A8",
      "tile": "8-1",
      "rotation": 0
    },
    {
      "type": "pass",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 109
    },
    {
      "type": "run_routes",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 110,
      "routes": [
        {
          "train": "2-1",
          "hexes": [
            "B7",
            "B5",
            "B3"
          ]
        }
      ]
    },
    {
      "type": "dividend",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 111,
      "kind": "payout"
    },
    {
      "type": "buy_train",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 112,
      "train": "3-0",
      "price": 180
    },
    {
      "type": "pass",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 113
    },
    {
      "type": "buy_company",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 114,
      "company": "Ehime Railway",
      "price": 80
    },
    {
      "type": "pass",
      "entity": "UR",
      "entity_type": "corporation",
      "id": 115
    },
    {
      "type": "lay_tile",
      "entity": "Ehime Railway",
      "entity_type": "company",
      "id": 116,
      "hex": "C4",
      "tile": "15-0",
      "rotation": 5
    },
    {
      "type": "lay_tile",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 117,
      "hex": "K8",
      "tile": "15-1",
      "rotation": 1
    },
    {
      "type": "run_routes",
      "entity": "AR",
      "entity_type": "corporation",
      "id": 118,
      "routes": [
        {
          "train": "2-2",
          "hexes": [
            "K8",
            "L7"
          ]
        }
      ]
    }
  ],
  "players": [
    {
      "name": "Player 1"
    },
    {
      "name": "Player 2"
    },
    {
      "name": "Player 3"
    }
  ],
  "title": "1889",
  "description": "glennfirefox",
  "max_players": "6",
  "id": "hs_1587917409",
  "mode": "hotseat",
  "user": {
    "id": 0,
    "name": "You"
  },
  "created_at": "2020-04-26"
}

**Comment by gchambers419** [comment] 2020-04-26 16:57
BUG triggered during the build route action at the end. Did not happen in previous route-building

**Comment by gchambers419** [comment] 2020-04-26 23:46
I've seen this multiple places now.  In a hotseat game, reloading the page cleans it up.

**Comment by rajgiriUW** [comment] 2020-04-27 05:20
I've tried a few times in a hotseat game and I think I can reproduce this effect. This effect occurs if you switch screens in the middle of resolving an action that involves clicking on the map. Refreshing eliminates it.

e.g. 
In Game, click a hex to lay a track (don't confirm it yet)
click on Companies
click on Game
click on the hex to reorient or anything and it will scroll to the top.

This occurs in track-laying and/or routing or placing a token. I assume it will auto-scroll in any action that involves clicking a hex.

**Comment by tobymao** [comment] 2020-04-27 05:32
Thank you so much. This is because there's a hash tag in the URL. easy fix

**Closed** 2020-04-27 05:43 UTC
