### ISSUE TITLE
[1822PNW] Shares must be sold before loan granted.

### ISSUE THREAD

**Issue by JaySixA** [tobymao/18xx#10113] opened 2024-01-09 16:29 UTC
This game has been stuck for a while.  Here is what we are being told:

We're sorry this game cannot be continued due to GameError: dfwinfinitejest (utc-8) still need to sell shares before a loan can be granted
Broken action: { "type": "buy_train", "entity": "20", "entity_type": "corporation", "id": 725, "created_at": 1702567450, "train": "3-0", "price": 200, "variant": "3" }
Please [raise a bug report](https://github.com/tobymao/18xx/issues?q=is%3Aissue+is%3Aopen+label%3A1822PNW,%22needs%20triage%22) and include this link (https://18xx.games/game/143212?action=724)

**Comment by benjaminxscott** [comment] 2024-01-09 19:39
dupe caused by #10059

The broader fix for this bug seems to be in progress, not to speak for anyone but it's self-assigned to someone

**Closed by benjaminxscott** 2024-01-09 19:39 UTC
Labels: needs triage
