### ISSUE TITLE
[1822PNW] Floating a major should not slide minors to the next available bid box

### ISSUE THREAD

**Issue by spenczar** [tobymao/18xx#10609] opened 2024-04-06 06:38 UTC
**What's your Game ID?**

https://gist.github.com/spenczar/e666b560df79803e3bc2ba8971f4c37a

**How to Reproduce the Bug?**

First, note that the minor in bid box 1 is 17, which is associated with the SPS major. We're in phase 5, so the major can be floated directly. Regional C is in bid box 2.

![image](https://github.com/tobymao/18xx/assets/880413/3e26ebe5-2d02-4f84-8ac5-a7f88be80f9d)

Float SPS.
![image](https://github.com/tobymao/18xx/assets/880413/8be48f28-8009-4f42-abb2-0e9acb940725)

Now, observe that Regional C has moved into bid box 1, inappropriately.
![image](https://github.com/tobymao/18xx/assets/880413/21a9e1ff-38b1-482b-bd5e-c2c5cd446eaf)

As a result, if Regional C receives no bids, it will be removed from the game and a train will be exported - incorrectly. It should have remained in bid box 2.

Rule 4.7.3, step 2 is explicit about this - bid box filling should only be at the end of the round:

> Once a the president’s certificate is procured, the associated minor company’s certificate is immediately removed from the
game. If it was removed from a bid box, the bid box is filled at the end of the stock round following the normal procedure.

**Which Browser / Platform?**

Any

**Comment by michaeljb** [comment] 2024-06-02 22:05
Thanks for reporting this and providing screenshots! I'm working a fix now.

Duplicate of #10525

**Closed by michaeljb** 2024-06-02 22:05 UTC
Labels: needs triage
