### ISSUE TITLE
[1846] We're sorry this game cannot be continued due to Set: uninitialized constant Engine::SharePool::Set

### ISSUE THREAD

**Issue by tonicebrian** [tobymao/18xx#10488] opened 2024-03-17 07:19 UTC
We got this error when playing the game

```
We're sorry this game cannot be continued due to Set: uninitialized constant Engine::SharePool::Set
Broken action: { "type": "par", "entity": 14847, "entity_type": "player", "id": 17, "created_at": 1710433237, "corporation": "B&O", "share_price": "100,0,10" }
Please [raise a bug report](https://github.com/tobymao/18xx/issues?q=is%3Aissue+is%3Aopen+label%3A1846,%22needs%20triage%22) and include this link (https://18xx.games/game/156443?action=16)
```
And the chat looks like we are in the first stock round while we were already running or1

**Comment by ollybh** [comment] 2024-03-17 10:49
Duplicate of #10484.

**Closed by ollybh** 2024-03-17 10:49 UTC
Labels: needs triage
