### ISSUE TITLE
[18WO] Game cannot be continued

### ISSUE THREAD

**Issue by barattie** [tobymao/18xx#10499] opened 2024-03-17 08:15 UTC
**What's your Game ID?** 150489

Link: https://18xx.games/game/150489?action=43

**How to Reproduce the Bug?**

**Which Browser / Platform?** Safari on MacOS Ventura

**Comment by ollybh** [comment] 2024-03-17 10:53
Duplicate of #10484.

**Closed by ollybh** 2024-03-17 10:53 UTC
Labels: needs triage
