### ISSUE TITLE
[1822] Tax haven bug after you view Entities or Game screen

### ISSUE THREAD

**Issue by waaayback** [tobymao/18xx#11107] opened 2024-08-07 14:33 UTC
There seems to be a weird bug related to the Tax Haven, depending on the order of screens viewed.  I think something got broken after the recent bug fixes in this area.

See this current game:
(https://18xx.games/game/167967?action=1318)  and go to the Spreadsheet tab.

Note the total player values, L to R:
3926, 5712, 1123, 4680, 4955.  These are correct. NY_NAFO owns the tax haven (value $604).

Now click to the Entities tab, and then click back to the Spreadsheet tab. 
**The player values (other than the TH owner) have changed - and the difference is the value of the Tax Haven!!**
3322 (-604), 5108 (-604), 519 (-604), 4076 (-604), 4955 (OK - he owns it).

The only way to recover the correct values seems to be to refresh the page in the browser.

**Comment by waaayback** [comment] 2024-08-07 14:43
One more thing...  

The numbers I referenced above are on the Spreadsheet tab.   Turns out there's a *different* set of wrong numbers on the Entities tab. If you go back to the Entities tab after clicking through above, the total values are correct EXCEPT for user 1mmm (incorrectly showing 3322 instead of 3926).

**Comment by waaayback** [comment] 2024-08-07 15:10
The bug also happens if you view the Game screen (instead of the Entities screen) and then return to the Spreadsheet.

Updated title accordingly.

**Comment by kepakiano** [comment] 2024-08-08 16:14
Probably the same as this: https://github.com/tobymao/18xx/issues/11040

**Comment by waaayback** [comment] 2024-08-08 21:01
Quite possibly the same bug as 11040, but just to be clear, that bug only reported a difference for one player.

I am seeing a difference across all players.

**Comment by cwebblax** [comment] 2024-08-10 14:43
I just noticed it today too. The values of players on the entities page don't match with the final score or what is on the spreadsheet, except for me.

**Comment by philcampeau** [comment] 2024-08-21 03:42
Duplicate of #11040

**Closed by philcampeau** 2024-08-21 03:42 UTC
Labels: bug, 1822, 1822CA
