### ISSUE TITLE
1849 2 bugs observed

### ISSUE THREAD

**Issue by pzieske** [tobymao/18xx#8383] opened 2022-09-26 03:48 UTC
1849 Game, Id: 98215
Description: Sicily 19Sept
https://18xx.games/game/98215
(1) The RCS has track to St Stefano (C9).  I wanted to play a tile east of there (D10), but the hex was not highlighted for the RCS to use.  Ditto for the CTL.  Hex E9 is also not available to play on but it should be.
(2) The RCS stock price was at 240 (row 2), just left of the blue area.  It paid a dividend of 260, so was eligible to move right.  However, phase 16H had not started yet, so the price should have moved up instead of right.  The game did not move the token and left it at 240.  Section 5 of the rules indicates what happens when at the "edge" of the market:
"Stock market tokens may not enter the blue “Phase 16 Only” section until the game reaches Phase 16. Before Phase 16 treat this section as the right edge of the market."
"If the token needs to move left or right, but cannot because it is at the edge of the market, it moves up or down as indicated by the arrows."

**Comment by dfannius** [comment] 2022-09-26 10:40
(1) This behavior is correct; the connection from D8 to C9 changes gauge, making it an invalid route.
(2) is a duplicate of #8253.

**Closed** 2022-09-26 10:41 UTC
Labels: bug, 1849, needs triage
