### ISSUE TITLE
1830 - Cosmetic - ISR Title Line Misleading

### ISSUE THREAD

**Issue by rheretic** [tobymao/18xx#3820] opened 2021-02-12 21:39 UTC
> (Top of screen)
> [HOTSEAT] 1830: Phase 2 - Stock Round 1 - Sell/Buy/Sell Shares

As shown this implies that you can Sell, or Buy then Sell a share.  However, since this is the ISR (SR1), that is not really allowed.

Maybe something like:
> [HOTSEAT] 1830(Sell/Buy/Sell): Phase 2 - Stock Round 1 - Buy Shares Only

> [HOTSEAT] 1830(Sell/Buy/Sell): Phase 2 - Stock Round 2 - Sell/Buy/Sell Shares
-or-
> [HOTSEAT] 1830(Sell/Buy/Sell): Phase 2 - Stock Round 2

**Comment by dfannius** [comment] 2021-02-12 21:47
Duplicate of #3794.

**Closed by dfannius** 2021-02-12 21:47 UTC
