### ISSUE TITLE
[1822MX] Not Able to Use P8 with P13 Per Rule 4.1.15

### ISSUE THREAD

**Issue by fanman80** [tobymao/18xx#8183] opened 2022-08-13 19:07 UTC
Game ID: 92154

Game link: https://18xx.games/game/92154

Rule 4.1.15 states: The powers of private company P12 or P13 (remove town) and private company P8 (advanced track lay) can be used together as part of the same track tile placement step.

During the game player Pawnpusher won the bids for Concession FNM, privates P8 (advanced track lay), P12 (remove town), and p13 (remove town) among other things.  As president of FNM, Pawnpusher had the FNM acquire privates P8 (advanced track lay), P12 (remove town), and p13 (remove town).

During Phases 3 and 4, the FNM tried to use P8 & P13 to upgrade tile # 144 (green) on M24 to tile # 546.  However, the game seemed to allow the use of only one private ability at a time.  When the P13 ability was chosen, tile lays of brown tiles were disallowed due to they were for a later phase.  When the P8 ability was chosen, the only tiles that were offered as available had a town.

![image](https://user-images.githubusercontent.com/70117294/184507288-49d98bdd-d1ee-4379-8ba2-087c3fcf7b87.png)

![image](https://user-images.githubusercontent.com/70117294/184507353-4cbdaaae-74b6-4a5b-812a-f0add2cd3716.png)

![image](https://user-images.githubusercontent.com/70117294/184507364-85fa0813-d60c-4cd9-8afb-4d7e62ef71af.png)

![image](https://user-images.githubusercontent.com/70117294/184507339-f6646b09-513a-4569-8647-db51d116a54b.png)

![image](https://user-images.githubusercontent.com/70117294/184507380-91a7375b-74a7-484c-b587-b57b64df2dd9.png)

Pawnpusher was using Brave browser for play.  Pawnpusher has had no issues playing 18xx.games on this browser.

**Comment by crericha** [comment] 2022-08-13 19:38
Duplicate of #4469. We are aware of the issue, but it is very difficult to fix and no one has stepped up to do so yet.

**Closed by crericha** 2022-08-13 19:38 UTC
Labels: needs triage
