### ISSUE TITLE
1844 Bug: destination fee is payed after token phase instead before

### ISSUE THREAD

**Issue by volker18xxdev** [tobymao/18xx#9831] opened 2023-10-26 08:21 UTC
game: https://18xx.games/game/138428/#165
connection is established (see log), but the money is payed to the company after the token-phase.
![grafik](https://github.com/tobymao/18xx/assets/80693707/1fd3e534-f8f8-4869-86f4-8af0e8133ad2)

the german rules said: pay the money immediately to the company:
![grafik](https://github.com/tobymao/18xx/assets/80693707/156d1983-1dd1-4d49-af09-3df1a460f8d6)
(in this case, the nob had enough money for a Token and then could activate the mountain)

    {
      "type": "lay_tile",
      "entity": "NOB",
      "entity_type": "corporation",
      "id": 165,
      "created_at": 1698179978,
      "auto_actions": [
        {
          "type": "destination_connection",
          "entity": "NOB",
          "entity_type": "corporation",
          "created_at": 1698179980,
          "corporations": [
            "NOB"
          ]
        }
      ],
      "hex": "D17",
      "tile": "4-1",
      "rotation": 1
    },

**Comment by ollybh** [comment] 2023-10-28 09:26
Duplicate of #9799.

**Closed by ollybh** 2023-10-28 09:26 UTC
Labels: needs triage
