### ISSUE TITLE
18MS the private company Mobile and Ohio is not giving a discount to train purchases

### ISSUE THREAD

**Issue by leonej15424** [tobymao/18xx#10217] opened 2024-01-28 18:43 UTC
**What's your Game ID?**

**How to Reproduce the Bug?**

**Which Browser / Platform?**

**Comment by leonej15424** [comment] 2024-01-28 18:45
Game ID 150673 The bug is apparent when the company is eligible to purchase a 4 train, but no discount is given.  I am using an IMAC with Safari browser .

**Comment by michaeljb** [comment] 2024-01-28 19:03
Duplicate of #9192

**Closed by michaeljb** 2024-01-28 19:03 UTC
Labels: needs triage
