### ISSUE TITLE
1822: Can't use two privates L&SR (double tile action) and E&GR (mountain) at same time

### ISSUE THREAD

**Issue by waaayback** [tobymao/18xx#4325] opened 2021-03-05 14:42 UTC
https://18xx.games/game/30489?action=521

Here the NER has acquired both privates and is trying to lay a mountain tile as part of the L&SR's double tile action, and pay for it using the E&GR's ability.  

Clicked on L&SR power to lay a second set of yellow tiles. The first tile was 60L mountain. When I clicked on the E&GR power, the L&SR power clicked off, so I could not lay a tile.
Other info: I tried acquiring E&GR with the persistent 20L discount, but that also did not work.

**Comment by magnusfalt** [comment] 2021-03-05 14:50
No using both at the some time i dont think is possible with the currect framework. Ive made so you can lay normal tile lay, use extra tile lay and then use the extra again. So you can mix the 2 just in these cases where you need to use in you example the e&gr on the third tile lay. With this you shouldnt need to use both at the same time.

I took you game and made a hotseat, and undo one move and pressed the £20 and it worked fine for me. What didnt work when you pressed it?

**Comment by waaayback** [comment] 2021-03-05 15:44
I submitted this bug for another player in the game (jjrbedford).  Here's his reply:
_I never noticed any "20L button". It just had the "E&GR" button. When I tried on a separate tile to use the single token aspect, it worked fine. But not on the third lay.
Here are the actual steps I did:
- Laid two normal yellow tiles.
- The third tile I wanted to lay had a 60L mountain.
- Clicked on L&SR to let me lay a third tile
- Clicked on E&GR to discount the tile, but when I did, the L&SR power vanished and thus could not lay the third tile.
- If I lay the tile first, it charged me the full amount_

FWIW I just tried it as well, and I don't see a 20L button either.

**Comment by magnusfalt** [comment] 2021-03-05 15:51
After the aquire step, if you aqcuired the E&GR you will get 2 buttons. One for the discount token and one for the £20 passive discount. If you see the E&GR then the he already have made the choice.

I undertand how you did your steps :) I just saying that if you did it in another order you will be able to do the same things you want to:

- Use L&SR for first tile.
- Use L&SR for second tile.
- Now you still have your normal "track lays" left. Third lay tile.
- Fourth click E&GR and use it to remove the cost of the fourth tile lay.

End result will be what you wanted, just used the abilities in a different order.

**Comment by magnusfalt** [comment] 2021-03-05 15:56
You will see the choose buttons here:

https://18xx.games/game/30489?action=520

**Comment by waaayback** [comment] 2021-03-05 16:08
OK sure, that would work. 

So should this bug remain open?  I'm not sure what you meant above by "using both at the some time i dont think is possible with the current framework", does that mean this bug can't be fixed now?  

This specific case has a workaround, but I don't know if there are other cases that might not have such a solution.  OTOH it's probably not worth it to find a solution with no problem. :)

**Comment by Maxwell-Frank** [comment] 2021-03-05 16:15
The prime test case of this would be trying to use the "advanced tile lay" private to use the "remove small station" private.  I haven't had the opportunity to test this, but I'm not sure if using 2 privates on the same track lay is currently possible or not.

**Comment by magnusfalt** [comment] 2021-03-05 16:28
> The prime test case of this would be trying to use the "advanced tile lay" private to use the "remove small station" private. I haven't had the opportunity to test this, but I'm not sure if using 2 privates on the same track lay is currently possible or not.

What i can read from the rules you can never lay and upgrade the same hex during an operation round. I can be wrong about this.


> So should this bug remain open? I'm not sure what you meant above by "using both at the some time i dont think is possible with the current framework", does that mean this bug can't be fixed now?

Its not possible to have 2 companies activate at the same time. This would require a really big code change to get this to work. So i tried to do as many workaround as possible to make the end result the same even if you dont do them in exacly the same order as intended by the rules.

I will close this issue for now. But if there is any more combinations of privates where you cant do as intended im happy to check them out.

**Closed** 2021-03-05 16:29 UTC
Labels: 1822, needs triage

**Comment by Maxwell-Frank** [comment] 2021-03-05 16:42
You can definitely use the "advanced tile lay private" to lay a brown tile in the green phase.  And that brown tile can be upgrading a green dit into a brown plain track, using the "remove small station private." I can try to dig up rules/BGG clarifications of this if necessary, but this does need to be possible.
