### ISSUE TITLE
[1830] Payout/withhold screen says the price will move right even though the corporation is at the top of the market

### ISSUE THREAD

**Issue by slapphappyjazz** [tobymao/18xx#9134] opened 2023-04-21 11:53 UTC
https://18xx.games/game/114522?action=962

The NYC stock token is in the highest space on the market and so will not move if the NYC pays out, but the screen says it will more 1 space right.

This is a very minor bug for 1830, but if present in games with multiple jumps it may have more of an impact.

**Comment by benjaminxscott** [comment] 2023-04-21 18:17
dupe of https://github.com/tobymao/18xx/issues/8536

s.b. fixed by https://github.com/tobymao/18xx/pull/9114

**Closed by benjaminxscott** 2023-04-21 18:17 UTC
Labels: needs triage
