### ISSUE TITLE
1830 cannot be continued 

### ISSUE THREAD

**Issue by gitcior** [tobymao/18xx#10501] opened 2024-03-17 08:59 UTC
The game 156326 suddenly gave such warning:
We're sorry this game cannot be continued due to Set: uninitialized constant Engine::SharePool::Set
Broken action: { "type": "bid", "entity": 17063, "entity_type": "player", "id": 7, "created_at": 1710275825, "company": "SV", "price": 20 }

link: https://18xx.games/game/156326?action=6
Game ID 156326 

Browser: GoogleChrome 122.0.6261.129

**Comment by ollybh** [comment] 2024-03-17 10:53
Duplicate of #10484.

**Closed by ollybh** 2024-03-17 10:53 UTC
Labels: needs triage
