### ISSUE TITLE
1828 "Show Last Route and Tile For:" not showing one of the trains

### ISSUE THREAD

**Issue by mjshaver** [tobymao/18xx#5310] opened 2021-05-11 02:22 UTC
https://18xx.games/game/39123

When selecting Show Last Route and Tile For:" any corporation, it's like one of the trains is set to black.  The map shows the last  tile placed and doesn't show one of the trains.  See the screen shot, the PRR 610 was running two trains and only one showed up in red.

![game 39123](https://user-images.githubusercontent.com/77868485/117748190-2697cb80-b242-11eb-952e-b721e0429327.png)

I have the colors of the first two trains set to red and blue and they work perfectly for other games but something is wrong with 1828.

**Which Browser / Platform?**
- Browser Version
  - Opera Version:76.0.4017.107
- Platform Desktop

Problem is reproduceable on my phone
 - Brave on Mobile

**Comment by crericha** [comment] 2021-05-12 15:30
Probably has to do with the two shells of trains

**Comment by Andy-0711** [comment] 2021-05-20 11:59
I just wanted to report that problem, too.
The selection "Show last route..." allows to select closed corporations (maybe wanted?) and fusioned ones. if you select a corporation with shells it shows the (last ?) route for the old (not fusioned) ones regardles which one you select (by revenue). It do not show any of the shell train routes.
Example: https://18xx.games/game/41941
Chrome Version 90.0.4430.212 (Offizieller Build) (64-Bit)
Desktop: Microsoft Windows [Version 10.0.19043.985]; Microsoft Windows [Version 10.0.17763.1935]; Phone (Android)

**Comment by Andy-0711** [comment] 2021-05-20 13:11
I expect the problem is that there are 2 corporations with the same name: the old (unmerged) and the new (merged). So this problem is basically the same as in https://github.com/tobymao/18xx/issues/5408 and https://github.com/tobymao/18xx/issues/5333. These problems should be resolved together, I guess.

**Comment by dfannius** [comment] 2022-03-06 02:13
#5408 and #5333 are both marked as fixed. Is this issue fixed as well, per @Andy-0711's latest comment?

**Comment by crericha** [comment] 2022-05-08 02:52
Looks fixed.

**Closed by crericha** 2022-05-08 02:52 UTC
Labels: minor bug, 1828.Games
