### ISSUE TITLE
1822PNW problems with P19 Rockport Coal Mine

### ISSUE THREAD

**Issue by ChrisTheCat** [tobymao/18xx#8290] opened 2022-09-06 03:05 UTC
https://18xx.games/game/96627?action=790

M19 owns the Rockport Coal Mine and is unable to place PNW4 in K16.

M19 can trace track through K16 to lay tiles and tokens, despite the fact that tile PNW4 has not been placed.

**Comment by outsidePasser** [comment] 2022-09-06 03:22
Duplicate of #8286

**Closed** 2022-09-07 02:17 UTC
Labels: needs triage
