### ISSUE TITLE
[18CZ] Can run medium trains with a large company

### ISSUE THREAD

**Issue by pstone1** [tobymao/18xx#3975] opened 2021-02-17 19:09 UTC
As shown here, https://18xx.games/game/27929?action=799 KK is able to run a 4+4f train, when a large company should only be able to run E trains.

**Comment by Zwergenpunk** [comment] 2021-02-17 20:37
Thanks but Irs fixed already.. Your game is pined

**Comment by benjaminxscott** [comment] 2021-02-17 21:08
duplicate of #3952

**Closed by benjaminxscott** 2021-02-17 21:08 UTC
Labels: 18CZ, bug
