### ISSUE TITLE
1849 Game Broke

### ISSUE THREAD

**Issue by jerryyeti** [tobymao/18xx#10074] opened 2023-12-31 22:40 UTC
https://18xx.games/game/144496?action=10

We were actually pretty far into the game. Not sure what broke. The AFG was first first company, and now it has reverted to the beginning with an error and the CTL as the first company.

**Comment by michaeljb** [comment] 2023-12-31 22:59
This was caused by #10070, fixed by the seed migration.

**Closed by michaeljb** 2023-12-31 22:59 UTC
Labels: needs triage
