### ISSUE TITLE
[Harzbahn 1873] https://18xx.games/game/46378 is stuck

### ISSUE THREAD

**Issue by KKiermeier** [tobymao/18xx#6008] opened 2021-07-13 19:11 UTC
https://18xx.games/game/46378 is stuck, and the player whose turn it is says that he cannot act, in this case: bid on the NWE concession that is for auction.

**Comment by roseundy** [comment] 2021-07-14 14:54
This looks like another javascript vs. server issue. It will take me a bit to debug.

**Comment by roseundy** [comment] 2021-07-15 03:54
I can't reproduce this, and it looks like the player was able to bid. Closing.

**Closed by roseundy** 2021-07-15 03:54 UTC
Labels: needs triage
